### ISSUE TITLE
Add timeout to wait for CompletionStages / Futures.

### ISSUE THREAD

**Issue by tkruse** [assertj/assertj-core#1150]
CompletionStage/Future assertions should provide timeouts such as `assertThat(future).completesWithin(1000)`... to allow testing with multiple threads without unpredictable race conditions.

The name of the method is up to discussion. A timeout parameter might also be added to existing asserts, such as

     CompletableFuture<String> foo;
     assertThat(foo).isCompletedWithin(3000, TimeUnit.SECONDS)
     assertThat(foo).hasFailedWithin(3000, TimeUnit.SECONDS)

The Awaitility library design should be taken into consideration.

Discussed in #1010

**Comment by pswiatowski** [comment]
I can work on this.

**Comment by hadrienk** [comment]
Sorry for digging up an old issue, but what happened to `failsWithin()`?

**Comment by joel-costigliola** [comment]
`succeedsWithin` has been added, let's finish this issue by adding `failsWithin`

**Comment by hadrienk** [comment]
I think the best is to pass whatever exception was thrown (including cancellation) and let the user chain the correct assertions based on the contract of CompletableFuture.

```
// Interrupted
assertThat(tokenFuture).failsWithin(duration).isInstanceOf(InterruptedException.class);

// Cancelled
assertThat(tokenFuture).failsWithin(duration).isInstanceOf(CancellationException.class);

// Time out
assertThat(tokenFuture).failsWithin(duration).isInstanceOf(TimeoutException.class);

// Generic failure.
assertThat(tokenFuture).failsWithin(duration).isInstanceOf(ExecutionException.class)
    .hasCauseInstanceOf(MyOwnException.class);
```

Regarding the `hasFailed()`, I was not part of the discussion but it seems to me that the cancelation should be a failure as well. The documentation states the following: 

> Since (unlike FutureTask) this class has no direct control over the computation that causes it to be completed, cancellation is treated as just another form of exceptional completion. Method cancel has the same effect as completeExceptionally(new CancellationException()). Method isCompletedExceptionally() can be used to determine if a CompletableFuture completed in any exceptional fashion.

But again, maybe this was discussed and there's a good reason I cannot not see?

**Comment by joel-costigliola** [comment]
I agree that would be the most natural.

I remember spending quite a bit of time trying to get the `CompletableFuture` assertions right and not being fully happy with them but at the time that was the best I could think of, in hindsight I would probably do it differently today, I'll consider deprecating `hasFailed` as part of this piece of work.

**Comment by hadrienk** [comment]
I think the confusion can come from the tense, I'd rename `hasFailed()` to `isFailed()` to better reflect that the check is done on the state - as in `isCompletedExceptionally()` - and does blocks on anything. But IMO those assertions are better done manually against the method.

Some shortcuts with the type might be nice? What do you think?
```
assertThat(tokenFuture).interruptsWithin(duration);
assertThat(tokenFuture).cancelsWithin(duration);
assertThat(tokenFuture).timesoutWithin(duration);
```

**Comment by joel-costigliola** [comment]
`assertThat(tokenFuture).timesoutWithin(duration);` reads nicely but the other a bit less,  `isInterruptedWithin` sounds better.

I see the usefulness of `timesoutWithin` but the other ones don't seem to me as useful.
