### ISSUE TITLE
isXmlEqualToContentOf and similar checks should enable description on parse exception

### ISSUE THREAD

**Issue by tkruse** [assertj/assertj-core#1286]
#### Summary

When running xml comparisons, it would be useful to be able to print the xml on parse exceptions using as().

Currently a RuntimeException is thrown instead of an assertion error.

#### Example

```java
assertThat("<foo></bar>").as("show me").isXmlEqualTo("<foo></foo>");
```

causes "show me" not to be printed

```
[Fatal Error] :1:8: The element type "foo" must be terminated by the matching end-tag "</foo>".

java.lang.RuntimeException: Unable to format XML string

	at org.assertj.core.util.xml.XmlStringPrettyFormatter.toXmlDocument(XmlStringPrettyFormatter.java:73)
	at org.assertj.core.util.xml.XmlStringPrettyFormatter.xmlPrettyFormat(XmlStringPrettyFormatter.java:45)
	at org.assertj.core.internal.Strings.assertXmlEqualsTo(Strings.java:877)
	at org.assertj.core.api.AbstractCharSequenceAssert.isXmlEqualTo(AbstractCharSequenceAssert.java:980)
	at com.example.Example.testExample(Example.java:19)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 8; The element type "foo" must be terminated by the matching end-tag "</foo>".
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at org.assertj.core.util.xml.XmlStringPrettyFormatter.toXmlDocument(XmlStringPrettyFormatter.java:71)
	... 32 more```

**Comment by joel-costigliola** [comment]
Fair enough.

This will have a low priority as we recommend using XMLUnit for xml assertions but contributions are always welcome.

**Comment by TendoPW** [comment]
I would like to work on this issue.

**Comment by joel-costigliola** [comment]
Sure go for it @TendoPW

**Comment by TendoPW** [comment]
Sorry for disturbing you @joel-costigliola 
I noticed that the previous code converted XML to a string in `XmlStringPrettyFormatter.prettyFormat()`.

In `prettyFormat()`, if an exception thrown due to an XML format error is caught, a `runtime exception` is thrown.

The way I plan to solve this issue is, in the process of converting XML into a string and comparing, catch that runtime exception, and then throw an assert error.

But I am not sure what kind of assertion error I  should use. Could you give me some advice?

The code will be like:
```
public void assertXmlEqualsTo(AssertionInfo info, CharSequence actualXml, CharSequence expectedXml) {
    // check that actual and expected XML CharSequence are not null.
    // we consider that null values don't make much sense when you want to compare XML document as String/CharSequence.
    checkCharSequenceIsNotNull(expectedXml);
    assertNotNull(info, actualXml);
    // we only use default comparison strategy, it does not make sense to use a specific comparison strategy
    try {
        final String formattedActualXml = xmlPrettyFormat(actualXml.toString());
        final String formattedExpectedXml = xmlPrettyFormat(expectedXml.toString());
        if (!comparisonStrategy.areEqual(formattedActualXml, formattedExpectedXml))
        throw failures.failure(info, shouldBeEqual(formattedActualXml, formattedExpectedXml, comparisonStrategy,
        info.representation()));
    } catch (Exception e) {
        throw xxxxxxxxx
        // (I am not sure what should throw here...)
    }
}
```

**Comment by joel-costigliola** [comment]
I think we can go with directly throwing an Assertion error built with `AssertionErrorCreator.assertionError(message, actual, expected, cause)` where `message` indicates which XML was badly formatted (we want to report which of actual or expected was invalid).  

Note that `AssertionErrorCreator.assertionError(message, actual, expected, cause)` needs to be added, at the moment there's only `AssertionErrorCreator.assertionError(message, actual, expected)`.

Moreover `isXmlEqualTo` javadoc must be updated to tell users what happened when bad xml is given.

**Comment by TendoPW** [comment]
> I think we can go with directly throwing an Assertion error built with `AssertionErrorCreator.assertionError(message, actual, expected, cause)` where `message` indicates which XML was badly formatted (we want to report which of actual or expected was invalid).
> 
> Note that `AssertionErrorCreator.assertionError(message, actual, expected, cause)` needs to be added, at the moment there's only `AssertionErrorCreator.assertionError(message, actual, expected)`.
> 
> Moreover `isXmlEqualTo` javadoc must be updated to tell users what happened when bad xml is given.

Thanks! I am working on it.

**Comment by TendoPW** [comment]
Sorry for disturbing you again @joel-costigliola 

Another question is that if `AssertionErrorCreator` is used, it seems that the `AssertionErrorCreator` class does not directly provide a method for inputting `assertioninfo`, which results in the `as` method is still not available, although the thrown exception is already `AssertionError`. Should I directly add `info.description()` to message in `assertionErrorCreator.assertionError(message, actualXmlString, expectedXmlString, xmlFormatIncorrect)` to make `as` available?

It seems `ShouldBeEqual` already has a similar function.

**Comment by joel-costigliola** [comment]
You are not disturbing at all, that's a fair point. 

I think the best approach then  would be to overload `failWithActualExpectedAndMessage` and add a cause parameter:
```java
protected void failWithActualExpectedAndMessage(Object actual, Object expected, Throwable, cause, String errorMessageFormat, Object... arguments) {
    String errorMessage = Optional.ofNullable(info.overridingErrorMessage())
                                  .orElse(format(errorMessageFormat, arguments));
    String description = MessageFormatter.instance().format(info.description(), info.representation(), errorMessage);
    // this method needs to be added
    AssertionError assertionError = assertionErrorCreator.assertionError(description, actual, expected, cause);
    Failures.instance().removeAssertJRelatedElementsFromStackTraceIfNeeded(assertionError);
    removeCustomAssertRelatedElementsFromStackTraceIfNeeded(assertionError);
    throw assertionError;
  }
```
`failWithActualExpectedAndMessage` takes care of any description or overridden error message.
This still requires to add `AssertionErrorCreator.assertionError(message, actual, expected, cause)`.

Makes sense?

**Comment by joel-costigliola** [comment]
To test `failWithActualExpectedAndMessage` look and adapt  `AbstractAssert_failWithActualExpectedAndMessage_Test`

**Comment by joel-costigliola** [comment]
Closing this as there is no active contribution for this and XMLUnit is the way to go.
