### ISSUE TITLE
hasOnlyOneElementSatisfying() (and others) returning void rather than self

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#1301]
#### Summary

 Some assertions not returning self type.

#### Example
The following assertions return type are `void` instead of `SELF`:
```java
EnumerableAssert.isNullOrEmpty();
EnumerableAssert.isEmpty();
AbstractIterableAssert.hasOnlyOneElementSatisfying(...);
```
#### Detail

I think I can understand the reasoning behind `isNullOrEmpty()` and `isEmpty()` being declared void -  there are no further useful assertions that can be performed on an object once you've established that it is null or empty. So this looks like it's done by design (that seems to be the implication in #275

`hasOnlyOneElementSatisfying()` is a bit harder to explain in this way. In fact, the way I discovered this issue was because I had a list with multiple elements and I wanted to assert that it had two elements with two different conditions, but I didn't care what order they were in. I was trying to use this method with two invocations chained after each other. The second wouldn't chain because of this issue.

I'm assuming this is a simple oversight, but thought to ask the question of wiser & more experienced AssertJ heads than me.

**Comment by kriegfrj** [comment]
Ok, I've just played around with this a bit more and I think I have misread the intent of `hasOnlyOneElementSatisfying()`. I read it as "only one element in this collection satisfies the given condition (but there may be other elements)", but it seems that it actually means "this collection has only one element, and that element satisfies the given condition". In the latter case, the void return type makes more sense. I think that the assertion name is perhaps a bit ambiguous, but it's probably too late to change that now.

I have gotten around my problem for now by using havingExactly(1, <Condition>), but it would be nice if there was an equivalent with Consumers (like allSatisfying()) rather than Predicates.

**Comment by joel-costigliola** [comment]
Another user was also confused about it I was thinking either to rename it `isSingletonWhoseElementSatisfies` or simply get rid of checking it is a singleton.

I prefer the former as it is not ambiguous, the latter might still be interpreted as checking a singleton.

Thoughts ?

**Comment by joel-costigliola** [comment]
The preferred approach is using [`singleElement()`](https://assertj.github.io/doc/#assertj-core-group-navigation-singleElement) chained with [`satisfies`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractAssert.html#satisfies(java.util.function.Consumer)).
