### ISSUE TITLE
Deep comparison of Iterables?

### ISSUE THREAD

**Issue by kerrykimbrough** [assertj/assertj-core#1312]
#### Summary

This is a common testing pattern. But I'm new to AssertJ and it's not clear to me if AssertJ offers any support. Advice?

#### The Problem

A test wants to verify that an actual Iterable contains **exactly** the contents expected. (For now, assume this means "in any order", although the order-specific variation is also common.) Where "exactly" means that:

- each expected element has an actual counterpart that is `equals` to it 
- and each expected element and its actual counterpart match using property-by-propery comparison
- and the same strategy is applied recursively to all element properties that implement Iterable
- and a failure message identifies each expected or actual element without an `equals` counterpart
- and, when all elements have `equals` counterparts, a failure message for any property mismatch identifies exactly which property of which element (property) failed to match.

#### Deep comparison = identity + values

The problem arises because "deep comparison" of Iterable instances involves two distinct questions:

1. Identity: Does an expected element exist?
1. Values: Does an actual element contain all of the values expected for it?

So choosing to compare either by `equals` (identity, i.e. "primary key" fields) _or_ by properties (values, i.e. non-key fields) is insufficient. You need to do both. First by identifying `equals` counterparts, then by matching properties. And recursively applying the same comparison to Iterable property values.

**Comment by joel-costigliola** [comment]
I know AssertJ lacks a user guide but I'm working on it (here's a wip version https://assertj.github.io/doc/).

Use [`containsExactly`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#containsExactly-ELEMENT...-) for exact comparison (including the order) or [`containsExactlyInAnyOrder`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#containsExactlyInAnyOrder-ELEMENT...-) if the order does not matter.

AssertJ allows to compare elements field by field recursiveley with [`usingRecursiveFieldByFieldElementComparator`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIterableAssert.html#usingRecursiveFieldByFieldElementComparator--).  It compares elements fields (honoring `equals` if a field type has an overridden `equals` method).

It does not exactly matches your need, the comparison fails at the first difference and does not show the field difference but the assertion error message (like `containsExactly`).

Note that a work is in progress to revamp the recursive comparison API in #1002.

**Comment by joel-costigliola** [comment]
Done and documented https://assertj.github.io/doc/#assertj-core-recursive-comparison-for-iterable
