### ISSUE TITLE
MapAssert: Add a way to mix containsOnly and containsOnlyKeys in a single call

### ISSUE THREAD

**Issue by mihhail-lapushkin** [assertj/assertj-core#1313]
I like using the strict `MapAssert#containsOnly`. However, sometimes I have entries containing random values and for them I can only use key assertions. In this case I have 2 options:
1) Do `containsOnlyKeys` with all entries, followed by `contains` with non-random entries. Drawbacks: duplicated code + less strict `contains` misses unexpected extra entries.
2) Just use `contains`. Drawbacks: random keys are not asserted at all + less strict `contains` misses unexpected extra entries.

Something like this would have solved my problem:
```java
assertThat(map).containsOnly(
  entry("aKey", "aValue"),
  key("aRandomKey"))
```

Or maybe some existing API can solve it as well?

**Comment by joel-costigliola** [comment]
It feels the first solution is the best, I'm not sure to understand why you would miss extra entries if you have checked that the keys were right. I get there is a bit of duplicated verification on the keys but that's not too bad IMO. At the end of the day if some values are random then you can only validate the keys.

It looks like to me that if you could control the source of randomness (by mocking basically) you could rewrite your tests without the randomness issue.

**Comment by mihhail-lapushkin** [comment]
Yeah, I think the second drawback is not valid.

**Comment by joel-costigliola** [comment]
I guess the only way to make it easier would be for AssertJ to have a magic value to represent any value and provide a way to build entries with it, something like `entryWithAnyValue(key)`. 
What I'm not sure of is whether it is possible to have a magic value compatible with `Entry<? extends K, ? extends V>` which is the entry expected by `contains`. 
I'm also not sure to like introducing magic value to much in AssertJ codebase.

**Comment by joel-costigliola** [comment]
Closing is as not an AssertJ but more a test design one.
