### ISSUE TITLE
AbstractSoftAssertions.proxies protected but SoftProxies class not public 

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#1323]
#### Summary

Using AssertJ with soft assertions in an OSGi environment.

I'm also using Mockito, which is a little annoying because Mockito always hard asserts. So I had the idea to add a method like this to my `SoftAssertions` subclass:

````java
public void softly(Runnable run) {
    try {
        run.run();
    } catch (AssertionError e) {
       proxies.collectError(e);
    }
}
````

Problem is, although `proxies` is protected and visible to my subclass, its type `SoftProxies` is package-private and is not. Thus it won't compile.

I'd have offered a fix, but this is probably more of an architectural issue that needs some more thought from a core developer, depending on whether you really want the functionality of `proxies` exposed to subclasses . Possibilities are:

1. Make `proxies` package-private or private, so that it is not intended for subclasses to use.
2. Make `SoftProxies` public and part of the API.
3. Change it to use a different type or a publicly-available interface (eg, `ISoftProxies`) which the package-private `SoftProxies` class then implements.

**Comment by kriegfrj** [comment]
As an aside, the very idea of the `softly` method I think would be a useful addition to the AssertJ soft assertions core, if it does not already exist in some form that I am not aware of. It would allow you to easily turn "hard" assertions in 3rd party assertion libraries into soft versions, and would look quite neat when used with lambdas.

@joel-costigliola , if you think this is worthy, I'll raise a new, separate issue to address it where we can fight over (I mean, calmly discuss!) the most fluent naming for the method.

**Comment by joel-costigliola** [comment]
@kriegfrj can you give a more concrete example ?

Could you use the [`satisfies`](http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractAssert.html#satisfies-java.util.function.Consumer-) with soft assertions to achieve your goal ?

**Comment by kriegfrj** [comment]
Hi @joel-costigliola ,

I didn't think to try and use `satisifes()` - thanks for the suggestion. I took your advice and had a look - I think it could work, but it is slightly more verbose:

````java
    softly.assertThat(mockLog).satisifes(m-> verify(m).log(Level.SEVERE, "expecting error message"));
```` 
vs:
````java
    softly.runAssertion(() -> verify(mockLog).log(Level.SEVERE, "expecting error message"));
```` 

Regardless if you think something like `runAssertion()` is a good idea or not, the issue raised in the OP still stands I think.

**Comment by kriegfrj** [comment]
Note that the `runAssertion()` was added in #1460 (it ended up being called `check()`).

I think that it still an issue that a protected field uses a package-private type - either the field should also be package-private, or else the type should be public (or extract a public interface).

I think with the changes in #1817, it would be reasonable to make this field package-private or even private - all of its functionality is accessible through the (public) methods of `SoftAssertion` so there is no need to access it directly.

**Comment by joel-costigliola** [comment]
I guess we can close this one @kriegfrj?

**Comment by kriegfrj** [comment]
I still think it's an issue that the field is protected but the type is package private. I'd lean toward making the field package private. But it's not a major functional issue,  more of a code style issue.

**Comment by joel-costigliola** [comment]
I'll do that, thanks for the update.
