### ISSUE TITLE
Add extracting with AssertFactory

### ISSUE THREAD

**Issue by tarioch** [assertj/assertj-core#1467]
#### Summary
Would it be possible to add a version of extracting that takes an AssertFactory as an additional argument? Similar to the assertThat that also provides this functionality.

#### Example

What works
```java
assertThat(myObject.getCollection(), MyAssertions.assertThat)
```

What would be nice to work
```java
assertThat(myObject)
 .extracting(MyClass::getCollection, MyAssertions.assertThat)
```

**Comment by joel-costigliola** [comment]
@tarioch could you provide a more complete example to clarify what you want ? 
My guess is you want to have strongly typed navigational assertion, it that right ?

The only existing feature that might help at the moment  is [`extracting(String propertyOrField, Class<P> extractingType)`](https://static.javadoc.io/org.assertj/assertj-core/3.12.2/org/assertj/core/api/AbstractIterableAssert.html#extracting-java.lang.String-java.lang.Class-).

**Comment by tarioch** [comment]
there is the assertThat for collections which allows to specify the assertFactory for a single element in the collection (assertThat(Iterable<? extends ELEMENT> actual, AssertFactory<ELEMENT,ELEMENT_ASSERT> assertFactory))
I think it would be great to also have the same functionality available on the extracting functions, basically adding an extracting method which takes an additional AssertFactory.

**Comment by joel-costigliola** [comment]
Just to be crystal clear, could you give a use case of why we would need that ?

**Comment by tarioch** [comment]
Sure, I'm thinking of something like

```java
class Address {
   private String country;

   ....
}

class Person {
   private List<Address> addresses;

   ....
}


class AddressAssertion ... {

  public AddressAssertion isSwitzerland() {
    ... 
  }
}


void testFoo() {
   ...
  assertThat(person)
      .extracting(Person::getAddresses, AddressAssertion::new)
      .first()
      .isSwitzerland();
}
```

**Comment by joel-costigliola** [comment]
Thanks, that's what I had in mind.

I have no objection adding this capability.

**Comment by joel-costigliola** [comment]
Done with  [`extracting(Function, InstanceOfAssertFactory)`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function,org.assertj.core.api.InstanceOfAssertFactory))
