### ISSUE TITLE
Provide comparable assertions for non comparable class when given a comparator

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#1492]
#### Summary

Comparable assertions are restricted to `Comparable` types, this could extended for non `Comparable` types if a proper `Comparator` is given.

This is issue was created after this discussion https://stackoverflow.com/questions/55811121/assertj-fluent-ordering-tests-with-custom-comparator/55828748?noredirect=1#comment98322628_55828748.

#### Example

```java
Foo foo1 = ...;
Foo foo2 = ...;
FooComparator fooComparator = ...;
assertThat(foo1).usingComparator(fooComparator).isGreaterThan(foo2);
```

We want to avoid  to copy comparable assertions in `AbstractAssert` as it would pollute the API.

The idea of this improvement is to return a `ComparableAssert` from `usingComparator` and then chain comparable assertions.  Moreover we would ideally keep the original type assertions.
Whether this is technically possible is something to explore as part of this improvement.

**Comment by wettera** [comment]
> #### Summary
> Comparable assertions are restricted to `Comparable` types, this could extended for non `Comparable` types if a proper `Comparator` is given.
> 
> This is issue was created after this discussion https://stackoverflow.com/questions/55811121/assertj-fluent-ordering-tests-with-custom-comparator/55828748?noredirect=1#comment98322628_55828748.
> 
> #### Example
> ```java
> Foo foo1 = ...;
> Foo foo2 = ...;
> FooComparator fooComparator = ...;
> assertThat(foo1).usingComparator(fooComparator).isGreaterThan(foo2);
> ```
> 
> We want to avoid to copy comparable assertions in `AbstractAssert` as it would pollute the API.
> 
> The idea of this improvement is to return a `ComparableAssert` from `usingComparator` and then chain comparable assertions. Moreover we would ideally keep the original type assertions.
> Whether this is technically possible is something to explore as part of this improvement.

`usingComparator` in `AbstractAssert` should return SELF type, return `ComparableAssert` will cause compile failure
![message](https://user-images.githubusercontent.com/38947732/83346196-ef8c1b00-a34c-11ea-9469-3b1099250101.png)

**Comment by joel-costigliola** [comment]
I did a quick spike on this one, I'm actually not sure if this technically feasible.
Moreover we can loose some strongly typed assertion, for example:
```java 
assertThat("foo").usingComparator(CASE_INSENSITIVE)
                 .isGreaterThan("bar") // ok 
                 .startsWith("f"); // does not compile if we return `ComparableAssert`.
```

**Comment by joel-costigliola** [comment]
Closing it in favor of https://github.com/assertj/assertj-core/issues/2041 and potentially `assertThat(T actual, Comparator<T> comparator)` if that works
