### ISSUE TITLE
Provide a way to assert all the fields a given class can contain

### ISSUE THREAD

**Issue by x80486** [assertj/assertj-core#1496]
#### Summary

It would be nice if `AssertJ` provides a way to _check_ that a given class contains **only** a certain set of fields/members. I (and probably others) usually test creation/instantiation workflows for POJOs; for instance:

```kotlin
import nl.jqno.equalsverifier.EqualsVerifier
import org.assertj.core.api.Assertions
import org.junit.jupiter.api.Test
import java.time.Clock
import java.time.ZonedDateTime

internal class IssueTest {
  @Test
  fun `create proper instance`() {
    val start = ZonedDateTime.now(Clock.systemUTC())
    val instance = Issue("the title", "some description", "full content")
    val end = ZonedDateTime.now(Clock.systemUTC())
    Assertions.assertThat(instance)
        .hasNoNullFieldsOrPropertiesExcept("id")
        .satisfies {
          Assertions.assertThat(it.title).isEqualTo("the title")
          Assertions.assertThat(it.description).isEqualTo("some description")
          Assertions.assertThat(it.content).isEqualTo("full content")
          Assertions.assertThat(it.status).isEqualTo(Issue.Status.CREATED)
          Assertions.assertThat(it.createdAt).isBetween(start, end)
          Assertions.assertThat(it.modifiedAt).isBetween(start, end)
          Assertions.assertThat(it.version).isEqualTo(0)
        }
  }

  @Test
  fun `contract between equals and hashCode must be fulfilled`() {
    EqualsVerifier.forClass(Issue::class.java)
        .withIgnoredFields("createdAt", "modifiedAt", "id", "version")
        .verify()
  }
}
```

In that realm, we keep adding/removing/updating/modifying members, so having that kind of assertion(s) will let you have more confidence when you do such things.

I see there is already a `hasFieldOrProperty("fieldName")`, so I'm thinking about something like `hasOnlyFieldsOrProperties("field1", "field2", ..., "fieldN")`.

In the end, I'm not sure if this is super useful for some others, but I thought I would start somewhere :sunglasses:

**Comment by joel-costigliola** [comment]
would this help: http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractObjectAssert.html#hasFieldOrPropertyWithValue-java.lang.String-java.lang.Object- ?

**Comment by x80486** [comment]
I saw that one too, but like the documentation states: `Asserts that the actual object has the specified field or property with the given value`.

What I was trying to achieve is to check that a class **only** have _these_ fields/members. Later on, if you add more and/or remove/update any of the fields, the test will fail because it's expected to have the previous set.

**Comment by joel-costigliola** [comment]
Alright got it, `hasOnlyFieldsOrProperties` looks fine to me if you are keen to contribute it.

**Comment by wht-github** [comment]
hi, i'm trying to implement `hasOnlyFieldsOrProperties` , i have a bit confused about the error message.
If following the format as `hasFieldOrProperty`, the expecting message will be like
```
Expecting
ClassA has properties and fields named VarA, VarB, VarC
```
Is it ok, or need to print which fields and properties is absent or surplus, like
```
Expecting
ClassA has properties and fields named VarA, VarB, VarC
Absent : A , B
Surplus: D
```
Because i think `hasFieldorProperty` indicating what is absent, but `hasOnlyFieldsOrProperties` doesn't.
Which one is better?

**Comment by joel-costigliola** [comment]
I have renamed the assertion `hasOnlyFields` to make it clear it only looks at fields and not properties.
