### ISSUE TITLE
Be more descriptive in assertThat(Throwable) by including the stacktrace

### ISSUE THREAD

**Issue by bbottema** [assertj/assertj-core#1505]
#### Summary
I was happy to find an assertThat specifically for `Throwable`, but it ignores the stacktrace contained within. It should describe the value using the stacktrace instead of simply `.toString()`.

#### Example
```java
    public static void main(String[] args) {
        Exception e;
        try {
            throw new RuntimeException();
        } catch (RuntimeException e2) {
            e = e2;
        }

        assertThat(e).isNull();
    }
```
Output:
> Exception in thread "main" org.junit.ComparisonFailure: expected:<null> but was:<java.lang.RuntimeException>
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at Test.main(Test.java:35)

#### Workaround
To work around it I have to manually describe it using a custom utility (in this case I used Apache Commons Lang):
```java
assertThat(e).as(ExceptionUtils.getStackTrace(e)).isNull();
```
Output:

> Exception in thread "main" org.junit.ComparisonFailure: [Exception:
> 	java.lang.RuntimeException
> 	at Test.main(Test.java:30)
> ] expected:<null> but was:<java.lang.RuntimeException>
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at Test.main(Test.java:35)

**Comment by joel-costigliola** [comment]
That's a good idea, I think we should limit the stack trace to a few lines by default for readability but allow users to override that behavior, WDYT ?

**Comment by bbottema** [comment]
Excellent!

**Comment by Eveneko** [comment]
I'll work on it ;-)

> That's a good idea, I think we should limit the stack trace to a few lines by default for readability but allow users to override that behavior, WDYT ?

It seems like getting stack trace by default when we just execute `assertThat(e).isNull();`.
BUT how to allow users to override tthe behavior? I'd like to hear your advice ;-)

**Comment by joel-costigliola** [comment]
That's a good candidate to put in the `org.assertj.core.configuration.Configuration`

**Comment by Eveneko** [comment]
Option1:
```
Exception in thread "main" org.opentest4j.AssertionFailedError: [java.lang.RuntimeException
	at org.assertj.core.util.Throwables_Description_Test.main(Throwables_Description_Test.java:11)
] 
Expecting:
 <java.lang.RuntimeException>
to be equal to:
 <null>
but was not.
```
Option2:
```
Expecting:
 [java.lang.RuntimeException
	at org.assertj.core.util.Throwables_Description_Test.main(Throwables_Description_Test.java:11)
 ]
to be equal to:
 <null>
but was not.
```
@bbottema @joel-costigliola
We consider two representation format for this case. which one is better?

**Comment by joel-costigliola** [comment]
I prefer Option 2 (without []), option 1 is a bit confusing as we display the exception first and then we repeat it with a short description, somehow one might think both are different.
