### ISSUE TITLE
and()-ing multiple matches(...) assertions

### ISSUE THREAD

**Issue by behrangsa** [assertj/assertj-core#1529]
#### Summary

It would be nice if we could chain multiple `matches(...)` assertions fluently using `and()` connectors, with support for sub properties.

#### Example

```java
// POJOs

class Person {
    private String firstName;

    private Address address;

    public Person(String name, Address address) {
        this.firstName = name;
        this.address = address;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }
}

class Address {
    private String country;

    private String state;

    public Address(String country, String state) {
        this.country = country;
        this.state = state;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
}
// Test

Person person = new Person("Steve Jobs", new Address("USA", "California"));

assertThat(person)
                .enter(p -> p.getAddress())
                    .matches(a -> a.getCountry()).isEqualTo("USA")
                    .and()
                    .matches(a -> a.getState()).isEqualTo("California")
                .exit()
                .matches(p -> p.getFirstName()).isNotNull().isEqualTo("Steve Jobs");
```

**Comment by joel-costigliola** [comment]
[extracting](https://static.javadoc.io/org.assertj/assertj-core/3.12.2/org/assertj/core/api/AbstractObjectAssert.html#extracting-java.util.function.Function-) for object already provides forward navigation, what is not supported is navigating back to the parent object.

I see why you would want navigation, this is not something straightforward to implement and at the moment you always have the traditional way to perform assertions where you just repeat  `assertThat(person)`, this is why I would not rate this as a high priority feature (lot of work for an average value).

In your example `and()` is not needed all chained assertions must succeed for the test to pass (`and` semantic).

I'm happy to raise the priority of this feature if more users vote for it.

**Comment by behrangsa** [comment]
You are right, the `and()` call is not needed, but if I’m not wrong at the moment it’s not possible to write assertions like these, especially if our POJOs have many complex properties, with just one `assertThat` call.

**Comment by joel-costigliola** [comment]
You are correct, you can't do all assertions  with just one `assertThat` call, this is what I was trying to say here:
> you always have the traditional way to perform assertions where you just repeat assertThat(person)

**Comment by kprzygudzki** [comment]
Sure you can do that with a single `assertThat` call:
```
assertThat(person)
    .satisfies(p -> assertThat(p.address)
        .satisfies(a -> assertThat(a.country).isEqualTo("USA"))
        .satisfies(a -> assertThat(a.state).isEqualTo("California")))
    .satisfies(p -> assertThat(p.firstName).isNotNull().isEqualTo("Steve Jobs"))
```
Of course, you can use the AbstractAssert#matches method as well, although the logic might get slightly more complex.

It definitely can be done and I've used a pattern like this successfully numerous times.

There is a question you might want to ask yourself, however: is this coupling your tests too much to the implementation of the Person class?
Perhaps it would be better to create a Person assert that would allow you to assert certain attributes of a person object without accessing the properties directly through getters.

**Comment by joel-costigliola** [comment]
Closing it since an alternative has been proposed.
