### ISSUE TITLE
assertThat(streamSupplier.get()).isEqualTo(streamSupplier.get()) Always Fails

### ISSUE THREAD

**Issue by Bill** [assertj/assertj-core#1545]
#### Summary
If I have a stream-supplying lambda or a stream-returning method, I ought to be able to compare the result of `get()`ing it or executing it twice in succession. But apparently I can't (profitably) send a`Stream` to `isEqualTo()`.

#### Example

```java
  private static Supplier<Stream<Integer>> ss = () -> Stream.of(1, 2);

  @Test
  void compareWithSelf() {
    /*
     This fails:

      org.opentest4j.AssertionFailedError:
      Expecting:
       <[1, 2]>
      to be equal to:
       <java.util.stream.ReferencePipeline$Head@7e0e6aa2>
      but was not.
      Expected :java.util.stream.ReferencePipeline$Head@7e0e6aa2
      Actual   :[1, 2]

     */
    assertThat(ss.get()).isEqualTo(ss.get());
  }
```

This works:

```java
    assertThat(ss.get()).containsExactly(1,2);
```

As does this:

```java
    // to compare a stream on RHS, it must be converted to something iterable
    final Iterable<Integer> c = ss.get().collect(Collectors.toList());
    assertThat(ss.get()).isEqualTo(c);
```

But in my test it would be more natural to do it the first way (providing the result of `ss.get()` directly to `isEqualTo()`. I'd like my stream-supplying lambda (`ss` in my example) to be the source of truth for this assertion.

Is there some good reason why AssertJ doesn't support this, or is it simply a bug?

**Comment by ebundy** [comment]
The behavior is conform to `Stream.equals()`. 
`.isEqualTo()` relies on the `equals()` method, here the `Stream.equals()` method that is not overriden (so it is the reference equality).  
Here each supplier invocation instantiates a distinct stream object. 
Use the same and it should be fine :

```
  private static Supplier<Stream<Integer>> ss = () -> Stream.of(1, 2);
  Stream<Integer> s =  ss.get();
  assertThat(s).isEqualTo(s);

```

> But in my test it would be more natural to do it the first way

This will break the `isEqualTo()` semantic that is not designed to perform some conversion. So, I don't think that it is the right way.

This works and is rather acceptable : 

    assertThat(ss.get()).containsExactly(1,2);

And fon't forget that a stream is not a List or a collection. Comparing two streams with equals() is really not a conventional requirement. You compare rather the stream content or the stream equality (in terms of object)

**Comment by joel-costigliola** [comment]
@ebundy thanks, this is exactly what I would replied. I'm just going to add that `assertThat(ss.get())` converts the [stream to a list](https://static.javadoc.io/org.assertj/assertj-core/3.12.2/org/assertj/core/api/Assertions.html#assertThat-java.util.stream.Stream-) in order to be able to chain multiple assertions.

@Bill any objections for me before I close this issue ?

**Comment by Bill** [comment]
Not really @joel-costigliola. It's just that the asymmetry here made me think maybe something better (or at least different) was possible. Look again at the error message:

```java
      org.opentest4j.AssertionFailedError:
      Expecting:
       <[1, 2]>
      to be equal to:
       <java.util.stream.ReferencePipeline$Head@7e0e6aa2>
      but was not.
      Expected :java.util.stream.ReferencePipeline$Head@7e0e6aa2
      Actual   :[1, 2]
```

Notice how the first part shows what appears to be the contents of a collection:

```java
      Expecting:
       <[1, 2]>
```

And then the second part goes off the rails:

```java
      to be equal to:
       <java.util.stream.ReferencePipeline$Head@7e0e6aa2>
```

Why the asymmetry?

I figured, perhaps naïvely, that it would be possible to treat streams specially. Clearly, AssertJ is already applying a terminal operation (collecting) one of the streams (otherwise the error message wouldn't contain the `1,2`). I was looking for AssertJ to do the same thing for the other half of the assertion.

This asymmetry seems to indicate that I can make no useful assertions about streams directly. I was hoping that the asymmetry could be removed so that the most common case would "just work". Alas.

**Comment by joel-costigliola** [comment]
The asymmetry is to allow assertions on streams as if they were lists, which we believe is quite handy otherwise you need to convert the stream to list yourself, the other option would be for AssertJ to provide assertions specific to streams but they would not be chainable as the first assertion that requires to inspect the stream would consume it.

> I was looking for AssertJ to do the same thing for the other half of the assertion.
Maybe, we need to think about that.

> This asymmetry seems to indicate that I can make no useful assertions about streams directly
on the expected side yes, on the stream under test you have all the list/iterable at your disposal.
