### ISSUE TITLE
usingElementComparatorIgnoringFields does not work for map array

### ISSUE THREAD

**Issue by yarafed** [assertj/assertj-core#1592]
#### Summary
Hello!
Could you, please, tell me, if there is a possibility to ignore map "keys" when we check that map array contains map object.

#### Example

```java
       HashMap<String, Integer> object1 = new HashMap<String, Integer>() {
            {
                put("John", 25);
            }
        };
        HashMap<String, Integer> object2 = new HashMap<String, Integer>() {
            {
                put("John", 12);
            }
        };
        Map<String, Integer> object3 = new HashMap<String, Integer>() {
            {
                put("Tom", 23);
            }
        };
        Map[] array = new Map[] {object2, object3};
        assertThat(array).usingElementComparatorIgnoringFields("John").contains(object1);
```

**Comment by joel-costigliola** [comment]
Sorry, this had fallen under my radar, will look at it shortly (ping me if I don't)

**Comment by joel-costigliola** [comment]
@yarafed not at the moment, I don't see this to be supported in the near future TBH.
What was your use case, JSON object comparison?

**Comment by phx1999** [comment]
can i try to solve it

**Comment by mct10** [comment]
Hi, we are a student group and we would like to look into this. We may not be able to implement it with extremely high quality, but we will try our best.

**Comment by joel-costigliola** [comment]
@mct10 thanks but I'm going to close this one since it is a rather exotic use case and @yarafed has not replied to my question.
@yarafed feel free to give us more details on your use and we will reconsider this demand.
