### ISSUE TITLE
Incorporate ConcurrentUnit's Waiter funtionality into AssertJ

### ISSUE THREAD

**Issue by leventov** [assertj/assertj-core#1646]
#### Summary

I think it would be nice to incorporate [ConcurrentUnit](https://github.com/jhalterman/concurrentunit)'s Waiter into AssertJ to aid writing multi-threaded tests.

#### Example

The problem with combining AssertJ and ConcurrentUnit as any two Java libraries is that Waiter doesn't support AssertJ's API:
```java
@Test
public void shouldDeliverMessage() throws Throwable {
  final Waiter waiter = new Waiter();

  messageBus.registerHandler(message -> {
    // Not currently possible with ConcurrentUnit
    waiter.assertThat(message).isEqualTo("foo");
    waiter.resume();
  };
  
  messageBus.send("foo");
  
  // Wait for resume() to be called
  waiter.await(1000);
}
```

FYI @jhalterman

**Comment by jhalterman** [comment]
FWIW, I agree that something like `Waiter` would be nice in assertj.

**Comment by scordio** [comment]
Looking at the example, it seems that Waiter is offering already assertion APIs, so maybe ConcurrentUnit could include AssertJ as a dependency and implement [WithAssertions](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/WithAssertions.java) in Waiter.

Would it make sense?

**Comment by joel-costigliola** [comment]
I did not know about ConcurrentUnit, cool to learn about it!

I don't have a strong opinion here, on one hand AssertJ could integrate `Waiter` as it seems it's only a few classes without dependencies, on the other hand I tend to think providing concurrent utilities is outside AssertJ's scope as it's not directly assertion related, increasing its scope will make AssertJ more work to maintain.

@jhalterman I'm curious how `ConcurrentUnit` compares to http://www.awaitility.org/ (which supports AssertJ).

**Comment by jhalterman** [comment]
Awaitility and ConcurrentUnit solve the same problems, waiting on multi-threaded actions to occur in a test and being able to perform assertions from different threads, but they use different approaches. Awaitility polls a specified method whereas ConcurrentUnit gives you a `Waiter` that you can pause and resume explicitly.

**Comment by fduminy** [comment]
Another alternative is [tempus-fugit](http://tempusfugitlibrary.org/recipes/2013/03/17/wait-for-ui-element/)

**Comment by joel-costigliola** [comment]
nice, did not about that one

**Comment by joel-costigliola** [comment]
Closing this since at the moment the scope of AssertJ is big enough and alternatives exist.
