### ISSUE TITLE
move Assertion* classes to a different package

### ISSUE THREAD

**Issue by xenoterracide** [assertj/assertj-core#1694]
it's annoying that these are in the same package, I might suggest java6 be split into its own jar now, and that the others be moved to a different package (makes sense for exports with jigsaw support too?) this is just me griping, feel free to close if it's a terrible idea for the next major version [example of issue screenshot](https://imgur.com/a/rnyKJpc)

**Comment by joel-costigliola** [comment]
This is an IDE issue in the first place, in eclipse for example you can select your favorites import and you don't have this issue.
