### ISSUE TITLE
Facilitate expected value type coercion

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#1823]
#### Summary

There are some data types where it is convenient to intialise them using primitive literal types. Some examples that I've come across:

BigDecimal: useful to use Strings, floats, BigInts, etc.
timestamps: useful to convert between Date, Timestamp, Instant and long

In practice, I've seen either an explosion of different method signatures to support the different arg types (making the API more cluttered and harder to use), or else lots of conversion code cluttering up the tests.

I think we should consider widening the allowed types for expected, supplying a `protected` coercion function in `AbstractAssert`, eg `protected ACTUAL coerce(Object expected)`

#### Example

Current situation using `BigDecimal` (explosion of methods to facilitate coercion):
```java
assertThat(bd).isEqualTo(new BigDecimal("123.45"));
assertThat(bd).isEqualToByComparingTo("123.45");
```
This also does not include other common types that you might want to compare with, like BigInteger or float. And not all of the comparison methods have even the String variant to coerce (eg, there is no isBetween(String, String), isBetween(String, BigDecimal), etc).

Current situation using `Date` (explosion of methods to facilitate coercion):
```java
assertThat(date).isEqualTo(new Date(123456));
assertThat(date).isEqualTo("1 Jan 1970");
```
DateAssert has `String` alternatives for many (most) of the comparison functions - they come at the price of cluttering up the API with duplicates. It also doesn't cater for other common alternatives (eg, comparing against an `Instant` or a `long`/`Long`).

In some of my own custom assertions, I've found it more useful to have an (eg) `isEqualTo(Object)` or `isGreaterThan(Object)`, etc, and then at runtime coerce that value to the type of ACTUAL to do the actual comparison. This avoids the explosion of API methods to cater for each of the different types for each of the comparison fields.

The reason I mention it here though is because some of the core assertions (and in particular, AbstractComparableAssert/ComparableAssert, even `usingComparator()`) force the method signatures of the comparable methods to have (eg) `isGreaterThat(Date)` and don't allow you to specify `isGreaterThan(Object)`. Perhaps we could consider retro-fitting this coercion to some of the core assertion types.

Admittedly, widening the type of `expected` all the way to Object comes at the cost of compile-time type safety. However, I believe that this can be managed - in my own assertions, the coercion function will fail-fast - first checking for valid types, and throwing `InvalidArgumentException` with a helpful error message if the wrong type is supplied. While you would obviously prefer compile-time type safety in a production environment, I think that fail-fast run-time type safety is typically good enough in a test code, where you're typically being pretty defensive about catching the exceptions anyway.

(The ideal solution though, IMO, would be for the Java generics mechanism to allow "union" type parameters, similar to the multi-catch() syntax. Then you could specify (eg): `isEqualTo(Date | Long | Instant expected)`, which type-erasure would convert to the same signature at runtime (ie `isEqualTo(Object)`), but the compiler would then be able to enforce the type checking at compile time.)

Thoughts?

**Comment by ars-java** [comment]
I think that it's a very long issue having props & cons for different cases. Could you post few concrete API examples you wanna see in the lib.

**Comment by joel-costigliola** [comment]
Hi @kriegfrj ,

We had a discussion with the team and we have a preference for keeping the type safety, we know it's bloating the API but if you are looking for a given assertion you will find a few variations like `isBefore(Date)` and `isBefore(String)` but we feel if users to starts code completion a few letters, the number of possibilities narrows down quickly.
The other point we are not super comfortable with is that is we have `isBefore(Object)` it's not clear which types are actually supported until you read the javadoc whereas is code completion gives you `isBefore(Date)` and `isBefore(String)` this is pretty clear.

**Comment by kriegfrj** [comment]
I understand. Perhaps we can all go and vote for union generic types to be added to a future version of Java. :smile:
