### ISSUE TITLE
SoftAssertionExtension to support (non-static) field injection/injecting on `beforeEach()` lifecycle method

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#1824]
#### Summary

A big thanks to @sbrannen for #1544.

I've been using `SoftAssertionsExtension` in anger recently, and I would like to propose a tweak.

`SoftAssertionsExtension` does not support injecting `SoftAssertions` into any lifecycle method. This was a deliberate choice by @sbrannen as documented in #1544. 

A common pattern I use in my tests is to factor out some boilerplate assertions into private methods, then have the main test method delegate to them. Because I'm doing multiple assertions per test, I like to use soft assertions for this.

Under the old pattern, this would be easy because the extension would be registered as a field using `@RegisterExtension` and so the same instance it would be visible to the private methods as well as the test method that called them.

With `SoftAssertionExtension`, I have to manually store the reference to the soft assertion instance in every method. So now all my test methods look like this:

```java
@ExtendWith(SoftAssertionsExtension.class)
public class MyTest {
  SoftAssertions softly;

  void myTest(SoftAssertions softly) {
    this.softly = softly;
    softly.assertThat(something).isWorking();
    assertBoilerplate();  
  }

  private void assertBoilerplate() {
    softly.assertThat(boilerplate).isFunctioning();
  }
}
```
Sometimes I forget to put the `this.softly = softly` line in, and I get a weird `NullPointerException` and I waste some precious brain cycles figuring out and fixing my mistake (especially precious in my case as I have so few of them to spare). 

I would like instead to be able to use the default injection pattern used by `TestInfo`, where it can be injected and stored into `@BeforeEach`. Or perhaps even to support injecting it into a field. Then my code simplifies to:

```java
@ExtendWith(SoftAssertionsExtension.class)
public class MyTest {
  SoftAssertions softly;

  @BeforeEach
  void beforeEach(SoftAssertions softly) {
    this.softly = softly;
  }

  void myTest() {
    softly.assertThat(something).isWorking();
    assertBoilerplate();  
  }

  private void assertBoilerplate() {
    softly.assertThat(boilerplate).isFunctioning();
  }
}
```

Given that @sbrannen made the deliberate decision to prohibit injection on lifecycle methods, I thought it would be worth having a closer look to see what his concern was. If I have understood correctly, the primary concerns are:
* potentially confusing behaviour when invoked in the wrong context (specifically, that `assertAll()` will not be called when expected, or perhaps not called at all);
* not behaving well in conjunction with Jupiter's advance threading/lifecycle features like @TestInstance(PER_CLASS) and/or parallel execution.

I can see how that concern would apply to `@BeforeAll`, `@AfterAll` and `@AfterEach`, but I don't think these same concerns apply to `@BeforeEach`:
* to the best of my knowledge, `@BeforeEach` methods are run on the same thread as the test that they precede;
* the `@BeforeEach` method is guaranteed to run before the test that it precedes, which is in turn guaranteed to run before `SoftAssertionsExtension.afterTestExecutionCallback()` (which calls `assertAll()`).

I can see that `@TestInstance(PER_CLASS)` could cause issues in combination with concurrent execution. I guess that's why the Jupiter team saw fit to make single threading the default mode for `@TestInstance(PER_CLASS)` (per the discussion in junit-team/junit5#1511). Anyone that needs to 1. use `@TestInstance(PER_CLASS)`, and 2. use concurrent execution and 3. wants to store the `SoftAssertions` object in an instance field will need to know to store it in a `ThreadLocal` field. My guess is that if they're already cluey enough to know about *and* use `@TestInstance(PER_CLASS)` with concurrency (which involves override not one, not two, but three defaults!), then they're already aware of these issues...

Before I rush ahead and implement this, I'd like to get @sbrannen's feedback, as I notice that his implementation mutated from his first spike (https://github.com/joel-costigliola/assertj-core/issues/1418#issuecomment-505450463), which supported `@BeforeEach`, to his final implementation in #1544 which didn't. I'd be interested to know his reasoning before I proceed.

**Comment by kriegfrj** [comment]
Apologies to @sbrannen - I just found his answer which was already recorded in https://github.com/joel-costigliola/assertj-core/issues/1418#issuecomment-505815527

> I realized that it never makes sense to have a SoftAssertions instance scoped beyond a specific method...if there is a failure in a `@BeforeEach` method, the `@Test` method should never execute.

I can see the logic behind this in certain circumstances. However, I am of the opinion that each "BeforeEach/Test/AfterEach" should be considered a single composite test, and that it *does* makes sense to have `SoftAssertions` scoped for a single test (even where that test is split over multiple methods). If I want my `@BeforeEach` to prevent execution of the corresponding test, then I can always use a `RuntimeException` or a hard assertion as appropriate for certain assertion failures (I could even manually call `softly.assertAll()` if I want) - just because the `SoftAssertions` object is supplied doesn't mean that I have to use it for all assertions.

Thoughts?

**Comment by joel-costigliola** [comment]
We were looking at a similar approach in https://github.com/joel-costigliola/assertj-core/pull/1784 where we would initialize any soft assertions instance field to a new SoftAssertion before each test and call assertAll() after each test.

I'm under the impression that this approach if fine except for classes combining `Lifecycle.PER_CLASS` with `@Execution(CONCURRENT)` (see https://github.com/joel-costigliola/assertj-core/pull/1784#issuecomment-608972854). 
@sbrannen what do you think ? (I'm happy to raise a JUnit 5 github issue summarizing what we are trying to achieve if that makes it easier for you or the JUnit team).

Also related https://github.com/joel-costigliola/assertj-core/pull/1771 for constructor injection of soft assertions

**Comment by kriegfrj** [comment]
My apologies for not seeing those other related issues/PRs.

FWIW, IMHO I don't think it's necessary for us to raise an issue in the JUnit 5 repo. This strikes me more as an AssertJ issue than a JUnit 5 issue.

I am in favour of supporting constructor injection (#1771), `@BeforeEach` injection, and field injection (#1784). Field injection would be the ultimate in minimising boilerplate code in my tests.

I understand the concerns about the "principle of least surprise", but I think we need to be pragmatic about applying it - if we apply it too strictly, we'll never implement any new feature because there's the potential that someone, somewhere *might* be surprised by it... Indeed, if we applied it too strictly, no one would ever use constructor or field injection at all due to the potential complications with `PER_CLASS` lifecycles and concurrency.

It is true that field, constructor and `@BeforeEach` injection can have weird side-effects with certain combinations of lifecycle and concurrency. However, out-of-the-box, Jupiter is configured for `PER_INSTANCE` and single-threading, and that is how most developers will use it. The principle of least surprise is clearly honoured in these cases.

I would argue that anyone who is using advanced features of Jupiter, like `PER_CLASS` or concurrency, should be aware of the potential issues, and therefore the risk that they will be surprised when they encounter them is low. But we can minimise this even further by:
1. documenting these limitations in the Javadoc, and/or
2. runtime sanity checks (eg, `supportsParameter()` should throw a `ParameterResolutionException` if we attempt constructor injection while a `PER_CLASS` lifecycle is in force).

**Comment by joel-costigliola** [comment]
Soft assertion field injection is supported https://assertj.github.io/doc/#assertj-core-junit5-soft-assertions-field-injection
