### ISSUE TITLE
AssertJ 4

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#1841]
Let's define the scope of the next major version:

- [ ] Move to Java 11
- [ ] Drop multi-release build in favor of module-only
- [ ] Delete all [deprecated elements](https://github.com/joel-costigliola/assertj-core/search?q=deprecated&unscoped_q=deprecated)
- [ ] Internal error message refactoring
- [ ] use the new recursive comparison API for iterables element by element comparison, 
      this would lead to remove API made irrelevant like: 
  - [ ] `usingComparatorForElementFieldsWithNames` 
  - [ ] `usingComparatorForElementFieldsWithType`
  - [ ] `usingElementComparatorOnFields`
- [ ] Replace `java.lang.reflect.AccessibleObject#isAccessible` with `java.lang.reflect.AccessibleObject#canAccess` (#1958)

Any comments, proposals or feedback?

**Comment by ishanarora04** [comment]
Hey , I would like to start work on few of these elements . Is it still available for grabs ?

**Comment by scordio** [comment]
@ishanarora04 sure it is! We would need a separate main branch to start merging version 4 topics, but this can be prepared once the first pull request is raised.

**Comment by bjhargrave** [comment]
>     * Drop multi-release build in favor of module-only

Does this mean JPMS modules only? We need to continue to support OSGi users. So the [osgi-test](https://github.com/osgi/osgi-test) team would like to work with you to ensure continued OSGi support.

**Comment by scordio** [comment]
@bjhargrave yes, that point was about JPMS. Working together making sure we are still supporting OSGi users properly would be perfect!

**Comment by onacit** [comment]
I'm not sure of the schedule but shouldn't Java-8 which is LTS-ish be still count?
Say, I'm the one who is pleased using Assert-J with [spring-boot-test](https://search.maven.org/search?q=a:spring-boot-test) which depends itself on assertj-*.
Shouldn't we consider those major frameworks/platforms regarding their plans for Java-11?
Thanks.

**Comment by scordio** [comment]
There is no schedule yet for AssertJ 4. I can easily imagine versions 3 and 4 to continue together for some time, where we would backport any Java 8 compatible feature to version 3.
