### ISSUE TITLE
Verify type of element in iterable with order in mind

### ISSUE THREAD

**Issue by maciejwalkowiak** [assertj/assertj-core#1907]
#### Summary

Create new assertion on `AbstractIterableAssert` that verifies type of each element of iterable taking order into consideration.

#### Example

I am working currently with following code where it's important to verify that elements are of correct type in particular order:

```java
List<CredentialsProvider> credentialsProviders = ....;

assertThat(credentialsProviders).hasSize(3);		
assertThat(credentialsProviders.get(0)).isInstanceOf(AWSStaticCredentialsProvider.class);
assertThat(credentialsProviders.get(1)).isInstanceOf(EC2ContainerCredentialsProviderWrapper.class);
assertThat(credentialsProviders.get(2)).isInstanceOf(ProfileCredentialsProvider.class);
```

Initial though was to replace these 3 lines with 
```java
assertThat(credentialsProviders).hasOnlyElementsOfTypes(AWSStaticCredentialsProvider.class, EC2ContainerCredentialsProviderWrapper.class, ProfileCredentialsProvider.class);
```

but it does not verify the order of types.

My idea is to create an assertion that would verify if all elements of an iterable match given type like:

```java
assertThat(credentialsProviders).containsOnlyElementsOfTypes(AWSStaticCredentialsProvider.class, EC2ContainerCredentialsProviderWrapper.class, ProfileCredentialsProvider.class);
```

I am happy to implement it if you confirm it's a good idea or propose another solution to the problem 🙂

**Comment by scordio** [comment]
We would like to avoid `containsOnlyElementsOf` assertions because they can be misleading for some users (e.g., see #1075 and #1513).

What about `containsExactlyElementsOfTypes`?

A not so nice solution with existing assertons would be:

```java
List<Object> list = Arrays.asList("asd", 3, Duration.ofDays(1));
Class[] types = new Class[] { String.class, Integer.class, Duration.class }; // raw types

assertThat(list).extracting(Object::getClass)
                .containsExactly(types); // unchecked
```

but it would trigger raw types and unchecked assignment warnings.

**Comment by maciejwalkowiak** [comment]
`containsExactlyElementsOfTypes` sounds good to me. Can I implement it?

**Comment by joel-costigliola** [comment]
Due to the limitations of using extracting, I'm fine with `containsExactlyElementsOfTypes`, @maciejwalkowiak  thanks for contributing it.

**Comment by joel-costigliola** [comment]
@maciejjaskowski are you still interested in contributing this one?

**Comment by RGalways17** [comment]
Hi @joel-costigliola

**Comment by RGalways17** [comment]
Hi@joel-costigliola,
 Is this still open for contribution? I'd like to implement the `containsExactlyElementsOfTypes`.

**Comment by joel-costigliola** [comment]
It is @RGalways17 thanks! Let us know if you need some guidance.

**Comment by RGalways17** [comment]
@joel-costigliola I've noticed the `containsExactlyElementsOf` and `containsExactly`. How about having a similar implementation: a `containsExactlyElementsOfTypes` calling `containsExactlyTypes(toArray(iterable))` and let `containsExactlyTypes` be like `assertThat(credentialsProviders).containsExactlyTypes(AWSStaticCredentialsProvider.class, EC2ContainerCredentialsProviderWrapper.class, ProfileCredentialsProvider.class);` . 
Also, I think the assertion can be made similar to  `assertContainsExactly`, just extract a List<Object>with `getClass` to store the types and `diff` can be used(if I'm not mistaken about how it works). Then the rest part can be the similar to `assertContainsExactly`, only modifying the failure information.

**Comment by joel-costigliola** [comment]
@RGalways17 I think we only want to add `containsExactlyElementsOfTypes(Class... expectedTypes)`  but not overload it with `containsExactlyElementsOfTypes(List<Class<?>> expectedTypes)`, is that what you had in mind @scordio?

> Also, I think the assertion can be made similar to assertContainsExactly, just extract a Listwith getClass to store the types and diff can be used(if I'm not mistaken about how it works). Then the rest part can be the similar to assertContainsExactly, only modifying the failure information.

I agree! 
Ideally the error message should indicate that we are checking the elements types but we can start using the generic `ShouldContainExactly` to get a feel of the error message and change it if we find it could be better.

**Comment by scordio** [comment]
> @RGalways17 I think we only want to add `containsExactlyElementsOfTypes(Class... expectedTypes)` but not overload it with `containsExactlyElementsOfTypes(List<Class<?>> expectedTypes)`, is that what you had in mind @scordio?

Yes, that is what I had in mind, but looking again at `ObjectEnumerableAssert` I'm wondering if it makes more sense to stay closer to the existing assertions like `hasAtLeastOneElementOfType`, `hasOnlyElementsOfType`, `hasOnlyElementsOfTypes` and `doesNotHaveAnyElementsOfTypes`.

What about `hasExactlyElementsOfTypes(Class<?>... types)`?

**Comment by joel-costigliola** [comment]
Yes, good point let's do `hasExactlyElementsOfTypes(Class<?>... types)`, I think the naming is better

**Comment by RGalways17** [comment]
Great. I'll get started:)
