### ISSUE TITLE
anySatisfy could give clearer error messages

### ISSUE THREAD

**Issue by abrudin** [assertj/assertj-core#1923]
#### Summary
When working with unordered lists or sets, there is a reasonable risk that objects do not implement equals in a way one would hope, especially in legacy code. That makes it hard to assert that the "correct" elements are indeed in there. anySatisfy is a great start, but it is still a little unclear where the assertions in the consumer fail. One way would be to show, for every element, what went wrong. There is of course a risk that this will turn out a little verbose, but in a failing test more information is always preferable to less.

#### Example

```java
class ComplexElementWithObjectEquals {
  private String key;
  private AnotherComplexElement complexInner;
  private int number;
  ...
}
List<ComplexElementWithObjectEquals> list = new ArrayList<>();
list.add(new ComplexElementWithObjectEquals("a", anotherComplexElement, 1, ...);
list.add(new ComplexElementWithObjectEquals("b", anotherComplexElement, 3, ...);
assertThat(list).anySatisfy(cewoe -> {
  assertThat(cewoe.getKey()).isEqualTo("c");
  assertThat(cewoe.getComplexInner()).satisfies(...);
  assertThat(cewoe.getNumber()).isGreaterThan(1);
  ...
}
```
This test could fail for any number of reasons, but the inner asserts just disappears, as the message is something along the lines
```
Expecting any element of: ComplexElementWithObjectEquals#1, ComplexElementWithObjectEquals#2 to satisfy the given assertions requirements but none did.
```
A way to make this clearer would be to display the first failing assertion for each element:
```
Expecting any element of: ComplexElementWithObjectEquals#1, ComplexElementWithObjectEquals#2 to satisfy the given assertions requirements but none did:
ComplexElementWithObjectEquals#1:
Expecting:
 <"a">
to be equal to:
 <"c">
but was not.
ComplexElementWithObjectEquals#2:
Expecting:
 <"b">
to be equal to:
 <"c">
but was not.
 
```

**Comment by joel-costigliola** [comment]
Not sure what version you are using but with the current version 3.18.1, you have a pretty detailed error:
Example:
```java
assertThat(list("Luke", "Leia", "Yoda", "Obiwan")).anySatisfy(s -> {
   assertThat(s).hasSize(4);
   assertThat(s).contains("W");
});
```
fails with this error:
```
Expecting any element of:
  <["Luke", "Leia", "Yoda", "Obiwan"]>
to satisfy the given assertions requirements but none did:

  <"Luke">
error: 
Expecting:
 <"Luke">
to contain:
 <"W"> 

  <"Leia">
error: 
Expecting:
 <"Leia">
to contain:
 <"W"> 

  <"Yoda">
error: 
Expecting:
 <"Yoda">
to contain:
 <"W"> 

  <"Obiwan">
error: 
Expected size:<4> but was:<6> in:
<"Obiwan">
```

**Comment by joel-costigliola** [comment]
@abrudin does that address your issue? If so I'll close it.

**Comment by abrudin** [comment]
Yes, now it seems to be working great. Not sure what version I was using back then but when I retry older versions I can't reproduce the problem so we can definitely close this issue. Thanks for taking your time to look at it!
