### ISSUE TITLE
Move succeedsWithin to FutureAssert

### ISSUE THREAD

**Issue by rupert-madden-abbott** [assertj/assertj-core#1929]
`succeedsWithin` is currently only defined on `CompletableFutureAssert` but is compatible with a regular `Future` also.

This means if I have a method that returns a `Future` (but I know it is a `CompletableFuture`), I have to cast it in order to use this assertion.

Placing this assertion on `FutureAssert` instead would let it work in either case.

**Comment by joel-costigliola** [comment]
sure!

**Comment by rupert-madden-abbott** [comment]
Awesome, thanks! I'll put a PR together.

**Comment by rupert-madden-abbott** [comment]
Done. 

As far as I can see, the assertions need to stay on CompletableFutureAssert also. I've tried to share as much code between them but let me know if there is a better way.

Please let me know if you'd like any changes.

**Comment by joel-costigliola** [comment]
succeedsWithin had been added to FutureAssert: https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractFutureAssert.html#method.summary
