### ISSUE TITLE
"returns" method is not intuitive

### ISSUE THREAD

**Issue by mgrafl** [assertj/assertj-core#1932]
#### Summary
The [```AbstractObjectAssert.returns(T, Function)```](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractObjectAssert.html#returns(T,java.util.function.Function)) method is not intuitive, considering that similar methods are named [```has```](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractAssert.html#has(org.assertj.core.api.Condition)), [```hasFieldOrProperty```](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractObjectAssert.html#hasFieldOrProperty(java.lang.String)), etc., and that [```hasFieldOrPropertyWithValue```](https://www.javadoc.io/static/org.assertj/assertj-core/3.16.1/org/assertj/core/api/AbstractObjectAssert.html#hasFieldOrPropertyWithValue(java.lang.String,java.lang.Object)) has different argument order. 

Would a method named ```has(Function, T)``` be more appropriate? 

#### Example

```java
assertThat(frodo).has(TolkienCharacter::getName, "Frodo");
```

**Comment by scordio** [comment]
The methods you listed are targeting different use cases from my point of view:
* `has` allows to use a custom `Condition`, which could do much more than single property assertion
* `hasFieldOrProperty` and `hasFieldOrPropertyWithValue` only accept a `String` property name, which means they are not type safe but they support reflective access

As mentioned in the javadoc, the main use case of `returns()` together with the `from()` syntax sugar is to assert several properties one after the other:

```java
assertThat(frodo).returns("Frodo", from(TolkienCharacter::getName)
                 .returns(33, from(TolkienCharacter::getAge));
```

I find `has(Function, T)` too similar to `has(Condition)`, it might be confusing to understand the purpose of one or the other.

**Comment by mgrafl** [comment]
Okay thanks for the clarification. 
For someone reading the tests, it certainly reads nicely.
But at least to me, the ```returns``` method seemed a bit hidden when I was writing tests. I only found it in the link referenced by ```hasFieldOrPropertyWithValue``` Javadoc. 
Maybe an example could be given in the assertj guide (https://assertj.github.io/doc/)?

**Comment by joel-costigliola** [comment]
Documentation will be addressed with https://github.com/assertj/doc/issues/80
