### ISSUE TITLE
Add isCloseTo for Duration

### ISSUE THREAD

**Issue by sparty02** [assertj/assertj-core#1942]
#### Summary
Add isCloseTo assertion for java.time.Duration

#### Example

```java
assertThat(Duration.ofSeconds(59)).isCloseTo(Duration.ofMinutes(1), within(Duration.ofSeconds(10)));
```

The implementation could probably just be a facade that simply does `duration.toMillis()`, and delegates to `LongAssert`.  This will likely need a new Offset class, e.g. `DurationOffset` to support the `offset` parameter to `isCloseTo`.

**Note** I considered genericizing this to adding isCloseTo for `java.time.TemporalAmount` which would encompass both `Duration` and `Period`, but periods are a bit different as they can't directly be converted down to something like millis.  Their lowest precision is a day, different days potentially  have different numbers of seconds, etc....so the `isCloseTo` algorithm would have to be different for them.

**Comment by sparty02** [comment]
Let me know if you'd like me to submit a PR!

**Comment by joel-costigliola** [comment]
PR always welcome, I would not delegate to `LongAssert` as the error message would be related to long and not duration.
you can't reuse the existing Offset class so introducing a `DurationOffset` would be needed.

Let's start first with `Duration`, `Period` can be added later on with some refactoring if we find it handy to share some implementation bits.
