### ISSUE TITLE
Github action release

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#1986]
#### Summary

Investigate if it is possible to create a github action to release assertj-core to maven central.

**Comment by filiphr** [comment]
As far as I know Byte Buddy does a release via an action. 

https://github.com/raphw/byte-buddy/blob/6b1bc2a5e07db2597969af274b4eca3ed31fb5bd/.github/workflows/main.yml#L92-L109

**Comment by joel-costigliola** [comment]
Thanks @filiphr, we'll look at it.

**Comment by scordio** [comment]
I think the [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) event would be a good fit for a release job. I'll put together a PR to see what we can do.

**Comment by joel-costigliola** [comment]
The release steps are `mvn release:prepare release:perform`, would need to use the `-B` option to avoid being prompt for the next development version.

**Comment by scordio** [comment]
The same [workflow](https://github.com/assertj/assertj-parent-pom/blob/main/.github/workflows/release.yml) as `assertj-parent-pom` will be introduced to release 3.22.0.
