### ISSUE TITLE
Remove references to assertj.org

### ISSUE THREAD

**Issue by agabrys** [assertj/assertj-core#1995]
#### Summary
The `assertj.org` domain points to dangerous pages (contain malware). Some of them are even blocked by network providers and browsers. The latest release 3.17.2 still points to it. The project URL is equal to `http://assertj.org/assertj-core`. This URL is inherited from [assertj-parent-pom](https://github.com/assertj/assertj-parent-pom). The URL has been fixed 3 months ago (https://github.com/assertj/assertj-parent-pom/issues/45), but it has not been released yet (https://github.com/assertj/assertj-parent-pom/issues/74).

Update the parent when possible and release a new version of `assertj-core`.

**Comment by joel-costigliola** [comment]
Good catch thanks!

**Comment by joel-costigliola** [comment]
Fixed by a619a163 and https://github.com/assertj/assertj-parent-pom/commit/5274a20f670072750f43c3f27d798a5f9edca259
