### ISSUE TITLE
Add Abstract(Float|Double)Assert#is(Not)(Negative|Positive)Infinity

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2005]
#### Summary

I see we already have `is(Not)Nan`.
Can we have a chance for `is(Negative|Positive)Infinity`?

#### Example

```java
final float f = getSome();
//assertThat(f).isEquals(Float.NEGATIVE_INFINITY);
assertThat(f).isNegativeInfinty();
```

**Comment by joel-costigliola** [comment]
Sure.

**Comment by onacit** [comment]
Can I contribute ?

**Comment by scordio** [comment]
Absolutely, thanks @onacit! Please let us know if you have any questions.

**Comment by onacit** [comment]
@scordio Happily created a [PR](https://github.com/assertj/assertj-core/pull/2006). Thank you.
