### ISSUE TITLE
AllSatisfy should fail for empty map

### ISSUE THREAD

**Issue by LomaPL** [assertj/assertj-core#2013]
#### Summary
Assertions specified in `.allSatisfy` block incorrectly pass for empty map. Of course, this can be easily fixed by adding `.isNotEmpty()` but seems to misleading when assertions inside the block pass.

#### Example

```java
    @Test
    public void shouldFailForEmptyMap() {
        Map<String, String> stringMap = new HashMap<>();
        assertThat(stringMap).allSatisfy((a, b) -> {
            assertThat(a).contains("Entry");
            assertThat(b).isEqualTo("A");
        });
    }
```

**Comment by joel-costigliola** [comment]
I understand where you are coming from but at the same time it is consistent with java stream API, ex:
```java
boolean allMatch = Collections.emptyList().stream().allMatch(item -> item == null);
System.out.println(allMatch); // prints true
```

**Comment by ars-java** [comment]
I agree with @joel-costigliola. If you have no elements then your method must not be invoked (must be invoked 0 times). If you wanna fail on empty collection or map you must say it explicitly using `.isNotEmpty()`.

**Comment by joel-costigliola** [comment]
Closing this issue as won't fix, still keen to hear for better counter arguments.
