### ISSUE TITLE
A question about SoftlyExtensions and SoftAssertionsExtension

### ISSUE THREAD

**Issue by KroArtem** [assertj/assertj-core#2017]
#### Summary
Hello! I've noticed there are some great things to use with JUnit5 -  `SoftlyExtensions` and `SoftAssertionsExtension` https://assertj.github.io/doc/#assertj-core-junit5-softly-extension

However, `SoftAssertionsExtension` has to be passed into each test method which is not very convenient, especially if you create helper methods in the same class. This means `SoftAssertions` instance have to be passed into this helper method which makes it cumbersome.

`SoftlyExtensions` sounds great but it has several limitations listed in the doc.

WDYT, isn't it possible to implement `SoftlyExtensions` that will take injected SoftAssertions instance and work with it without listed limitations?

We're using IOC a lot and current SoftAssertions instance is injected, then in `@BeforeEach` it initializes and in `@AfterEach` or directly in tests they're `assertAll`'d.

**Comment by joel-costigliola** [comment]
There will improvements in that area in the next version but the trouble with soft assertions is that they are stateful and that does not play well with JUnit extension model

**Comment by KroArtem** [comment]
Ok, nice to hear some improvements are planned. Is there any roadmap/tickets/issues available? I've looked through opened issues but https://github.com/assertj/assertj-core/issues/1824 seem to be the only one more or less up-to-date.

**Comment by joel-costigliola** [comment]
here it is: https://github.com/assertj/assertj-core/pull/1984, we haven't started the corresponding documentation yet but the javadoc and the tests should already be useful.

**Comment by KroArtem** [comment]
@joel-costigliola , @kriegfrj , I've tried assertj-3.17.3-SNAPSHOT and `@InjectSoftAssertions SoftAssertions softly;` works ok, didn't check parallel execution, though. I am eager to see that in a new release! Hope it'll happen soon 😃 

I'll check parallel execution in a day or two.

**Comment by joel-costigliola** [comment]
@KroArtem #1984 is released, I'm closing this issue but feel free to comment to give us your feedback and we will reopen it if needed.
