### ISSUE TITLE
Add map(…) and flatMap(…) to all <T>Assertions where T has map and flatMap

### ISSUE THREAD

**Issue by lpandzic** [assertj/assertj-core#2023]
#### Summary
When dealing with types of type T that have map and flatMap methods I'd expect <T>Assertions to include map and flatMap aliases similar to https://github.com/assertj/assertj-core/issues/751

**Comment by joel-costigliola** [comment]
I guess you are expecting them on iterables, for them we have [extracting](https://www.javadoc.io/static/org.assertj/assertj-core/3.17.2/org/assertj/core/api/AbstractIterableAssert.html#extracting(java.util.function.Function)) which is a map operation and [flatExtracting](https://www.javadoc.io/static/org.assertj/assertj-core/3.17.2/org/assertj/core/api/AbstractIterableAssert.html#flatExtracting(java.util.function.Function)) which is a flatMap operation.

Are you aware of these operations? 

For optional we have `map` and `flatMap` support.

**Comment by lpandzic** [comment]
Yes I am, but extracting and flatExtracting are not conventional method names for such functionality. If we already have map and flatMap on OptionalAssert I'd expect the same on IterableAssert.

**Comment by joel-costigliola** [comment]
They were created before java 8 and they express IMO better what do you with them in the context of assertions.
Anyway we are happy to add map/flatMap where we have extracting and flatExtracting taking lambdas. (extracting have a bunch of variations that don't take lambdas which we find is not suitable to be aliased as map so we will skip those ones).
