### ISSUE TITLE
isEqualTo() does not always invoke `equals()` method

### ISSUE THREAD

**Issue by bliessens** [assertj/assertj-core#2025]
#### Summary

Implementation of `isEqualTo()` assertion does not always call the actual `equals()` method
of tested type.

#### Example
My expectation is that following example will invoke `MyType.equals()`.
Unfortunately this is not true. Reason is that `StandarComparisonStrategy` delegates to `Objects.deepEquals()` which  returns true when `actual == expected`.

```java
MyType anInstance = new MyType();
assertThat(anInstance).isEqualTo(anInstance);
```

**Comment by scordio** [comment]
The current implementation follows [the contract](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-) of `equals`, where it is mentioned:
> for any non-null reference value x, x.equals(x) should return true

In your example, would you expect `anInstance.equals(anInstance)` to return `false`? This would mean that the custom `equals` implementation is violating the contract. See also #1949.

**Comment by bliessens** [comment]
I do not question the contract of `equals` at all. Neither do I want `anInstance.equals(anInstance)` to return `false`. 
My point is merely that assertj's `isEqualTo` does not always invoke `MyType.equals()` - the method I expect to be tested and asserted.

**Comment by scordio** [comment]
Thanks @bliessens, I got it now. AssertJ is not designed to provide coverage for custom `equals` implementations, because of that we usually suggest [EqualsVerifier](https://jqno.nl/equalsverifier/).

**Comment by bliessens** [comment]
That statement is somewhat surprising. If `isEqualTo()` is not ment to rely on custom `equals()` methods then it should never use a custom `equals()` at all, right?  

However this snippet does call the custom `equals()` method.
```java
MyType instance = new MyType("abc");
assertThat(instance).isEqualTo(new MyType("abc");
```

Also, the javadocs on `isEqualTo()` do not mention anything about **not** using custom equals methods. 

Wouldn't it be better to only allow `isEqualTo()` when a specific comparator is used? This would make the comparison strategy more explicite to users:
```java
assertThat(instance).usingDeepComparison().isEqualTo(other)
assertThat(instance).usingDeepComparisonExcludingFields("name").isEqualTo(other)
```

**Comment by scordio** [comment]
> That statement is somewhat surprising. If `isEqualTo()` is not ment to rely on custom `equals()` methods then it should never use a custom `equals()` at all, right?

Sorry, I missed an adjective:

> AssertJ is not designed to provide _full_ coverage for custom equals implementations

The custom equals is of course used in the `isEqualTo` assertion, except in the case you spotted or for null checks. This is usually not an issue as the contract is still satisfied, but if you are looking for full coverage `isEqualTo` is not a good tool for it hence our suggestion to use EqualsVerifier.

**Comment by bliessens** [comment]
Thanks for the feedback @scordio. Much appreciated.
