### ISSUE TITLE
can the Failures class be moved from internal to util?

### ISSUE THREAD

**Issue by Zegveld** [assertj/assertj-core#2026]
We've got an OSGI project that uses both assertj and xmlunit-assertj ( https://github.com/xmlunit/xmlunit )
But now we get issues with that xmlunit uses the Failures class while this is not exposed.

The reason why they use it is to: 
1. [determine whether or not to filter (their own) elements from the exception's stacktrace.](https://github.com/xmlunit/xmlunit/blob/main/xmlunit-assertj/src/main/java/org/xmlunit/assertj/CustomAbstractAssert.java#L49) (not avoidable)
2. [create the AssertionError class](https://github.com/xmlunit/xmlunit/blob/main/xmlunit-assertj/src/main/java/org/xmlunit/assertj/error/ComparisonFailureErrorFactory.java#L51). (avoidable)

I've been looking at the xmlunit-assertj code and checking if I could find another way to achieve this without usage of the Failures class but did not find it. 
I could avoid the creation of the AssertionError route, but I would still end up with the same problem concerning the first point.

**Comment by scordio** [comment]
Before exposing `Failures` we could try to work together with `xmlunit-assertj` to change the access to internal classes. If something is needed but not available, we can probably find a way to expose it via a new public api.

I'll take a look and put here my thoughts.

**Comment by scordio** [comment]
One important point is that `xmlunit-assertj` relies on `assertj-core` 2.9, which is in maintenance mode. We need to check if upgrading to 3.x and Java8 is an option considering XMLUnit requirement section:

> Starting with version 2.8.0 XMLUnit requires Java 7, which has always been the minimum requirement for the AssertJ module. All other modules in versions 2.0.0 to 2.7.0 required Java 6.

**Comment by scordio** [comment]
I put my comments in xmlunit/xmlunit#203.

**Comment by scordio** [comment]
As discussed in xmlunit/xmlunit#203:

>> 1. [determine whether or not to filter (their own) elements from the exception's stacktrace.](https://github.com/xmlunit/xmlunit/blob/main/xmlunit-assertj/src/main/java/org/xmlunit/assertj/CustomAbstractAssert.java#L49) (not avoidable)
>
> `AbstractAssert#removeCustomAssertRelatedElementsFromStackTraceIfNeeded()` is mostly doing what is needed here, but it is `private` and is restricted to AssertJ package. We could refactor this part in `assertj-core` and expose it as `protected` method.

**Comment by joel-costigliola** [comment]
@Zegveld let us know if we can close this issue.

**Comment by Zegveld** [comment]
Fix found in commit [4e04c29ce67b712af1661aae4706c883c20d2c7e](https://github.com/assertj/assertj-core/commit/4e04c29ce67b712af1661aae4706c883c20d2c7e) as discussed at [xmlunit/xmlunit#203](https://github.com/xmlunit/xmlunit/issues/203)

xmlunit's Assertj3 variant tested and works correctly under OSGI.

Therefor closing this issue.
