### ISSUE TITLE
Add doesNotHaveSameHashCodeAs and doesNotHaveToString assertions

### ISSUE THREAD

**Issue by alexisjehan** [assertj/assertj-core#2028]
#### Summary
I sugest to add _doesNotHaveSameHashCodeAs_ and _doesNotHaveToString_ assertions to reflect _isEqualTo_/_isNotEqualTo_. (With a shorter name maybe?)

#### Example

```java
assertThat(foo).isEqualTo(foo);
assertThat(foo).hasSameHashCodeAs(foo);
assertThat(foo).hasToString(foo.toString());

// Would replace:
assertThat(foo).isNotEqualTo(bar);
assertThat(foo.hashCode()).isNotEqualTo(bar.hashCode());
assertThat(foo.toString()).isNotEqualTo(bar.toString());

// By:
assertThat(foo).isNotEqualTo(bar);
assertThat(foo).doesNotHaveSameHashCodeAs(bar);
assertThat(foo).doesNotHaveToString(bar.toString());
```

**Comment by joel-costigliola** [comment]
Looks good to me, I can't think of shorter names.

**Comment by lykims** [comment]
Hi!
I would like to contribute to assertj, and it's my first time. I'm interested in working on this issue. Is this available for me?

**Comment by scordio** [comment]
@lykims sure it is, thanks! Please let us know if you need anything from us.

**Comment by lykims** [comment]
@scordio Is one pull request per method preferable?

**Comment by scordio** [comment]
@lykims yes, the review will be faster and you could reuse the feedback for the style of the second PR

**Comment by lykims** [comment]
@joel-costigliola This issue is half resolved. It was suggested to create one PR per assertion.

Should this issue be reopened so I could implement `doesNotHaveToString` next?

**Comment by joel-costigliola** [comment]
Yes, my bad, would be great
