### ISSUE TITLE
Add method isBetween(Instant, Instant) to AbstractDateAssert 

### ISSUE THREAD

**Issue by ars-java** [assertj/assertj-core#2032]
#### Summary

I think it will be convenient to have in AbstractDateAssert<T> method `isBetween(start: Instant, end: Instant)` because `Data` and `Instant` are the same in meaning (unix time moment). But it's more comfortable to calculate times as `Instant` and don't use `Date.from()` to convert.

#### Example

```java
assertThat(validatingDate).isBetween(Instant.now().minusSeconds(2),  Instant.now().plusSeconds(2))
```

**Comment by joel-costigliola** [comment]
Would it be acceptable for you to convert your date to an instant and use: [isBetween(java.time.Instant,java.time.Instant)](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.0/org/assertj/core/api/AbstractInstantAssert.html#isBetween(java.time.Instant,java.time.Instant))?

**Comment by ars-java** [comment]
Yes, I can convert `validatingDate` to `Instant` and use `isBetween` for `Instant` but then there's no need to have `AbstractDateAssert` in test framework because each `Date` could be converted to `Instant` and saved to variable.  :)  I think that the main reason to use assertj and to have `AbstractDateAssert` insight it is to help programmer to write code easier without his own boilerplate or thinking about such natural conversions. One more reason to have such methods (having `Instant` as parameter) in `AbstractDateAssert` is that `Instant` is an official replacement for `Data` and we must provide the ability to use new better API.

**Comment by joel-costigliola** [comment]
Fair enough.

**Comment by ars-java** [comment]
I think, for completeness, I can contribute all such methods:
```
isEqualTo(Instant instant)
isEqualToIgnoringHours(Instant instant)
isEqualToIgnoringMinutes(Instant instant)
isEqualToIgnoringSeconds(Instant instant)
isEqualToIgnoringMillis(Instant instant)
isNotEqualTo(Instant instant)
isIn(Instant... instants)
isNotIn(Instant... instants)
isBefore(Instant other)
isBeforeOrEqualTo(Instant other)
isAfter(Instant instant)
isAfterOrEqualTo(Instant instant)
isBetween(Instant start, Instant end)
isBetween(Instant start, Instant end, boolean inclusiveStart, boolean inclusiveEnd)
isBetween(Instant start, Instant end, boolean inclusiveStart, boolean inclusiveEnd)
isNotBetween(Instant start, Instant end)
isInSameYearAs(Instant instant)
isInSameMonthAs(Instant instant)
isInSameDayAs(Instant instant)
isInSameHourWindowAs(Instant instant)
isInSameHourAs(Instant instant)
isInSameMinuteWindowAs(Instant instant)
isInSameMinuteAs(Instant instant)
isInSameSecondWindowAs(Instant instant)
isInSameSecondAs(Instant instant)
isCloseTo(Instant instant, long deltaInMilliseconds)
hasSameTimeAs(Instant instant)
usingInstantComparator(Comparator<? super Instant> customComparator)
usingInstantComparator(Comparator<? super Instant> customComparator, String customComparatorDescription)
```

**Comment by joel-costigliola** [comment]
Cool but let's do one thing at a time, let's start with `isBetween` and then we can move to do the other progressively, big PR are really hard to review as you often have the same issues being replicated.

I'm not sure what the usage for `usingInstantComparator` would be, the comparator is for actual (thus Date)

**Comment by ars-java** [comment]
OK, I'm going to do `isBetween`

**Comment by joel-costigliola** [comment]
@ars-java I'm finishing this one

**Comment by ars-java** [comment]
@joel-costigliola I think it's correct to integrate my implementation into main because I took this issue to resolve, the code already have been done and pull requests already have been created before you integrate your implementation.

**Comment by joel-costigliola** [comment]
Sorry @ars-java, I integrated some of your work and since you did not seem active on the issue I took over and informed you about it but then you raised new PRs the thing I had already quite advanced the work so integrated your PRs was more work than finishing the issue.
Don't worry I'll give you full credit for the issue in the release notes.
