### ISSUE TITLE
Can I access the data i added to "as"?

### ISSUE THREAD

**Issue by chaganiu** [assertj/assertj-core#2033]
#### Summary
I am trying to access the value that I put in the `as` method of my soft assert.  I've tried calling the `getMessage()` method but that adds the failure reason to the description.  I'd like to have access to just the description I added to the assert.

I am storing all of my soft assert failures like this:

```java 
private final List<Throwable> errorList = Collections.synchronizedList(new ArrayList<>());
private final HashMap<String, Integer> aggregateErrors= new HashMap<>();

@Test
public void SomeTest() {
  softly.assertThat(csv.getPublisher()).as("publisher").isEqualTo(record.getValue(DATABASE.PUBLISHER));
  .
  .
  .
  .
  errorList.addAll(softly.errorsCollected());
//errorList.addAll(softly.assertionErrorsCollected());
}

@AfterClass
public void AfterClass() {
  errorList.forEach(error -> aggregateErrors.merge(error.getMessage(), 1, Integer::sum));
}
```

`getMessage()` returns `[publisher] expected:<[]> but was:<["foo"]>` and I'm looking for just `publisher`.  It seems that the `detailMessage` field has the value but is there a way for me to get that without reflection?

**Comment by joel-costigliola** [comment]
I think the easiest would be to use a regex to get the description inside the first `[]`.

Note 1: 
The description can be retrieved from the assertions with [getWritableAssertionInfo()](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.0/org/assertj/core/api/AbstractAssert.html#getWritableAssertionInfo()).[descriptionText()](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.0/org/assertj/core/api/WritableAssertionInfo.html#descriptionText()) but not from the assertion error itself (which is a basic exception).

Note 2: 
You can add consumer of assertion description, see https://assertj.github.io/doc/#assertj-core-assertion-description-consumer

**Comment by chaganiu** [comment]
@joel-costigliola do I have access to ` getWritableAssertionInfo()` from the `errorsCollected()` method?  I need to do this after the tests have completed so I can get a sum of the various errors.

**Comment by joel-costigliola** [comment]
Nope `getWritableAssertionInfo` is from `AbstractAssert`

**Comment by joel-costigliola** [comment]
@chaganiu if you don't have any other questions, are you happy for me to close this issue?

**Comment by chaganiu** [comment]
Yes thank you.
