### ISSUE TITLE
Fine-grained Representations

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#2048]
#### Summary

I have recently discovered the `Representation` API. I am looking at using it with osgi-test and with idempiere-test as part of their respective domain-specific assertion libraries, so that they can produce more readable diagnostics by overriding `toString()` implementations in the domain objects.

For maximum usability and code readability, It would be nice if these Representation implementations could be auto-registered. AssertJ already provides a mechanism for this.

However, ideally, different domain-specific libraries would be able to independently register `Representation` implementations for their specific settings  osgi-test and idempiere-test could independently register `Representation` implementations for their respective domains. For example, osgi-test could register a `Representation` implementation for the type `org.osgi.framework.Bundle` while idempiere-test could register one for `org.compiere.model.MInvoice`.

Unfortunately, with the current implementation, the default `Representation` implementation is a global singleton setting that is applied to all objects. 

#### Proposal

I'm open to ideas. I'm thinking something along these lines:

1. Un-deprecate the `ServiceLoader` implementation of `Representation`. `Configuration` is by nature a singleton instance and not well-suited to the modular, multi-implementation approach being offered.
2.  `Representation` will become parameterized. Thus:
```java
public interface Representation<T> {
  String toStringOf(T object);
  String unambiguousToStringOf(T object);
```
Specific implementations of `Representation` can add their own bounds, eg:

```java
public class BundleRepresentation implements Representation<Bundle> {
...
}
```
3. AssertJ Core will collate all of the implementations and build a lookup table from object type to representation. This will be used by the core in determining which representation to use (if not overridden by a call to `usingReperesentation()`).

I think it will be possible to build the lookup table with no further changes to `Representation`, using reflection to find out the bound on `T`. However, if it is not possible, then add a `supportedType()` method to `Representation` that the core can interrogate:

```java
public interface Representation<T> {
  String toStringOf(T object);
  String unambiguousToStringOf(T object);
  default Class<T> supportedType() {return (Class<T>)Object.class; }
```

**Comment by filiphr** [comment]
This is an interesting idea @kriegfrj. 

As food for thought another alternative would be instead of parametrizing it or adding method for supported type to create a composite of all available `Representation`(s) loaded through the service loader + the default implementation.
The `toStringOf` will be invoked until it returns non-null value. 

e.g.

```
public class CompositeRepresentation implements Representation {

    protected final Collection<Representation> representations;

    public CompositeRepresentation(Collection<Representation> representations) {
        this.representations = representations;
    }

    @Override
    public String toStringOf(Object object) {
        for ( Representation representation : representations ) {
            String value = representation.toStringOf( object );
            if ( value != null ) {
                return value;
            }
        }

        return null;
    }

    @Override
    public String unambiguousToStringOf(Object object) {
        for ( Representation representation : representations ) {
            String value = representation.unambiguousToStringOf( object );
            if ( value != null ) {
                return value;
            }
        }

        return null;

    }
}
```

The javadoc of the `toStringOf` will need to be adapted saying that if the representation doesn't know how to provide `toStringOf` to return `null`.

This will then allow other libraries to provide a single `Representation` that would know how to handle their objects.

An additional thought can also be done for deprecating / removing `unambiguousToStringOf` and having the default implementation done in a different place. The javadoc of that method already says how the implementation should look like:

>Returns the `String` representation of the given object with its type and hexadecimal hash code so that it can be differentiated from other objects with the same `toStringOf(Object)` representation.

**Comment by joel-costigliola** [comment]
I like the idea of being able to register multiple representations, there should be a clear mechanism to decide which one to use if multiple representations can represent the same type, thinking out loud: custom representation of type would have priority over assertj ones, it's a bit trickier if multiple custom representations provide representation for the same types.

 @filiphr suggested implementation seems to be simpler ;-)

**Comment by filiphr** [comment]
>there should be a clear mechanism to decide which one to use if multiple representations can represent the same type, thinking out loud: custom representation of type would have priority over assertj ones, it's a bit trickier if multiple custom representations provide representation for the same types.

1. We can add `int getPriority` with a default implementation to `Representation` that way in case multiple implementations provide a representation they would need to handle it. I don't think that AssertJ should worry about that. AssertJ would order them once it loads them through the service loader.

2. We can always add the default representation from AssertJ in the end of the list. This would make sure that everything works smoothly. If a custom implementation wants to change something in the default one they only need to provide their own implementation that handles that.

**Comment by joel-costigliola** [comment]
I agree adding a priority should be good enough, there is always a risk of collision in the priority values but easy to address.

**Comment by Annette0127** [comment]
Hi! I wonder whether this issue is still open. If it is, I would like to work on this issue. 😊

**Comment by joel-costigliola** [comment]
thanks @Annette0127, go for it!
I think at the moment we can try @filiphr approach.

**Comment by kriegfrj** [comment]
Sorry I never circled back to comment on this issue...

I think the main difference between my original suggestion and @filiphr 's proposal is the backing structure - I was proposing a HashMap for O(1) lookup, and @filiphr is proposing a simple collection for O(n) lookup. Given that n is likely to be very small, I can't imagine a massive performance gain by using a hash, so I'm comfortable with @filiphr 's suggestion as being (probably) simpler to implement and maintain. But also, both proposals could work with the same API design for custom representations, so it would be easy to switch to a hash-based lookup in the future in the unlikely event that it was necessary to do so for performance.

**Comment by Annette0127** [comment]
Hi! I have considered a possible solution these days. I used `Map` to store different `Representations`. 
To start with, I am a beginner. I will be so pleased if you can give me some suggestions! 😊
First, I think the method `String unambiguousToStringOf(Object object)` from the ''org.assertj.core.presentation.Representation.java'' is no longer needed since I can implement various of `Representations` in the class `CompositeRepresentation`. (But I am not sure whether this method can be deleted.)

And according to the idea of [@filiphr](https://github.com/filiphr) and [@kriegfrj](https://github.com/kriegfrj), a new ideas formed. The code is generally showing below.

```java
public class CompositeRepresentation implements Representation{
  protected Map<String, Representation> representations;
  
/*Initialize the CompositeRepresentation according to a certain correspondence of the "name of representation" and "representation" itself.*/
  public CompositeRepresentation(Map<String, Representation> representations) {
    this.representations = representations;
  }
  
  /*Initialize the CompositeRepresentation when the user does not have the correspondence of the "name of representation" and "representation" itself yet.*/
  public CompositeRepresentation(){
    representations = new HashMap<>();
  }

  /*Implementation of the `toString` method.*/
  @Override
  public String toStringOf(Object object) {
    for (Map.Entry<String, Representation> entry : representations.entrySet()) {
      String value = entry.getValue().toStringOf(object);
      if (value != null)
        return value;
    }
    return STANDARD_REPRESENTATION.toStringOf(object);
  }

  /*Implementation of the `toString` method when user want to use a specific representation.*/
  public String toStringOf(Object object, String representationName) {
    if (representations.containsKey(representationName))
      return representations.get(representationName).toStringOf( object );
    return null;
  }

  /*Change the correspondence of the "name of representation" and "representation"*/
  public void setRepresentations(Map<String, Representation> representations) {
    this.representations = representations;
  }

  /*Get the "representation"*/
  public Map<String, Representation> getRepresentations(){
    return representations;
  }
  
  /*Add an entry of the correspondence of the "name of representation" and "representation"*/
  public boolean addRepresentation(String representationName, Representation representation){
    if (representations.containsKey(representationName))
      return false;
    representations.put(representationName,representation);
    return true;
  }
	
  /*Delete an entry of the correspondence of the "name of representation" and "representation"*/
  public boolean deleteRepresentation(String representationName){
    if (representations.containsKey(representationName)){
      representations.remove(representationName);
      return true;
    }
    return false;
  }
}

```

Thank you very much!😊

**Comment by joel-costigliola** [comment]
@Annette0127 can you raise a PR in draft mode? it's easier to provide feedback that way.
