### ISSUE TITLE
Add method cast() to get casted value after isInstanceOf()

### ISSUE THREAD

**Issue by ars-java** [assertj/assertj-core#2051]
#### Summary
It will be convenient to have a method that returns a casted object after `isInstanceOf` call.

For example:
```java
MyException e = assertThatThrownBy(() -> {
            // do smth
        }).isInstanceOf(MyException::class.java).cast()

assertThat(e.getCustomField())...
// Other checks
```

And it will be convenient to evaluate the following checks using already casted value.

For example:
```java
assertThatThrownBy(() -> {
            // do smth
        }).isInstanceOf(MyException::class.java)
.extracting(e -> {
    // I wanna use fields and methods from MyException here
})
```

or 
```java
assertThatThrownBy(() -> {
            // do smth
        }).isInstanceOf(MyException::class.java).cast()
.extracting(e -> {
    // I wanna use fields and methods from MyException here
})
```

**Comment by scordio** [comment]
[`asInstanceOf()`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractAssert.html#asInstanceOf(org.assertj.core.api.InstanceOfAssertFactory)) with [`InstanceOfAssertFactories.type()`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/InstanceOfAssertFactories.html#type(java.lang.Class)) is probably what you are looking for.

For example, having:

```java
class MyException extends RuntimeException {

  private final String field;
 
  MyException(String field) {
    this.field = field;
  }
 
  String getField() {
    return field;
  }
}
```

You could write:

```java
assertThatThrownBy(() -> { throw new MyException("some-value"); })
  .asInstanceOf(type(MyException.class))
  .extracting(MyException::getField)
  .isEqualTo("some-value");
```

Type-specific assertions are also possible with [`extracting()`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function,org.assertj.core.api.InstanceOfAssertFactory)) and [`as()`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/Assertions.html#as(org.assertj.core.api.InstanceOfAssertFactory)), e.g.:

```java
assertThatThrownBy(() -> { throw new MyException("some-value"); })
  .asInstanceOf(type(MyException.class))
  .extracting(MyException::getField, as(InstanceOfAssertFactories.STRING))
  .startsWith("some");
```

**Comment by joel-costigliola** [comment]
FYI if you use `extracting(String)` you can extract without casting:

```java
assertThatThrownBy(() -> { throw new MyException("some-value"); })
  .asInstanceOf(MyException.class)
  .extracting("field")
  .isEqualTo("some-value");
```

**Comment by scordio** [comment]
Hi @ars-java, do our answers help with your use case? Please let us know in case something is unclear.

**Comment by sukolenvo** [comment]
I would love `isInstanceOf(T)` to return `Assert<?, T>` instead of `Assert<?, ? extends Throwable>` since we already checked casting is safe.

Thanks for workarounds @scordio . But is there any real reason not to change return type? It would be very helpful if developers won't need to cast it manually and make code a little cleaner.

**Comment by scordio** [comment]
@sukolenvo `isInstanceOf` returns `SELF` to allow chaining additional assertions for the same type, that's probably where `Assert<?, ? extends Throwable>` is coming from, and it is not meant to change the current assertion instance. `asInstanceOf` would be the way to go for the latter.

Maybe I did not fully understand what you have in mind, could you provide a short example?

**Comment by sukolenvo** [comment]
Hi @scordio , `asInstanceOf` is exactly what I was looking for. Thank you for your help!
