### ISSUE TITLE
Consumer-based "satisfyExactly" assertions for elements in arrays and iterables

### ISSUE THREAD

**Issue by mgrafl** [assertj/assertj-core#2053]
#### Summary

Based on #1621, extend the assertions API for arrays and iterables with a `satisfyExactly` method accepting multiple  `Consumer<? super ELEMENT>`s. 
The tested collection must have the same size as the consumers. Each element of the tested collection is fed to the corresponding consumer.

The additional method would have the signature: 
```java
public final SELF satisfyExactly(Consumer<? super ELEMENT>... consumers)
```

Additionally, the method would be overloaded with an assert factory as first parameter and consumers operating not on the collection ELEMENT but on an assertion over that element (as suggested by @jbytecoder):
```java
public final <A extends AbstractAssert<?, ELEMENT>> 
SELF satisfyExactly(Function<ELEMENT, A> assertFactory, Consumer<? super A>... consumers)
```

#### Example

```java
assertThat(trilogy).satisfyExactly(movie -> {
    // the fellowship of the Ring
    assertThat(movie.getReleaseDate()).isBefore(parse("2002-12-17"));
    assertThat(movie.xrated).isFalse();
  }, 
  movie -> {
    // the two Towers
     assertThat(movie.getReleaseDate()).isEqualTo(parse("2002-12-18"));
     assertThat(movie.getTitle()).contains("Towers");
  }, 
  movie -> {
    // the Return of the King
    assertThat(movie.getTitle()).endsWith("King");
  }
);

assertThat(movieTitles).satisfyExactly(
  Assertions::assertThat,
  s -> s.contains("fellowship"), 
  s -> s.endsWith("Towers"), 
  s -> s.matches(".* Return .* King")
);
```

This issue (and #2054) was split from #1621 as suggested by @joel-costigliola in https://github.com/assertj/assertj-core/issues/1621#issuecomment-539696963

**Comment by joel-costigliola** [comment]
I'm ok with `SELF satisfyExactly(Consumer<? super ELEMENT>... consumers)` it's behaviour is natural/obvious but the other with an assert factory is not so obvious and can be done with the former.

**Comment by mgrafl** [comment]
@joel-costigliola, thanks for the feedback, fine for me. So I assume it's acceptable that the first parameter might become ambiguous (in some edge cases, detailed in https://github.com/assertj/assertj-core/issues/1621#issuecomment-734410494) when the second method variant is introduced in a later release.

**Comment by joel-costigliola** [comment]
minor: I'll name the assertion `satisfiesExactly` for the sake of English grammar.
