### ISSUE TITLE
Consumer-based "satisfyExactlyInAnyOrder" assertions for elements in arrays and iterables

### ISSUE THREAD

**Issue by mgrafl** [assertj/assertj-core#2054]
#### Summary

Based on #1621, extend the assertions API for arrays and iterables with a `satisfyExactlyInAnyOrder` method accepting multiple  `Consumer<? super ELEMENT>`s. 
The tested collection must have the same size as the consumers. For each element of the tested collection the (remaining) consumers are called; if a consumer accepts the element, then the element and that consumer are removed from their collections and the next element is probed.

The additional method would have the signature: 
```java
public final SELF satisfyExactlyInAnyOrder(Consumer<? super ELEMENT>... consumers)
```

Additionally, the method would be overloaded with an assert factory as first parameter and consumers operating not on the collection ELEMENT but on an assertion over that element (as suggested by @jbytecoder):
```java
public final <A extends AbstractAssert<?, ELEMENT>> 
SELF satisfyExactlyInAnyOrder(Function<ELEMENT, A> assertFactory, Consumer<? super A>... consumers)
```

Note: the implementation from #1892 (originally for the `satisfy` method, aka. `containsElementsSatisfyingExactlyInAnyOrder`, still pending agreement on clear naming) already performs all necessary logic. It could be combined with a simple length verification.

#### Example

```java
assertThat(trilogy).satisfyExactlyInAnyOrder(movie -> {
    // the fellowship of the Ring
    assertThat(movie.getReleaseDate()).isBefore(parse("2002-12-17"));
    assertThat(movie.xrated).isFalse();
  }, 
  movie -> {
    // the Return of the King
    assertThat(movie.getTitle()).endsWith("King");
  },
  movie -> {
    // the two Towers
     assertThat(movie.getReleaseDate()).isEqualTo(parse("2002-12-18"));
     assertThat(movie.getTitle()).contains("Towers");
  } 
);

assertThat(movieTitles).satisfyExactlyInAnyOrder(
  Assertions::assertThat,
  s -> s.matches(".* Return .* King"),
  s -> s.endsWith("Towers"), 
  s -> s.contains("fellowship")
);
```

This issue (and #2053) was split from #1621 as suggested by @joel-costigliola in https://github.com/assertj/assertj-core/issues/1621#issuecomment-539696963

**Comment by joel-costigliola** [comment]
Same comment as for `satisfyExactly`, happy with `SELF satisfyExactlyInAnyOrder(Consumer<? super ELEMENT>... consumers)` but feel that the variant with `Function<ELEMENT, A> assertFactory` is not necessary (you could achieve the same by calling `extracting/map` before.
