### ISSUE TITLE
StringAssert: Add method to assert equality of normalized strings 

### ISSUE THREAD

**Issue by sniffertine** [assertj/assertj-core#2057]
#### Summary
Some Strings look equal but their canonical form is not equal. For example one can compose the A umlaut (Ä) with a single character: \u00C4 Or with a combination of the A character and the dots (the dieresis character ¨): \u0041\u0308

In essence, you are using two unicode characters for one letter. Because equals() compares characters, the form with dieresis is not equals to the form without.

The problem is explained here: https://stackoverflow.com/questions/27670249/string-comparison-is-wrong/27670613#27670613

#### Example

```java
assertThat("\u00C4").isEqualToNormalizingUnicode("\u0041\u0308")
```

**Comment by joel-costigliola** [comment]
Fair enough, @sniffertine keen to contribute it?

**Comment by devjuliet** [comment]
@joel-costigliola Is this up for grabs? I would like to contribute 😄

**Comment by joel-costigliola** [comment]
It is @devjuliet, thanks for contributing! don't hesitate to ask if you are not sure how to tackle it.
