### ISSUE TITLE
Support Hibernate lists (ie: PersistentBag)

### ISSUE THREAD

**Issue by juherr** [assertj/assertj-core#2058]
#### Summary
Hibernate doesn't respect the equals/hashCode convention for its internal list (see https://hibernate.atlassian.net/browse/HHH-5409).

When tests are made on services, the returned lists may be the Hibernate ones.

AssertJ could detect Hibernate lists and make a deep assertion (like it does with arrays) instead of using the standard `List.equals`.

```kotlin
// Assertion is working if result1/2 are standard lists and failing if they are Hibernate lists
assertThat(result1).isEqualTo(result2)

// Workarround
assertThat(result1.toList()).isEqualTo(result2.toList())
```

**Comment by joel-costigliola** [comment]
The issue here is that assertj-core does not depend on anything explicitly, what you can do instead is use `containsExactly` which checks each pair of elements in order.

**Comment by filiphr** [comment]
To add to what @joel-costigliola said

You can actually use `containsExactlyElementsOf` for your use case

e.g.

```
assertThat(result1).containsExactlyElementsOf(result2)
```

**Comment by juherr** [comment]
@joel-costigliola 
> The issue here is that assertj-core does not depend on anything explicitly

Sure! But does exist an SPI, or a similar way, for custom extensions that could make the bridge between assertj and 3rd parties?

@filiphr 
Thanks! `containsExactlyElementsOf` is what I was looking for!

**Comment by scordio** [comment]
> But does exist an SPI, or a similar way, for custom extensions that could make the bridge between assertj and 3rd parties?

An option might be to implement a custom assertion for the Hibernate type, see: https://assertj.github.io/doc/#assertj-core-custom-assertions

**Comment by joel-costigliola** [comment]
Another option is to use the recursive comparison should the elements contain another list.
