### ISSUE TITLE
Add ability to use String Supplier when setting the assertion description.

### ISSUE THREAD

**Issue by tkvangorder** [assertj/assertj-core#2061]
#### Summary

I am working on a [project that will migrate JUnit 5 style assertions to AssertJ's assertion library.](https://github.com/openrewrite/rewrite-testing-frameworks/issues/8) 

One issue I have run into is that JUnit 5 has a variant of their assertion methods that accept a Supplier<String> to lazily instantiate the message: 

```
assertEquals("joe", "fred", () -> "These names should be the same");
```
Ideally, I would like to convert this to: 

```
assertThat("fred").as(() -> "These names should be the same").isEqualTo("joe");
```

There is no obvious, generic way to convert the supplier into a Description. We envision many projects using our "recipe" to perform this migration and it would be helpful if there was an overloaded `as` method within the core assertJ library. 

Right now, I am using .`withFailMessage` which already has an overload that accepts a supplier but, of course, this will 
completely override the message.

I think it would be as easy as adding something like the following:

```java
	public SELF as(final Supplier<String> messageSupplier) {
		super.as(
			new Description() {
			
			@Override
			public String value() {
				return messageSupplier.get();
			}
		});
	}
```

Thanks

**Comment by joel-costigliola** [comment]
Fair enough!
