### ISSUE TITLE
Make .isEqualToNormalizingXxx failures easier to analyze.

### ISSUE THREAD

**Issue by EtienneMiret** [assertj/assertj-core#2062]
#### Summary

IntelliJ IDEA (and most likely other IDEs) have a nice support for `org.junit.ComparisonFailure`, where it process the exception and generate a nice report with the diff, which I find very useful when comparing large objects. `isEqualTo ()` will already throw this error. I believe all `isEqualToNormalizingXxxx` methods should do the same instead of  throwing a raw `AssertionError`.

#### Example

Compare the result of the below (failling) tests in IntelliJ:

```java
public class AssertionFailureTest {

  @Test
  public void isEqualTo () {
    String expected = IntStream.range (0, 200)
      .mapToObj (String::valueOf)
      .collect (Collectors.joining ("\n"));
    String actual = IntStream.range (0, 200)
      .filter (i -> i != 42)
      .mapToObj (String::valueOf)
      .collect(Collectors.joining ("\n"));

    assertThat (actual).isEqualTo (expected);
  }

  @Test
  public void isEqualToNormalizingXxxx () {
    String expected = IntStream.range (0, 200)
      .mapToObj (String::valueOf)
      .collect (Collectors.joining ("\n"));
    String actual = IntStream.range (0, 200)
      .filter (i -> i != 42)
      .mapToObj (String::valueOf)
      .collect(Collectors.joining ("\n"));

    assertThat (actual).isEqualToNormalizingNewlines (expected);
  }

}
```

#### NB

The goal of this issue is to make it easy to find the issue in case an assertion fails. Throwing a ComparisonFailure seems me to be an easy way to do that, but feel free to suggest any other way.

**Comment by joel-costigliola** [comment]
Fine by me.
