### ISSUE TITLE
Unwanted Warning in tests for assertion on AtomicBoolean 

### ISSUE THREAD

**Issue by bmaggi** [assertj/assertj-core#2065]
#### Summary
Intellij indicate a warning when using assertj with AtomicBoolean whereas the test seems correct.

Assertions are working fine, the problem is on the unwanted warning. 
Text of the warning : "According to inferred contract, method 'assertThat' throws exception when parameter != true" 

#### Example

```java
import org.junit.jupiter.api.Test;

import java.util.concurrent.atomic.AtomicBoolean;

import static org.assertj.core.api.Assertions.assertThat;

class MyExampleTest {

    @Test
    void myTestSuccess() {
        AtomicBoolean executed = new AtomicBoolean(false);
        executed.set(true);
        assertThat(executed).isTrue(); // WARNING here but the test is Sucessfull
    }

    @Test
    void myTestFail() {
        AtomicBoolean executed = new AtomicBoolean(false);
        executed.set(true);
        assertThat(executed).isFalse(); // no warning here but the test is failing
    }
}
```

Using 

```xml
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>5.7.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.18.1</version>
            <scope>test</scope>
        </dependency>
```

**Comment by joel-costigliola** [comment]
@bmaggi  I think it's an issue in Intellij Idea or the tool that is reporting the warning, it's probably better to raise an issue in Intellij Idea tracker if you want it to be fixed.
I don't have such warning in Eclipse.

**Comment by bmaggi** [comment]
Coincidence ? Someone just opened a similar issue 3 days ago
https://youtrack.jetbrains.com/issue/IDEA-257165

Warning is displayed by intellij but based on code and annotation, so my guess was that something in code or annotation is misconfigured.

=> I close the ticket and link this issue in the Intellij's one.
