### ISSUE TITLE
Assertion fails on 3.18+

### ISSUE THREAD

**Issue by javydreamercsw** [assertj/assertj-core#2066]
#### Summary
Existing assertion working on 3.17.2 fails on 3.18+ releases.

#### Example

```java
assertThatJson(user)
          .withFailMessage("Failure message.")
          .isObject()
          .containsKey("lastSignOn")
          .extracting("lastSignOn")
          .hasFieldOrProperty("at")
          .hasFieldOrProperty("remoteIp")
          .hasNoNullFieldsOrPropertiesExcept();
```

The string being analyzed (some values masked for security reasons):
```
{
  "identityProvider" : {
    "type" : "***"
  },
  "createdAt" : "2020-12-08T16:21:09.395Z",
  "enabled" : true,
  "lastSignOn" : {
    "at" : "2020-12-08T16:21:25.220Z",
    "remoteIp" : "***"
  },
  "lifecycle" : {
    "status" : "ACCOUNT_OK"
  },
  "mfaEnabled" : false,
  "population" : {
    "id" : "25627d7c-7864-4469-b2a1-8276c84a44b1"
  },
  "updatedAt" : "2020-12-08T16:21:25.386Z",
  "username" : "****_1607444456807"
}
```

Error:
```
Failures:
implicitLogin>AssertionError: java.lang.AssertionError: [Different value found in node ""] 
Expecting
  <{"at":"2020-12-08T16:21:25.220Z","remoteIp":"***"}>
to have a property or a field named <["entrySet", "values"]>.
```

**Comment by javydreamercsw** [comment]
Test on both 3.18.0 and 3.18.1 with the same results.

**Comment by joel-costigliola** [comment]
Thanks, we'll look at it shortly

**Comment by joel-costigliola** [comment]
This is due to a [breaking change in 3.18.0](https://assertj.github.io/doc/#assertj-core-3-18-0-release-notes) where bare name properties are not found by default (for example `entrySet()` for the `entrySet` field as opposed to `getEntrySet()`).
Call `Assertions.setExtractBareNamePropertyMethods(true);` to enable them, the test succeeds with this.

**Comment by javydreamercsw** [comment]
That did the trick!

**Comment by javydreamercsw** [comment]
Sadly after revisiting this, although it fixes the issue above it breaks checks like this:

`assertThatJson(transaction).isObject().hasNoNullFieldsOrProperties();`

**Comment by javydreamercsw** [comment]
Works fine, nvm
