### ISSUE TITLE
Too much stack trace removed for failure in a utility method

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#2067]
#### Summary

I am using soft assertions with a custom soft assertions provider (though I'm not sure if the custom provider is a relevant point). I had an `AssertJMultipleFailuresError` that only contained one error. Unfortunately, the stack trace for the code where the original assertion failed seems to have been removed.

The problem seems to be that the soft assertion is thrown in a utility method within the same class, and not the original test method. This is possibly confusing the code that attempts to tidy-up the stack trace (which I believe has been altered recently).

#### Example

```
org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
[result] 
Expecting:
 <"@OK@ Transaction message #1722379596: [field name]: this is a description: this is a much longer description">
to contain:
 <"0"> 
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

Clearly, the assertion was not raised in the JDK code! The code that caused the above looked something like this:

```java
@InjectSoftAssertions 
SoftAssertions softly;

@Test 
void topLevelTest1() {
  // Do configuration specific to "topLevelTest1()" here

  // Run the common code along with the common sanity checks
  String result  = doCommonStuff();

  // Do assertions specific to "topLevelTest1()" here
  softly.assertThat(result).contains("topLevelTest1 message");
}

@Test 
String doCommonStuff() {
  String result;
  // Do common tasks here (eg, make the web request)

  // Now do common assertions - this is the one that fails
  softly.assertThat(result).as("result").contains("@OK@");
}
```

As noted in the comment in my pseudo-code, it is that soft assertion in `doCommonStuff()` that actually failed. Yet all... errm... "trace" of it (pun intended) has been removed from the stack trace in the reported soft assertion failure.

This is a bit of an inconvenience - I miss being able to click on the stack trace and get taken straight to the line in the code where the failure happened. I also think (but I'm not 100% sure) that this is a regression - this problem didn't always used to happen (I'm sure I would have noticed it before now if that were the case). I think I remember first seeing it in 3.18.1.

**Comment by kriegfrj** [comment]
Actually, another detail that may (or may not) be important: the utility method `doCommonStuff()` is actually in a superclass.

**Comment by joel-costigliola** [comment]
Hi @kriegfrj,
Stack trace pertaining to assertj is filtered out by default, you can disable that with `Assertions.setRemoveAssertJRelatedElementsFromStackTrace(false)`.

The code is like:

```java
  private void removeCustomAssertRelatedElementsFromStackTraceIfNeeded(AssertionError assertionError) {
    if (!Failures.instance().isRemoveAssertJRelatedElementsFromStackTrace()) return;
    if (isAssertjAssertClass()) return;

    StackTraceElement[] newStackTrace = Arrays.stream(assertionError.getStackTrace())
                                              .filter(element -> !isElementOfCustomAssert(element))
                                              .toArray(StackTraceElement[]::new);
    assertionError.setStackTrace(newStackTrace);
  }

  private boolean isAssertjAssertClass() {
    return getClass().getName().startsWith(ORG_ASSERTJ);
  }

  protected boolean isElementOfCustomAssert(StackTraceElement stackTraceElement) {
    Class<?> currentAssertClass = getClass();
    while (currentAssertClass != AbstractAssert.class) {
      if (stackTraceElement.getClassName().equals(currentAssertClass.getName())) return true;
      currentAssertClass = currentAssertClass.getSuperclass();
    }
    return false;
  }
```

You can  override `isElementOfCustomAssert(StackTraceElement stackTraceElement)` in your custom assertions to tweak what is going to be removed.

The filtering might be too aggressive but hard to say without a reproducible case.

**Comment by kriegfrj** [comment]
Just to clarify... it was a custom provider, but it was a StringAssert not a custom assert. 

I think the key point is it being thrown in a subclass of the test class. I'll try and come b up with a concrete test case for it.

**Comment by kriegfrj** [comment]
Interestingly, I had a bit of a look at this today, and I can see that the test case for `AssertJMultipleFailuresError` is not expecting any stack traces in the individual failure messages:

https://github.com/assertj/assertj-core/blob/d20f3d381960a5ad504e7be9c44e16464cd64b51/src/test/java/org/assertj/core/error/AssertJMultipleFailuresError_getMessage_Test.java#L53-L109

Can you point me in the right direction here @joel-costigliola ? Is this by design? I thought I had seen the stack trace errors (or at least the first line) in the past. Maybe that was back when it was using the plain OpenTest4J `MultipleFailuresError`?

**Comment by joel-costigliola** [comment]
I remember now that we did not include the stack traces for the sake of brevity but that's the same behaviour as opentest4j `MultipleFailuresError` as far as I can see.

**Comment by kriegfrj** [comment]
I must be going insane (some might argue that this is not a recent development...).

Actually, we don't need the full stack trace - the top few lines (after AssertJ has removed its contribution) for each failure would be fine. That would do the job but without making it too verbose. (As noted, i thought i saw oit doing this in the past but i must have been mistaken. )

I have another more radical idea i might try though...

**Comment by joel-costigliola** [comment]
We can add the top filtered lines, like 5 per failure?

**Comment by kriegfrj** [comment]
The top 5 lines might even be too much. I was thinking top 2 or 3.

Ideally, it would be able to find the stack trace line that identifies the entry into the top-level test method, and ignore everything after that. That way it could automatically adapt to the pattern I use of utility assertion methods (which occasionally go through a few layers of indirection) but not include more than is necessary. But I'm not sure how feasible this is.

**Comment by joel-costigliola** [comment]
finding the top level test method is going to be brittle as it depends on the test name itself (can't really infer that) and possibly the test engine. 
let's keep it simple to 3 stack trace elements for now.

**Comment by perlun** [comment]
@joel-costigliola Was this ever implemented?

**Comment by joel-costigliola** [comment]
not yet, it has fallen under our radar I'm afraid, I'll schedule it for the next release.

**Comment by joel-costigliola** [comment]
playing with a possible implementation displaying 5 stack trace elements, given this test

```java
@Test
void test4() {
  setRemoveAssertJRelatedElementsFromStackTrace(true);
  then(list("aaa")).singleElement()
                   .satisfies(value -> then(value).startsWith("b"),  // line 36
                              value -> then(value).endsWith("z")); // line 37
}
```

the error message reports the proper line for the failing assertions:
```
org.assertj.core.error.AssertJMultipleFailuresError: 
[List check single element] (2 failures)
-- failure 1 --
Expecting actual:
  "aaa"
to start with:
  "b"
  at starwars.test.MyTest.lambda$2(MyTest.java:36)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
-- end of failure 1 --

-- failure 2 --
Expecting actual:
  "aaa"
to end with:
  "z"
  at starwars.test.MyTest.lambda$3(MyTest.java:37)
  at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
-- end of failure 2 --

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at starwars.test.MyTest.test4(MyTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
