### ISSUE TITLE
AssertJ Core quality reports website can’t open

### ISSUE THREAD

**Issue by xiaozhiliaoo** [assertj/assertj-core#2072]
#### Summary
AssertJ Core quality reports website can not open. http://nemo.sonarqube.org/dashboard/index/528057

**Comment by scordio** [comment]
Hi @xiaozhiliaoo, the report is available at https://sonarcloud.io/dashboard?id=joel-costigliola_assertj-core. From where did you take the other link?

**Comment by xiaozhiliaoo** [comment]
I get the link from this page: https://joel-costigliola.github.io/assertj/assertj-core.html . At Last line:Thanks to SonarQube for providing AssertJ Core quality reports.

**Comment by scordio** [comment]
Thanks @xiaozhiliaoo, then it comes from the legacy documentation. I'll close this issue.

The new documentation is available on https://assertj.github.io/doc/. However, the SonarQube report can be reached from the badge on the repository home page.

**Comment by xiaozhiliaoo** [comment]
@scordio  Thanks a lot!
