### ISSUE TITLE
Pass matcher as argument in softly.assertThat

### ISSUE THREAD

**Issue by CharlelieBouvier** [assertj/assertj-core#2082]
#### Summary
I have a list of elements and a list of matchers to apply to the first one.
I'd like to assert all the items and get all failures if there are any.

But sotfly.assertThat do not accept matcher as an argument

#### Example

```java
    protected void checkAllForPack(final Document document, final Map<Integer, Map<Integer, FieldData>> columnMap, final Integer pack) {
        final Map<Integer, FieldData> keyData = columnMap.get(pack);
        final Element rootElement = findElementByPackId(document, pack);
        for (Integer key : keyData.keySet()) {
            final Element element = rootElement.getElementById(key.toString());
            final FieldData fieldData = keyData.get(key);
            if (element == null) {
                assertTrue(fieldData.matcher instanceof org.hamcrest.core.IsNull, buildFieldMessage(pack, key, fieldData.label) + " is missing");
            } else {
                // Cannot use soflty here....
                assertThat(buildFieldMessage(pack, key, fieldData.label), element.attr("value"), fieldData.matcher);
            }
        }
    }
```

**Comment by joel-costigliola** [comment]
I don't fully understand what you are trying to do, a reproducible example would help here.

You can use Hamcrest matcher with [`HamcrestCondition`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/HamcrestCondition.html).
If you want to combine some pair of elements and perform some assertions for each pair, I would give a try to [`zipSatisfy`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#zipSatisfy(java.lang.Iterable,java.util.function.BiConsumer)) and zip your elements and your matcher that would wrapped as `HamcrestCondition`.

**Comment by CharlelieBouvier** [comment]
Thank you this did the trick 👍 

`assertThat("abc").is(matching(myMatcher));`
