### ISSUE TITLE
Consider idioms for empty satification

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2085]
#### Summary

Sometimes there are situations that we don't have to verify at all.

Say, a testcase verifies a overridden `hashCode()` method.

One can just call it and implicitly verifies nothing's thrown.
```java
@Test void testHashCode() {
    final int hashCode = new MyObject().hashCode();
}
```
Or explicitly,
```java
@Test void testHashCode() {
    // a little bit verbose...
    Assertions
            .assertThatCode(() -> {
                final int hashCode = new MyObject().hashCode();
            })
            .doesNotThrowAnyException();
}
```
One can just verifies for an empty consumer.
```java
@Test void testHashCode() {
    Assertions.assertThat(new MyObject().hashCode()).satifies(v -> {
        // empty
    });
}
```

#### Example
Is it more expressive when we can do this?
```java
@Test
void testHashCode() {
    Assertions.assertThat(new MyObject().hashCode()).satisfiesByItself(); // terminal
}
```

**Comment by joel-costigliola** [comment]
An existing alternative is:
```java
assertThatNoException().isThrownBy(() -> new MyObject().hashCode());
```
I find it good enough (as `doesNotThrowAnyException` btw).

The suggested approach does not really work as you can't capture any potential exceptions thrown by `hashCode()` in:
```java
assertThat(new MyObject().hashCode()).satisfiesByItself();
```
the reason being `hashCode()` is called before `assertThat` is thus there is no way for AssertJ to do anything here.

**Comment by onacit** [comment]
@joel-costigliola Thanks for your kind comments.
