### ISSUE TITLE
Misleading reference to newLinkedHashMap in Javadoc

### ISSUE THREAD

**Issue by LorenzoBettini** [assertj/assertj-core#2090]
#### Summary

The Javadoc of `AbstractMapAssert` mentions in the examples the methods `entry` and `newLinkedHashMap`. While `entry` is actually part of the class `Assertions`, `newLinkedHashMap` is not found anywhere. Actually, it's a private method of `Maps_assertContainsExactly_Test`, and I guess the examples in the Javadoc were copied from there.

AssertJ actually provides something similar, `org.assertj.core.util.Maps.newHashMap(K, V)`, but it only takes a key and a value.

Do you think it would be possible to have `newLinkedHashMap` (or something similar, I think there's a `mapOp` somewhere else in a few tests?) to which we can pass results of `entry` in the `Assertions` so that maps for assertions can be easily built? Or at least do you think it would be better to update Javadoc? Indeed, I found the Javadoc confusing in that respect and I tried to find newLinkedHashMap somewhere with no success.

**Comment by joel-costigliola** [comment]
We will clarify the javadoc but we won't add or expose `newLinkedHashMap`/`mapOf` as it's not the AssertJ's job to provide map factory methods (exposing `entry` is different in the sense it is used in some assertions parameter). 
If you need one I suggest to use guava [`ImmutableMap.of`](https://guava.dev/releases/30.1-jre/api/docs/com/google/common/collect/ImmutableMap.html#of(K,V))

**Comment by LorenzoBettini** [comment]
Thanks! From Java 9 also Map.of (https://docs.oracle.com/javase/9/docs/api/java/util/Map.html#of-K-V-) will be enough
