### ISSUE TITLE
Remove <> from error messages

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2091]
#### Summary

Error messages use `<>` to delimit a displayed value, this was made to disambiguate empty/blank value.
The issue is that it makes error messages harder to read most of the time, thus removing it will be an improvement.

If it's not already the case, indent with 2 spaces before displaying values on new lines.

#### Example

With `<>` and 1 space identation
```
[Test] 
Expecting:
 <8>
to be less than:
 <6> 
```

Without `<>` and 2 space indentation
```
[Test] 
Expecting:
  8
to be less than:
  6 
```

#### Scope

This affects the majority of error messages, so if you want to contribute to this just take one (unchecked) error message from the list below and raise a PR:

- [x] AnyElementShouldMatch
- [x] ClassModifierShouldBe
- [x] ConditionAndGroupGenericParameterTypeShouldBeTheSame
- [x] ElementsShouldBeAtLeast
- [x] ElementsShouldBeAtMost
- [x] ElementsShouldBeExactly
- [x] ElementsShouldBe
- [x] ElementsShouldHaveAtLeast
- [x] ElementsShouldHaveAtMost
- [x] ElementsShouldHaveExactly
- [x] ElementsShouldHave
- [x] ElementsShouldMatch
- [x] ElementsShouldNotBe
- [x] ElementsShouldNotHave
- [x] ElementsShouldSatisfy
- [x] NoElementsShouldMatch
- [x] NoElementsShouldSatisfy
- [x] OptionalDoubleShouldHaveValueCloseToOffset
- [x] OptionalDoubleShouldHaveValueCloseToPercentage
- [x] OptionalShouldBeEmpty
- [x] OptionalShouldContainInstanceOf
- [x] OptionalShouldContain
- [x] ShouldAccept
- [x] ShouldBeAbsolutePath
- [x] ShouldBeAbstract
- [x] ShouldBeAfter
- [x] ShouldBeAfterOrEqualTo
- [x] ShouldBeAfterYear
- [x] ShouldBeAnArray
- [x] ShouldBeAnnotation
- [x] ShouldBeAssignableFrom
- [x] ShouldBeAtIndex
- [x] ShouldBeAtSameInstant
- [x] ShouldBeBase64
- [x] ShouldBeBefore
- [x] ShouldBeBeforeOrEqualTo
- [x] ShouldBeBeforeYear
- [x] ShouldBeBetween
- [x] ShouldBeBlank
- [x] ShouldBeCanonicalPath
- [x] ShouldBeCloseTo
- [x] ShouldBeDirectory
- [x] ShouldBeEmptyDirectory
- [x] ShouldBeEmpty
- [x] ShouldBeEqualByComparingFieldByFieldRecursively
- [x] ShouldBeEqualByComparingOnlyGivenFields
- [x] ShouldBeEqualIgnoringHours
- [x] ShouldBeEqualIgnoringMinutes
- [x] ShouldBeEqualIgnoringNanos
- [x] ShouldBeEqualIgnoringNewLineDifferences
- [x] ShouldBeEqualIgnoringNewLines
- [x] ShouldBeEqualIgnoringSeconds
- [x] ShouldBeEqualIgnoringTimezone
- [x] ShouldBeEqualIgnoringWhitespace
- [x] ShouldBeEqualNormalizingPunctuationAndWhitespace
- [x] ShouldBeEqualNormalizingWhitespace
- [x] ShouldBeEqualToIgnoringFields
- [x] ShouldBeEqualWithinOffset
- [x] ShouldBeEqualWithinPercentage
- [x] ShouldBeEqualWithTimePrecision
- [x] ShouldBeEven
- [x] ShouldBeExactlyInstanceOf
- [x] ShouldBeExecutable
- [x] ShouldBeFile
- [x] ShouldBeFinite
- [x] ShouldBeGreater
- [x] ShouldBeGreaterOrEqual
- [x] ShouldBeInfinite
- [x] ShouldBeIn
- [x] ShouldBeInSameDay
- [x] ShouldBeInSameHour
- [x] ShouldBeInSameHourWindow
- [x] ShouldBeInSameMinute
- [x] ShouldBeInSameMinuteWindow
- [x] ShouldBeInSameMonth
- [x] ShouldBeInSameSecond
- [x] ShouldBeInSameSecondWindow
- [x] ShouldBeInSameYear
- [x] ShouldBeInstance
- [x] ShouldBeInstanceOfAny
- [x] ShouldBeInterface
- [x] ShouldBeInTheFuture
- [x] ShouldBeInThePast
- [x] ShouldBe
- [x] ShouldBeLess
- [x] ShouldBeLessOrEqual
- [x] ShouldBeLowerCase
- [x] ShouldBeMarked
- [x] ShouldBeNormalized
- [x] ShouldBeNullOrEmpty
- [x] ShouldBeOdd
- [x] ShouldBeOfClassIn
- [x] ShouldBePeriod
- [x] ShouldBeReadable
- [x] ShouldBeRegularFile
- [x] ShouldBeRelativePath
- [x] ShouldBeSame
- [x] ShouldBeSorted
- [x] ShouldBeSubsetOf
- [x] ShouldBeSubstring
- [x] ShouldBeSymbolicLink
- [x] ShouldBeToday
- [x] ShouldBeUpperCase
- [x] ShouldBeWritable
- [x] ShouldContainAnyOf
- [x] ShouldContainAtIndex
- [x] ShouldContainCharSequence
- [x] ShouldContainCharSequenceOnlyOnce
- [x] ShouldContainEntry
- [x] ShouldContainExactlyInAnyOrder
- [x] ShouldContainExactly
- [x] ShouldContain
- [x] ShouldContainKey
- [x] ShouldContainKeys
- [x] ShouldContainNull
- [x] ShouldContainOneOrMoreWhitespaces
- [x] ShouldContainOnlyDigits
- [x] ShouldContainOnly
- [x] ShouldContainOnlyKeys
- [x] ShouldContainOnlyNulls
- [x] ShouldContainOnlyWhitespaces
- [x] ShouldContainRecursively
- [x] ShouldContainSequence
- [x] ShouldContainSequenceOfCharSequence
- [x] ShouldContainsOnlyOnce
- [x] ShouldContainSubsequence
- [x] ShouldContainSubsequenceOfCharSequence
- [x] ShouldContainValue
- [x] ShouldContainValues
- [x] ShouldEndWith
- [x] ShouldEndWithPath
- [x] ShouldExist
- [x] ShouldHaveAllNullFields
- [x] ShouldHaveAnnotations
- [x] ShouldHaveAtIndex
- [x] ShouldHaveAtLeastOneElementOfType
- [x] ShouldHaveBinaryContent
- [x] ShouldHaveCauseExactlyInstance
- [x] ShouldHaveCauseInstance
- [x] ShouldHaveCause
- [x] ShouldHaveContent
- [x] ShouldHaveDateField
- [x] ShouldHaveDigest
- [x] ShouldHaveDimensions
- [x] ShouldHaveDuration
- [x] ShouldHaveExtension
- [x] ShouldHaveFields
- [x] ShouldHave
- [x] ShouldHaveLineCount
- [x] ShouldHaveMessageFindingMatchRegex
- [x] ShouldHaveMessage
- [x] ShouldHaveMessageMatchingRegex
- [x] ShouldHaveMethods
- [x] ShouldHaveName
- [x] ShouldHaveNoCause
- [x] ShouldHaveNoFields
- [x] ShouldHaveNoNullFields
- [x] ShouldHaveNoParent
- [x] ShouldHaveNoSuperclass
- [x] ShouldHaveOnlyElementsOfType
- [x] ShouldHavePackage
- [x] ShouldHaveParent
- [x] ShouldHavePeriod
- [x] ShouldHavePropertyOrField
- [x] ShouldHavePropertyOrFieldWithValue
- [x] ShouldHaveReference
- [x] ShouldHaveRootCauseExactlyInstance
- [x] ShouldHaveRootCauseInstance
- [x] ShouldHaveRootCause
- [x] ShouldHaveSameClass
- [x] ShouldHaveSameContent
- [x] ShouldHaveSameHashCode
- [x] ShouldHaveSameHourAs
- [x] ShouldHaveSameSizeAs
- [x] ShouldHaveSameTime
- [x] ShouldHaveSizeBetween
- [x] ShouldHaveSize
- [x] ShouldHaveStamp
- [x] ShouldHaveSuperclass
- [x] ShouldHaveTime
- [x] ShouldHaveToString
- [x] ShouldHaveValue
- [x] ShouldMatch
- [x] ShouldNotAccept
- [x] ShouldNotBeBetween
- [x] ShouldNotBeBlank
- [x] ShouldNotBeEmpty
- [x] ShouldNotBeEqualComparingFieldByFieldRecursively
- [x] ShouldNotBeEqualIgnoringCase
- [x] ShouldNotBeEqualIgnoringWhitespace
- [x] ShouldNotBeEqual
- [x] ShouldNotBeEqualNormalizingWhitespace
- [x] ShouldNotBeEqualWithinOffset
- [x] ShouldNotBeEqualWithinPercentage
- [x] ShouldNotBeExactlyInstanceOf
- [x] ShouldNotBeIn
- [x] ShouldNotBeInstance
- [x] ShouldNotBeInstanceOfAny
- [x] ShouldNotBe
- [x] ShouldNotBeOfClassIn
- [x] ShouldNotBeSame
- [x] ShouldNotContainAnyWhitespaces
- [x] ShouldNotContainAtIndex
- [x] ShouldNotContainCharSequence
- [x] ShouldNotContain
- [x] ShouldNotContainKey
- [x] ShouldNotContainKeys
- [x] ShouldNotContainNull
- [x] ShouldNotContainOnlyWhitespaces
- [x] ShouldNotContainSequence
- [x] ShouldNotContainSubsequence
- [x] ShouldNotContainValue
- [x] ShouldNotEndWith
- [x] ShouldNotExist
- [x] ShouldNotHaveAnyElementsOfTypes
- [x] ShouldNotHaveDuplicates
- [x] ShouldNotHave
- [x] ShouldNotHaveSameClass
- [x] ShouldNotHaveSameHashCode
- [x] ShouldNotHaveThrown
- [x] ShouldNotHaveToString
- [x] ShouldNotMatch
- [x] ShouldNotStartWith
- [x] ShouldOnlyHaveElementsOfTypes
- [x] ShouldOnlyHaveFields
- [x] ShouldSatisfy
- [x] ShouldStartWith
- [x] ShouldStartWithPath
- [x] ZippedElementsShouldSatisfy

**Comment by himadri-mandal** [comment]
@epeee You can assign this to me, I am new to the community and like to contribute to it.

**Comment by epeee** [comment]
@himadri-mandal I'd vote for leaving it unassigned for now (since there are still quite some messages to migrate).

**Comment by scordio** [comment]
@himadri-mandal just let us know which ones you are picking up so we don't step on each other 🙂

**Comment by himadri-mandal** [comment]
> @himadri-mandal just let us know which ones you are picking up so we don't step on each other 🙂

I am starting from the top. My next pull request(s) will have the following.

 ClassModifierShouldBe
 ConditionAndGroupGenericParameterTypeShouldBeTheSame
 ElementsShouldBeAtLeast
 ElementsShouldBeAtMost
 ElementsShouldBeExactly
 ElementsShouldBe
 ElementsShouldHaveAtLeast
 ElementsShouldHaveAtMost
 ElementsShouldHaveExactly
 ElementsShouldHave
 ElementsShouldMatch
 ElementsShouldNotBe
 ElementsShouldNotHave
 ElementsShouldSatisfy
 NoElementsShouldMatch

**Comment by himadri-mandal** [comment]
@scordio Is it ok to submit multiple commits on a single pull request, I see  #2097 is still not merged, or am I missing anything.

**Comment by scordio** [comment]
@himadri-mandal I think it is fine, each change is anyway small and it is not difficult to review them together.
