### ISSUE TITLE
Generic return type for AbstractSoftAssertions.fail

### ISSUE THREAD

**Issue by pfhartma** [assertj/assertj-core#2094]
#### Summary
The `fail` method in `Assertions` has generic return type:
```java
public static <T> T fail(String failureMessage)
```
This is convenient in a number of situations.

In contrast to this, the corresponding `fail` method in `AbstractSoftAssertions` has a return type of `void`:
```java
public void fail(String failureMessage)
```

 I would prefer to have both classes consistent, preferably with generic return type for `AbstractSoftAssertions.fail`.

**Comment by joel-costigliola** [comment]
Done

**Comment by vlsi** [comment]
@pfhartma , would you clarify when the generic return type is convenient?

I just ran into `Not enough information to infer type variable T` error when asserting like `softly.fail("...")`, so I am inclined the return types should better be removed.

**Comment by scordio** [comment]
@vlsi it's mentioned in its [Javadoc](URL):

> **Returns:**
>   nothing, it's just to be used in `doSomething(optional.orElseGet(() -> fail("boom")));`.

I see JUnit 5 [elaborates it better](https://junit.org/junit5/docs/5.8.2/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html#fail(java.lang.String)):

> The generic return type `V` allows this method to be used directly as a single-statement lambda expression, thereby avoiding the need to implement a code block with an explicit return value. Since this method throws an [`AssertionFailedError`](https://ota4j-team.github.io/opentest4j/docs/1.2.0/api/org/opentest4j/AssertionFailedError.html) before its return statement, this method never actually returns a value to its caller. The following example demonstrates how this may be used in practice.
>
> ```java
>  Stream.of().map(entry -> fail("should not be called"));
> ```

**Comment by vlsi** [comment]
@scordio , I've filed https://github.com/assertj/assertj/issues/2895 to revert this change, however, I believe the usage you suggest is unsafe.

```java
doSomething(optional.orElseGet(() -> fail("boom")));.
```

`fail` would return `null`, and it would result in `doSomething(null)` which might fail with NPE or another unexpected reason.
If people want to call method with `null` parameter, then they should do that instead of passing `fail(...)` value.

**Comment by vlsi** [comment]
JUnit5 justification does not apply to soft assertions as the resulting value does reach user-code 🤷‍♂️
