### ISSUE TITLE
Maps.assertContainsOnly(info, actual, entries) has inconsistent behaviour if `entries` is empty

### ISSUE THREAD

**Issue by oxygenecore** [assertj/assertj-core#2107]
https://github.com/assertj/assertj-core/blob/f27b022a369ba731ed72413f6c10c82a9e539495/src/main/java/org/assertj/core/internal/Maps.java#L745
The call mentioned in the link fails with IllegalArgumentException if `entries` is empty, and `actual` is not. This, however, would work if `actual` is empty as well (the mentioned line is not executed in this case). Thus, execution success depends on `actual` input, which is the most frequently changing part of the test.
I would expect this code to fail with AssertionError with proper message (`actual should be empty, but was XXX`)

**Comment by joel-costigliola** [comment]
I agree the error message should be as you said.
Are you keen to contribute it?

**Comment by abhijeetshuklaoist** [comment]
@joel-costigliola I would like to pick it up. If it's free for me to take, please assign it to me.

**Comment by joel-costigliola** [comment]
Thanks @abhijeetshuklaoist

**Comment by joel-costigliola** [comment]
@abhijeetshuklaoist have you made any progress?

**Comment by abhijeetshuklaoist** [comment]
Sorry I have been occupied for some time. I will get to it right away. 
Thanks!

**Comment by abhijeetshuklaoist** [comment]
@joel-costigliola What should be the correct behaviour here? 

Below are the use cases that I think should be there, if let me know if my understanding is correct.
1. If both Actual and Entries are empty : Should be an assertion success
2. If Actual is empty but Entries is not empty: AssertionFail with message "Actual is empty but should contain Entries" 
3. If Actual is not empty but Entries is empty: AssertionFail with message "Actual should be empty but was Entries" 

Thanks!

**Comment by joel-costigliola** [comment]
that's correct, 1. and 2. are already handled properly, 3. can be improved with a better error message.
We must not change `failIfEmpty` because it is used elsewhere, instead we replace it in `assertContainsOnly` and `assertContainsExactly` by calling `assertEmpty` as you suggested (good idea!) if `entries` is empty.

Does that make sense?
