### ISSUE TITLE
ListAssert containsSequence and containsSubsequence are misleading method names

### ISSUE THREAD

**Issue by YassinHajaj** [assertj/assertj-core#2112]
#### Summary
Hi,

I'm wondering why those names have been choosen for those methods.

In my opinion, the following names would be more suited

_containsSequence_ => _containsSubsequence_
_containsSubsequence_ => _containsInSequentialOrder_

For the second one, the name is maybe not the ideal one but it already expresses the intention of the method.

**Comment by joel-costigliola** [comment]
It's the match definition, a subsequence is about the order but you can skip elements whereas a sequence  you can't skip elements, see https://en.wikipedia.org/wiki/Subsequence.

**Comment by YassinHajaj** [comment]
Thanks for the reference @joel-costigliola , I was confused but thats only due to my wrong understanding of the concept
