### ISSUE TITLE
Add isNotFinite and isNotInfinite for floating-point types (double, float)

### ISSUE THREAD

**Issue by jcttrll** [assertj/assertj-core#2120]
#### Summary

`isFinite()` and `isInfinite()` assertions were handily added via #2005. In the comments on PR #2006, it looks like the original author believed `isNotFinite()` and `isNotInfinite()` were unnecessary, perhaps because they appear to be opposites.

However, `Double.isFinite()` and `Double.isInfinite()` (and corresponding `Float` methods) aren't exact opposites. `isFinite()` means:
* Not `POSITIVE_INFINITY`, _and_
* Not `NEGATIVE_INFINITY`, _and_
* Not `NaN`

`isInfinite()` means:
* `POSITIVE_INFINITY`, _or_
* `NEGATIVE_INFINITY`

While it's possible to achieve the same result as `isNotInfinite()` with `isNotEqualTo(Double.POSITIVE_INFINITY).isNotEqualTo(Double.NEGATIVE_INFINITY)`, that's a little cumbersome. 

`isNotFinite()` is much trickier to achieve--the best I've been able to do is `satisfiesAnyOf(...)`, but that's very cumbersome, indeed.

**Comment by scordio** [comment]
Fair point @jcttrll, keen to contribute?

**Comment by jcttrll** [comment]
@scordio Sure, I'll give it a try! Might not be for a couple of days, though.

**Comment by scordio** [comment]
Thank you @jcttrll, take your time and let us know if you need anything.
