### ISSUE TITLE
Display type of test in the description consumer report

### ISSUE THREAD

**Issue by ryanh007** [assertj/assertj-core#2129]
#### Summary
Wondering if there is a way to display the test operation being done in the description consumer  report

#### Example
Building off of this example
https://assertj.github.io/doc/#assertj-core-assertion-description-consumer

Assertions:
-- check name _[isEqualTo Frodo]_
-- check age _[isEqualTo 33]_

So whatever the test is .isXXX() (isTrue(), isEmpty0 etc) operation would be a report option that can be logged, along with the expected value

```java

```

**Comment by joel-costigliola** [comment]
Nope, the reason is the description passed to `as()` comes before the assertion so at this point AssertJ does not know what assertion is going to be performed.

**Comment by ryanh007** [comment]
> 
> 
> Nope, the reason is the description passed to `as()` comes before the assertion so at this point AssertJ does not know what assertion is going to be performed.

ah ok, I'll close this out then
thx
