### ISSUE TITLE
According to docs hasOnlyFields should not consider static fields, but it does

### ISSUE THREAD

**Issue by sdahlberg** [assertj/assertj-core#2136]
#### Summary

According to the [docs](https://assertj.github.io/doc/#assertj-core-3.19.0-hasOnlyFields) static fields shouldn't be considered, but they are.

#### Example

```java
public class Person {
    private static final String TEST = "test";
    private String name;
}

assertThat(new Person()).hasOnlyFields("name")
```
Outcome:

Expecting non static/synthetic fields of:
Person@769c9116
to contain only:
  ["name"]
but the following fields were unexpected:
  ["TEST"]

**Comment by joel-costigliola** [comment]
Thanks for reporting this @sdahlberg! which version are you using?

**Comment by sdahlberg** [comment]
I'm using 3.19.0

**Comment by sdahlberg** [comment]
That´s swift! Thanks alot! :)
