### ISSUE TITLE
Feature request: allow ignoring duplicates in assertThat(someSet).map(x::mapper)

### ISSUE THREAD

**Issue by C-Otto** [assertj/assertj-core#2139]
#### Summary
I have a set of values `Set<Foo> set = Set.of(a, b)` with size 2, i.e. `a.equals(b) == false`.
With `assertThat(set).map(Foo::getX)` I can extract property `x` out of my class and run assertions on the resulting collection:

`assertThat(set).map(Foo::getX).hasSize(1) // fails if a.x == b.x`

Against my intuition, this assertion fails if both elements of `set` have the same property `x`, i.e. the result of `map` gives me a list with two identical values.

I understand that this behaviour is correct, and that my intuition was wrong. However, I'd like to be able to work with "set" logic, i.e. ignore duplicates. The following example might help in my case:

`assertThat(set).mapToSet(Foo::getX).hasSize(1) // success even if if a.x == b.x`

Maybe a dedicated "remove duplicates" step might help:

```
assertThat(set).map(Foo::getX).removeDuplicates().hasSize(1) // success even if if a.x == b.x
assertThat(set).map(Foo::getX).toSet().hasSize(1) // success even if if a.x == b.x
assertThat(set).map(Foo::getX).asSet().hasSize(1) // success even if if a.x == b.x
```

Note that changing the logic of `map` (if invoked on a set) doesn't seem to be a good idea wrt. backwards compatibility (and it would be different from what `Stream.map` does).

**Comment by joel-costigliola** [comment]
I get your point but do you really need to check the size in your example? You could check the content with `containsOnly` and not check the size unless you really want to.
```
assertThat(set).map(Foo::getX).containsOnly(a.x);
```

**Comment by C-Otto** [comment]
The example above is simplified. One example that I'd like to simplify using AssertJ:

`assertThat(xxx.stream().map(Foo::getBar).collect(toSet())).hasSize(1);`

In this example I don't know a lot about `xxx`, but I know that for this specific test, the "bar" property should always be the same. Note that I don't know the exact value, I just know that the resulting set only contains one element.

**Comment by joel-costigliola** [comment]
Thanks for the additional details.

**Comment by sustc11810424** [comment]
Hello there, is this still open?  If yes, can I to try to implement it as a feature?

**Comment by joel-costigliola** [comment]
@C-Otto is your initial mostly address by my previous comment? 
I kinda feel the last case you could not simplify is quite rare and would not justify adding to `asSet` method but not decision set in stone yet.

@sustc11810424 this is still undecided but happy to give this to you if we reach a decision that would require a contribution

**Comment by C-Otto** [comment]
I agree, it is a rather exotic use case.

**Comment by joel-costigliola** [comment]
Thanks @C-Otto I'll close the issue then
