### ISSUE TITLE
Add hasCauseSatisfying()

### ISSUE THREAD

**Issue by wimdeblauwe** [assertj/assertj-core#2141]
#### Summary

I would love to have an extra method `hasCauseSatisfying()` on ThrowableAssertAlternative

#### Example

```java
assertThatExceptionOfType(ConstraintViolationException.class)
  .isThrownBy( () -> ....)
  .hasCauseSatisfying( ex  -> {
     assertThat(ex.getConstraintViolations())
         .hasViolationOnPath("foo");
   });
```

(That assert inside the proposed method would use https://www.wimdeblauwe.com/blog/2016/2016-04-01-assertj-custom-assertion-for-testing-constraintvalidator-implementations/ )

I am not sure if it would be possible to have `ex` typed to `ConstraintViolationException`. Would be great if it could, but if not, that would also be ok for me.

**Comment by scordio** [comment]
`ConstraintViolationException` belongs to the java validation api, so no chance we can have it in assertj-core.

On the other hand, I had in mind for some time to kickstart a separate assertj module to aid in bean validation tests, especially to have a nicer API. Is that something that would interest you too?

**Comment by scordio** [comment]
@wimdeblauwe maybe one clarification about the provided example: the lambda parameter should contain the cause, otherwise you would just use the existing `satisfies`, right?

**Comment by wimdeblauwe** [comment]
Whoops, I totally missed that `satisfies` method. That is what I need. You can ignore this request.

For reference, the example becomes:

```
assertThatExceptionOfType(ConstraintViolationException.class)
  .isThrownBy( () -> ....)
  .satisfies( ex  -> {
     assertThat(ex.getConstraintViolations())
         .hasViolationOnPath("foo");
   });
```

**Comment by scordio** [comment]
@onacit released an AssertJ extension for bean validation testing (https://github.com/assertj/assertj-core/issues/753#issuecomment-803954755): https://github.com/jinahya/assertj-bean-validation
