### ISSUE TITLE
RecursiveComparison with ignoringCollectionOrder failed with not java.lang types

### ISSUE THREAD

**Issue by clarkdo** [assertj/assertj-core#2144]
#### Summary

Version: 3.17.1

Let's define an enum and a pojo class:

```java
enum Type {
  FIRST,
  SECOND,
}

class Person {
  String id;
  String name;
  Type type;

  Person(String id, String name, Type type) {
    this.id = id;
    this.name = name;
    this.type = type;
  }
}
```

Then if we assert two lists of `Person` objects with `usingRecursiveComparison` and `ignoringCollectionOrder`, the test will pass without any problem:

```js
assertThat(
  Arrays.asList(
    new Person("1", "name-1", Type.FIRST),
    new Person("1", "name-2", Type.FIRST),
    new Person("1", "name-2", Type.SECOND)
  )
)
  .usingRecursiveComparison()
  .ignoringCollectionOrder()
  .ignoringOverriddenEqualsForTypes(Person.class)
  .isEqualTo(
    Arrays.asList(
      new Person("1", "name-1", Type.FIRST), // 1
      new Person("1", "name-2", Type.FIRST), // 2
      new Person("1", "name-2", Type.SECOND) // 3
    )
  );
```

But if we change the list order slightly, the assertion will fail:

```js
assertThat(
  Arrays.asList(
    new Person("1", "name-1", Type.FIRST),
    new Person("1", "name-2", Type.FIRST),
    new Person("1", "name-2", Type.SECOND)
  )
)
  .usingRecursiveComparison()
  .ignoringCollectionOrder()
  .ignoringOverriddenEqualsForTypes(Person.class)
  .isEqualTo(
    Arrays.asList(
      new Person("1", "name-2", Type.SECOND), // 3
      new Person("1", "name-2", Type.FIRST),  // 2
      new Person("1", "name-1", Type.FIRST)   // 1
    )
  );
```

I think this error is from https://github.com/assertj/assertj-core/commit/d66da9f8904a2386c54b6ca409d8973b5642c131 and [visitedDualValues.add(dualValue)](https://github.com/assertj/assertj-core/blob/0f1039f2900602e72c20f67a9e58c30f829b27e0/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java#L107) because the first matching of 2 lists will mark "actual: `Type.FIRST`, expect: `Type.SECOND`" as visited value and be removed in other following objects comparison, so `Person("1", "name-2", Type.FIRST)` and  `Person("1", "name-2", Type.FIRST)` will be considered as no difference.

**Comment by joel-costigliola** [comment]
Thanks for the detailed issue, we will look at it for the next release.

**Comment by joel-costigliola** [comment]
@clarkdo as a side note, you can now skip `.ignoringOverriddenEqualsForTypes(Person.class)` since 3.17.0 the recursive comparison  by default won't use equals unless explicitly told to do so.
