### ISSUE TITLE
containsSubsequence fails to check presence of multiple EMPTY Strings

### ISSUE THREAD

**Issue by dr29bart** [assertj/assertj-core#2158]
#### Summary
containsSubsequence should not fail to check presence of multiple EMPTY Strings in EMPTY String

#### Example

```java
import org.assertj.core.api.Assertions;
import org.testng.annotations.Test;

public class T {

    @Test
    public void test(){
        Assertions.assertThat("")
            .containsSubsequence("") // passes
            .containsSubsequence("", ""); // fails
    }
}
```

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

	at java.base/java.lang.String.substring(String.java:1837)
	at org.assertj.core.internal.Strings.removeUpTo(Strings.java:1049)
	at org.assertj.core.internal.Strings.assertContainsSubsequence(Strings.java:1038)
	at org.assertj.core.api.AbstractCharSequenceAssert.containsSubsequence(AbstractCharSequenceAssert.java:769)
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this @dr29bart!

**Comment by wtd2** [comment]
I wonder if this issue is still open, and I would like to work on this issue :).

**Comment by wtd2** [comment]
The occurrence of this issue is due to the result of function `indexOf("", "")` is `-1`, which leads to the exception.

I would like to add an **if** statement for the function `indexOf` in the file `Strings.java` as follows

```java
if (string.equals("") && toFind.toString().equals(""))
  return 0;
```

**Comment by joel-costigliola** [comment]
@wtd2 thanks, go for it, I suggest you raise a PR for code guidance, it's a bit easier for us to review your changes.
