### ISSUE TITLE
Map `containsOnly` assertions don't work correctly with case insensitive keys

### ISSUE THREAD

**Issue by filiphr** [assertj/assertj-core#2159]
#### Summary

When using case insensitive maps the map assertions for containsOnly are not working correctly.
The reason for this is due to the fact that the actual map is copied into a `LinkedHashMap` and thus the checks are not using the map.

#### Example

```java
Map<String, String> map = new LinkedCaseInsensitiveMap<>();
map.put("TEST", "value");
```

The following assertions will pass
```java
assertThat(map).containsKey("test");
assertThat(map).contains(entry("test", "value"));
```

The following assertions will fail
```java
assertThat(map).containsOnlyKeys("test");
assertThat(map).containsOnly(entry("test", "value"));
```

Note: `LinkedCaseInsensitiveMap` is from Spring.

If you agree I can work on a PR to change the mechanism that is used for validating `containsOnly` entries.

**Comment by joel-costigliola** [comment]
Yep, it would be great to have a PR on this, thanks @filiphr!

**Comment by scordio** [comment]
Interestingly enough, the example doesn't fail with `org.apache.commons.collections4.map.CaseInsensitiveMap`.

I tried the following without any changes from #2160 or #2167:

```java
  @Test
  void with_Commons_Collections_CaseInsensitiveMap() { // version 4.4
    Map<String, String> map = new CaseInsensitiveMap<>();
    map.put("TEST", "value");

    assertThat(map).containsKey("test");
    assertThat(map).contains(entry("test", "value"));

    assertThat(map).containsOnlyKeys("test");
    assertThat(map).containsOnly(entry("test", "value"));
  }

  @Test
  void with_Spring_LinkedCaseInsensitiveMap() { // version 5.3.5
    Map<String, String> map = new LinkedCaseInsensitiveMap<>();
    map.put("TEST", "value");

    assertThat(map).containsKey("test");
    assertThat(map).contains(entry("test", "value"));

    assertThat(map).containsOnlyKeys("test");
    assertThat(map).containsOnly(entry("test", "value"));
  }
```

and only the second test fails.

**Comment by nach-o-man** [comment]
@filiphr @joel-costigliola @scordio this issue also applies to sorted Maps

```
    Map<String, String> actual = new TreeMap<>(String::compareToIgnoreCase);

    actual.put("Color", "green");
    actual.put("NAME", "Yoda");

    Assertions.assertThat(actual).containsExactly(
                                                  new AbstractMap.SimpleEntry<>("COLOR", "green"),
                                                  new AbstractMap.SimpleEntry<>("Name", "Yoda"));
```

**Comment by filiphr** [comment]
That's a good one. I think that with the work @scordio has been doing this case is covered. This is another good test case.

btw @nach-o-man AssertJ already provides a factory method for creating `Map.Entry`. It is in `Assertions#entry`, a small hint in case you didn't know. If you statically import it the test then looks like:

```
 Map<String, String> actual = new TreeMap<>(String::compareToIgnoreCase);

    actual.put("Color", "green");
    actual.put("NAME", "Yoda");

    Assertions.assertThat(actual).containsExactly(
                                                  entry("COLOR", "green"),
                                                  entry("Name", "Yoda"));
```

**Comment by scordio** [comment]
Thanks @nach-o-man, test case added in a061788886d60b26ea4f63df3c962e928a1a9f2c
