### ISSUE TITLE
assertThat(boolean).isNotNull() should throw an exception

### ISSUE THREAD

**Issue by Bananeweizen** [assertj/assertj-core#2185]
#### Summary
`assertThat(methodWithPrimitiveBooleanReturn()).isNotNull()` doesn't make any sense, but passes in any case, independent of the method return value (true/false). Developers will not write such code intentionally, but it can be created by incomplete refactorings.

I suggest to throw an exception from `AbstractBooleanAssert.isNotNull()` (or similar), if the type of the argument is _primitive_ boolean. (I must admit I don't know if the framework can differentiate between primitive and boxed types there).

#### Example

```java
assertThat(true).isNotNull(); // passes
assertThat(false).isNotNull() // also passes
```

**Comment by joel-costigliola** [comment]
We can't know whether the value was a originally a primitive as AssertJ stores it as its wrapper counterpart, e.g. `assertThat(true)` is the same as `assertThat(Boolean.TRUE)` thus there is not much we can do here (without a major refactoring anyway).

**Comment by joel-costigliola** [comment]
I'm closing this issue for now, @Bananeweizen let us know if you're ok with that.
