### ISSUE TITLE
Map assertions to give better information about matching keys with different values

### ISSUE THREAD

**Issue by kriegfrj** [assertj/assertj-core#2197]
#### Summary

Had a `containsEntry()` map assertion that failed because the entry was missing.

It was unclear from the diagnostic message whether the failure was because there was no entry present, or because there was an entry present for that key with a different value.

Proposal:

* If an entry is present with the same key, the failure message should say that it failed because the values were different.
* If no entry is present with the same key, the failure message should say that it failed because no entry was present for that key.

Some suggestions:

Current:
```
Expecting map:
 <{"accept"="application/json", "authorization"="bearer eagraahl" ...}>
to contain:
 <[MapEntry[key="authorization", value="bearer ezfufztp"]]>
but could not find the following map entries:
 <[MapEntry[key="authorization", value="bearer ezfufztp"]]>
```

Suggestion 1:
```
Expecting map:
 <{"accept"="application/json", "authorization"="bearer eagraahl" ...}>
to contain entry:
 <[MapEntry[key="authorization", value="bearer ezfufztp"]]>
but key had different value:
 <[MapEntry[key="authorization", value="bearer eagraahl"]]>
```

Suggestion 2:
```
Expecting key:
 <authorization>
in map:
 <{"accept"="application/json", "authorization"="bearer eagraahl" ...}>
to have value:
 <bearer ezfufztp>
but it was:
 <bearer eagraahl>
```

**Comment by joel-costigliola** [comment]
I get your point @kriegfrj, I would go with suggestion 1 because it shows entries and the assertion is about entries.

**Comment by sustc11810424** [comment]
Thanks for all this!

So the direct solution would be to make `assertj/core/internal/Maps.failIfAnyEntryNotFoundInActualMap` differentiate between the two causes, namely `entryNotFound` and `valueDoesNotMatch`.

like:

```java
private <K, V> void failIfAnyEntryNotFoundInActualMap(AssertionInfo info, Map<K, V> actual,
                                                        Map.Entry<? extends K, ? extends V>[] entries) {
    Set<Map.Entry<? extends K, ? extends V>> notFound = new LinkedHashSet<>();
    Set<Map.Entry<? extends K, ? extends V>> notMatch= new LinkedHashSet<>();
    for (Map.Entry<? extends K, ? extends V> entry : entries) {
      if (!containsEntry(actual, entry)) notFound.add(entry); // check for existence
      else if(!matchesInValue(actual, enty)) notMatch.add(entry); // check for consistence
    }
    if (!notFound.isEmpty()) throw failures.failure(info,
                                                    shouldContain(actual, entries, notFound)),
                                                    shouldHaveValues(actual, entries, notMatch);
  }
```

The methods that will be affected are 
```java
public <K, V> void assertContains(AssertionInfo info, Map<K, V> actual,
                                    Map.Entry<? extends K, ? extends V>[] entries) {...}

public <K, V> void assertContainsAllEntriesOf(AssertionInfo info, Map<K, V> actual,
                                                Map<? extends K, ? extends V> other) {...}
```
Can I take this? If yes, is there any suggestion on formatting the failure message (since we may need to print out both causes for `assertContainsAllEntriesOf`) ? 

Thanks again!

**Comment by scordio** [comment]
Please wait for #2167 as there will be some changes in `org.assertj.core.internal.Maps`

**Comment by joel-costigliola** [comment]
@sustc11810424 thanks, assigned to you but let's get #2167 first.

**Comment by kriegfrj** [comment]
> Thanks for all this!
>

Thanks for agreeing to take this on!
 
> So the direct solution would be to make `assertj/core/internal/Maps.failIfAnyEntryNotFoundInActualMap` differentiate between the two causes, namely `entryNotFound` and `valueDoesNotMatch`.
> 
> like:
> 
> ```java
> private <K, V> void failIfAnyEntryNotFoundInActualMap(AssertionInfo info, Map<K, V> actual,
>                                                         Map.Entry<? extends K, ? extends V>[] entries) {
>     Set<Map.Entry<? extends K, ? extends V>> notFound = new LinkedHashSet<>();
>     Set<Map.Entry<? extends K, ? extends V>> notMatch= new LinkedHashSet<>();
>     for (Map.Entry<? extends K, ? extends V> entry : entries) {
>       if (!containsEntry(actual, entry)) notFound.add(entry); // check for existence

You should use `!containsKey()` rather than `!containsEntry()`, otherwise it will be equivalent to the current implementation (I think).

>       else if(!matchesInValue(actual, enty)) notMatch.add(entry); // check for consistence
>     }
>     if (!notFound.isEmpty()) throw failures.failure(info,

Need to add `|| !notMatch.isEmpty()` to the if condition.

>                                                     shouldContain(actual, entries, notFound)),
>                                                     shouldHaveValues(actual, entries, notMatch);
>   }
> ```
> 

> Can I take this? If yes, is there any suggestion on formatting the failure message (since we may need to print out both causes for `assertContainsAllEntriesOf`) ?
>

Yes, the error message will need to be able to handle one, both, or none of the failure modes.

org.assertj.core.error.AssertJMultipleFailuresError: 
Multiple Failures (1 failure)
-- failure 1 --
[headers] 
Expecting map:
 <{"accept"="text/json", "authorization"="bearer eagraahl",...>
to contain:
 <[MapEntry[key="authorisation", value="bearer ezfufztp"], MapEntry[key="accept", value="application/json"]]>
but could not find the following map entries:
 <[MapEntry[key="authorisation", value="bearer ezfufztp"]]>
and the following map entries had different values:
 <[MapEntry[key="accept", value="text/json"] (expecting <application/json>)]>
 ```

Actually, it occurred to me that we could probably make this output more concise (and more usable), like this:
```
to contain:
 <["authorisation"="bearer ezfufztp"], ["accept"="application/json"]]>
but could not find the following map entries:
 <["authorisation"="bearer ezfufztp"]>
and the following map entries had different values:
 <["accept"=>"text/json"] (expecting <application/json>),
```

For correct English grammar, make sure that "and" only gets added if both failure types are present.

**Comment by joel-costigliola** [comment]
@sustc11810424 now that #2167 is done, can you rebase your work on main and address the comments?

**Comment by joel-costigliola** [comment]
@kriegfrj  I'm working on this and at the moment I have got something like:
```
Expecting map:
  {"age"="500", "color"="green", "name"="yoda"}
to contain entries:
  ["NAME"="yoda", "color"="red", "age"="100"]
but could not find the following map entries:
  ["NAME"="yoda"]
and the following map entries had different values:
  ["color"="green" (expected: "red"), "age"="500" (expected: "100")]
```
I changed the representation of `MapEntry` to be `key=value` to get the above message.

WDYT?

**Comment by kriegfrj** [comment]
LGTM, @joel-costigliola ! Thanks!
