### ISSUE TITLE
Remove space in default error message for ShouldBeEqual to help IntelliJ diff detection

### ISSUE THREAD

**Issue by rpeng** [assertj/assertj-core#2199]
Referencing this StackOverflow ticket: https://stackoverflow.com/questions/10934743/formatting-output-so-that-intellij-idea-shows-diffs-for-two-texts

It seems that IntelliJ expects assertion errors to be in this format in order to have nicely rendered diffs:

`expected: xxx but was: yyy`

But AssertJ would format this with an extra space after the `was`:

`expected: xxx but was : yyy`

Which would cause it to fail the regex, and IntelliJ defaults to just printing the error string. I tried patching my AssertJ `ShouldBeEqual` locally without that extra space, and IntelliJ was then able to detect it properly.

Would it be possible to remove the extraneous space after the `was` so that the test output can automatically be detected as a diff?

Thanks!

Link to message: https://github.com/assertj/assertj-core/blob/main/src/main/java/org/assertj/core/error/ShouldBeEqual.java#L44

**Comment by joel-costigliola** [comment]
We did that to get values aligned but I guess we can remove that space for intellij idea
```
expected:
but was :
```
@rpeng could we do that instead?:
```
expected:
 but was:
```
@scordio did you have that issue? can you try that second proposal to see if it renders properly?

**Comment by rpeng** [comment]
Just tried it out with the second proposal (leading space) and it works!

**Comment by joel-costigliola** [comment]
thanks @rpeng! let's do that then.
Do you want to contribute it?

**Comment by rpeng** [comment]
Will do! I'll get a pull request ready shortly

**Comment by rpeng** [comment]
Just made a pull https://github.com/assertj/assertj-core/pull/2200

Sorry about the noise above, I accidentally made a pull against my own fork...

**Comment by scordio** [comment]
Hi @rpeng, do you have a concrete example that was not working as expected? I didn't see any issue with IntelliJ IDEA 2021.1.

For example, with the following:

```java
  @Test
  void test() {
    assertThat(new Object()).isEqualTo(0);
  }
```

I get:

![Screenshot 2021-05-06 at 21 03 53](https://user-images.githubusercontent.com/26772046/117351919-97d82700-aeae-11eb-9a0c-b4e59e8cf8a6.png)

which has already the link for the diff.

**Comment by rpeng** [comment]
Hmm @scordio, I'm on IntelliJ IDEA Ultimate 2020.2, and this is what I get:


```
  @Test public void testAssert() {
    assertThat(new Object()).isEqualTo(0);
  }
```

![image](https://user-images.githubusercontent.com/575174/117355235-2b860500-ae67-11eb-9aee-de5eb4c8d3e9.png)

I wonder if IntelliJ's error parsing behavior changed between 2020.x and 2021.x versions

**Comment by filiphr** [comment]
To my knowledge when using the AssertionFailure from opentest4j IntelliJ will get the values from the exception itself, not looking into the string output.

**Comment by rpeng** [comment]
Ah I did not know that, thanks for the insight. I wonder if this may be build-system dependent then. For example, when I run the test in IntelliJ, if it has to rely on capturing the output from an external tool (e.g. bazel?) instead of running it directly, it might have to resort to text matching to detect the expected vs. actual.

**Comment by scordio** [comment]
@rpeng not sure if it's possible, but it would be great to have a minimal example to play with it and understand the issue a bit better.

**Comment by rpeng** [comment]
@scordio Just made a simple example https://github.com/rpeng/assertj-minimal-bazel-run

Let me know if you have any issues reproducing it!
