### ISSUE TITLE
Implement ReaderAssert in a similar way as InputStreamAssert

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#22]
original issues : https://github.com/alexruiz/fest-assert-2.x/issues/46

I think that ReaderAssert should be implemented. Basically the functionality should have assertion methods to compare to other Reader as well as some textual support.

From my point of view, it will be cool if you could make an assertion if Reader contains some text. The question is how much similarity with StringAssert should be there?

**Comment by nach-o-man** [comment]
If it is still desired I could try implementing it.

**Comment by joel-costigliola** [comment]
@nach-o-man thanks for your interest, I'll discuss with the team to see if it is still relevant (quite an old issue :sweat_smile: )

**Comment by nach-o-man** [comment]
Ideed it is. Will browse to check if there is anythin I could grab. :)

**Comment by joel-costigliola** [comment]
We decided to close it since it was a bit of a corner case considering that there are ways to obtain an `InputStream` from a `Reader` and we have `InputStream` assertions.

**Comment by davidsusu** [comment]
`ReaderAssert` would be **very** useful. IMO `Reader` and `InputStream` are quite different. From a testing perspective `Reader` (with a small content) is more like to `String`.

`InputStreamAssert` could have `asReader(Charset)`. (Also, `InputStreamAssert` should have an `asString(Charset)` method, just like `ByteArrayAssert`.)

> there are ways to obtain an InputStream from a Reader

What do you mean by this? In some cases, it's not so easy. The standard library has no tool for generally achieving such a conversion (of course, apache-commons has `ReaderInputStream`, like some other third-party helper libs). Either way, `ReaderAssert` would be the proper fluent way to test `Reader`s.

**Comment by scordio** [comment]
@davidsusu would you have some concrete examples to help re-evaluate the topic?
