### ISSUE TITLE
ShouldNotBe: missing linebreak OR to much whitespaces 

### ISSUE THREAD

**Issue by stbischof** [assertj/assertj-core#2202]
ShouldNotBe has a missing linebreak OR to much whitespaces.

https://github.com/assertj/assertj-core/blob/e14081576c22240c45dd2f8f2d3afa7d42303faf/src/main/java/org/assertj/core/error/ShouldNotBe.java#L38

`"%nExpecting actual:%n  %s%nnot to be [ ]%s"`

**Comment by joel-costigliola** [comment]
I looks like there is an extra space here 
```
to be  %s
```
it should be 
```
to be %s
```

**Comment by Annette0127** [comment]
Hi, I would like to help with this issue! 😊
So from the description, all I need to do is to delete a white space?

**Comment by joel-costigliola** [comment]
Let's change `ShouldNotHave` too to follow the same pattern and be:
```
"%nExpecting actual:%n  %s%nnot to have %s"
```
