### ISSUE TITLE
`hasAllNullFieldsOrProperties` and primitive types

### ISSUE THREAD

**Issue by slawekjaranowski** [assertj/assertj-core#2210]
#### Summary

`hasAllNullFieldsOrProperties` check that the actual object has only null fields or properties.

All fields and properties are inspected but fields with primitive types always will have some value.

#### Example

```java
    class Book {
        String title;
        int pages;
    }

    @Test
    void testHasAllNullFieldsOrProperties() {
        Book book = new Book();
        assertThat(book).hasAllNullFieldsOrProperties();
    }
```

test will fail because of field `pages` is not null.

#### Proposition

Exclude by default all field with primitive types from assertion.

**Comment by wuqihan837** [comment]
I want to have a try on the issue, thanks.

**Comment by nach-o-man** [comment]
@slawekjaranowski primitives cannot be `null` - they have default values if not initialized. It is clearly stated in https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

**Comment by wuqihan837** [comment]
@nach-o-man I guess he meant primitive types should be ignored and not be considered when using hasAllNullFieldsOrProperties. Otherwise, if a class has primitive fields, the test will always fail. I'm not sure.

**Comment by nach-o-man** [comment]
Fair point, I understood this wrong when I read it for the first time. But I do think it is not right add such functionality.
This exactly falling test case can show design/logic flaws and can be avoided with the use of `hasNoNullFieldsOrPropertiesExcept`

**Comment by slawekjaranowski** [comment]
I used `hasNoNullFieldsOrPropertiesExcept` at current time with list of field which should be excluded.

Primitive types always have value, so. we always must be exclude it.

As my proposition in issue its can be excluded / skipped by default.

**Comment by wuqihan837** [comment]
@slawekjaranowski  I will have a try and make a pull request to skip primitive types by default.  I may add a new method.

**Comment by joel-costigliola** [comment]
@wuqihan837 before submitting a PR, give the assertj team a bit of time to think on how to address the issue.

My first comment would be that the current assertion does its job as primitive types are never null, changing it would be a breaking change so we might choose a different option, maybe overloading `hasAllNullFieldsOrProperties(boolean excludePrimitiveTypes)` but no decision has been reached yet.

**Comment by scordio** [comment]
The definition of field or property does not exclude primitive types, so I don't see an issue with the current behavior of `hasAllNullFieldsOrProperties`.

To simplify the primitive types use case, I vote for `hasAllNullFieldsOrProperties(boolean excludePrimitiveTypes)` or also `hasAllNullFieldsOrPropertiesExceptPrimitiveTypes()`.

**Comment by joel-costigliola** [comment]
I vote for `hasAllNullFieldsOrPropertiesExceptPrimitiveTypes()`, it is a long name but it is explicit whereas `hasAllNullFieldsOrProperties(true)` is not really self explanatory.

**Comment by KevinChen16** [comment]
What about using `hasAllDefaultValueForFieldsOrProperties()`? Because I believe that most of the time users use this function to validate whether there are any fields or properties changed or not clear, using `hasAllNullFieldsOrPropertiesExceptPrimitiveTypes()` will bring the misunderstanding that the method ignores all changes in primitive types? And I also wonder if there is something that needs to be done about this issue? I could help it.

**Comment by joel-costigliola** [comment]
This is now fixed by the introduction of the recursive assertion:

```java
@Test
void testHasAllNullFieldsOrProperties() {
  Book book = new Book();

  assertThat(book).usingRecursiveAssertion()
                  .ignoringPrimitiveFields()
                  .allFieldsSatisfy(field -> field == null);
}
```
