### ISSUE TITLE
`hasNoNullFieldsOrProperties` - recurrence

### ISSUE THREAD

**Issue by slawekjaranowski** [assertj/assertj-core#2211]
#### Summary

When we have more complicated objects structure it will be useful to have possibility to check that all fields for actual object and all fields in included object are also not null. 

#### Example

```java
    class Author {
        String name;
        String email;

        Author(String name, String email) {
            this.name = name;
            this.email = email;
        }
    }

    class Book {
        String title;
        Author author;

        Book(String title, Author author) {
            this.title = title;
            this.author = author;
        }
    }

    @Test
    void testHasNoNullFieldsOrProperties() {
        Book book = new Book("title", new Author(null, null));
        assertThat(book).hasNoNullFieldsOrProperties();
        assertThat(book.author).hasNoNullFieldsOrProperties();
    }

```

assertion `assertThat(book).hasNoNullFieldsOrProperties()` will pass and it is true
second assertion `assertThat(book.author).hasNoNullFieldsOrProperties()` will fail and it is also ok.

When we have object with many other object we must write many assertions for each fields.
When we add new field to object we must also remember to add new assertion.

#### Proposition
 
assertion `assertThat(book).hasNoNullFieldsOrProperties()` should fail because object `book.author` has fields with `null` values.

**Comment by wuqihan837** [comment]
I want to have a try on this issue,thanks!

**Comment by nach-o-man** [comment]
Maybe such method can be added to this can be a part of `RecursiveComparisonAssert`

**Comment by slawekjaranowski** [comment]
It will be also good, I will be able to write 

```java
assertThat(book).usingRecursiveComparison().hasNoNullFieldsOrProperties();
```

but from other side method `usingRecursiveComparison` will provide not only comparator but also assertions so can be misunderstood.

Maybe more readable will be renamed `usingRecursiveComparison` -> `usingRecursive`
so we will have:

```java
assertThat(book).usingRecursive().hasNoNullFieldsOrProperties();
assertThat(book).usingRecursive().isEqualTo(anotherBook);
```

or in fluent way

```java
assertThat(book).usingRecursive()
    .hasNoNullFieldsOrProperties()
    .isEqualTo(anotherBook);
```

**Comment by joel-costigliola** [comment]
I agree with @nach-o-man, this could be added to the recursive comparison as mentioned by  @slawekjaranowski 
```java
assertThat(book).usingRecursiveComparison().hasNoNullFieldsOrProperties();
```
I don't think adding `usingRecursive` would be good in the long term, I believe people will be confused when having to decide whether to call or `usingRecursive` or `usingRecursiveComparison`.

**Comment by slawekjaranowski** [comment]
Next case for recurring checking. 
When we have some of field as collection type we should check all items of collection.

Example for current implementation:

```java
 class Book {
        String title;
        List<Author> authors;

        Book(String title, List<Author> authors) {
            this.title = title;
            this.authors = authors;
        }
    }

    @Test
    void testHasNoNullFieldsOrProperties() {
        Book book = new Book("title", Collections.singletonList(new Author(null, null)));
        assertThat(book).hasNoNullFieldsOrProperties();
        assertThat(book.authors).isNotEmpty()
                .allSatisfy(item -> assertThat(item).hasNoNullFieldsOrProperties());
    }
```

I would like to have one assertion 
```java
assertThat(book).usingRecursiveComparison().hasNoNullFieldsOrProperties(); 
```
which do all job.

**Comment by slawekjaranowski** [comment]
What is design decision?
This feature will be very useful for me.
I can try to implement it.

**Comment by joel-costigliola** [comment]
I'm thinking a better way would to apply a predicate to all fields, this is a bit more generic and would apply to your case by giving a predicate like `field -> field != null`.

This is not easy to implement, recursive comparison requires to track already visited objects to avoid infinite cycle where A <-> B.

In your case, how would you treat collection fields? if it is not null, do you want to check the content?

**Comment by slawekjaranowski** [comment]
Possibility of applying a predicate to all fields is good idea.

I would to  test collections.

My proposition:

```
   assertThat(book).usingRecursive().allSatisfyFields(filed -> { ... });
```

I look at code and package `org.assertj.core.api.recursive.comparison` has many useful hints and class, maybe some of them can be reused.  But I think recurring walk on fields will be something different that comparing.
So code can be placed in new package `org.assertj.core.api.recursive.walk`

**Comment by stefanos-kalantzis** [comment]
I would also like this feature. Either approach would work for me:
- `.usingRecursiveComparison().hasNoNullFieldsOrProperties();`
- `.usingRecursive().allSatisfyFields(filed -> { ... });` (maybe rename to "allFieldsSatisfy" or similar, for sanity)

but of course the 2nd alternative has more benefits, because we can provide a "null-or-empty" predicate (for collections).

I think this is a crucial feature to be able to avoid false-positives in object graphs.

**Comment by joel-costigliola** [comment]
My preferred option is `usingRecursiveComparison().allFieldsSatisfy(field -> ...)`

**Comment by BenTels** [comment]
Is anybody working on this? If not, can I?

**Comment by scordio** [comment]
Seems to be up for grabs, so I'll give it to you. Thanks, @BenTels!

**Comment by BenTels** [comment]
Thanks! :+1:

**Comment by BenTels** [comment]
Submitted initial solution.

Should I assign this issue to someone else now?
