### ISSUE TITLE
Fix pitest PR setup

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2214]
#### Summary

PR builds are failing with the following error:
```
Error:  No plugin found for prefix 'pitest-git' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/runner/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'pitest-git' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/runner/.m2/repository), central (https://repo.maven.apache.org/maven2)]
```
The failing command was:
```
mvn -e -B pitest-git:aggregate
```

This might be due to the fact that the pitest profile is not used unlike the previous command `mvn -e -B -Ppitest -Dfeatures="+GIT(from[HEAD~1]), +gitci" test`.

A full build is available here: https://github.com/assertj/assertj-core/pull/2213/checks?check_run_id=2590339664

**Comment by scordio** [comment]
PRs look good now (e.g., https://github.com/assertj/assertj-core/pull/2246#issuecomment-855236608)
