### ISSUE TITLE
MapAssert::containsAllEntriesOf fails if the given map is empty

### ISSUE THREAD

**Issue by mizosoft** [assertj/assertj-core#2226]
#### Summary

When checking if a map contains a set of entries, the assertion fails with `actual is not empty` if this set is empty but the map isn't. I think this shouldn't be the case and the assertion should pass since `containsAllEntriesOf` (or `contains(Entry...)`) is like a subset check, and an empty set is a subset of all sets.

#### Example

This assertion fails.

```java
assertThat(Map.of("a", "b")).containsAllEntriesOf(Map.of());
```

**Comment by joel-costigliola** [comment]
Already fixed in #2124
