### ISSUE TITLE
Add `hasSize` to `Path` assertions

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2237]
#### Example

```java
assertThat(Paths.get("file.txt")).hasSize(10);
```

Related to #2205.

**Comment by Gily-H** [comment]
Hi, I would like to work on this.

**Comment by scordio** [comment]
Sure, thanks @Gily-H. Let us know if you need any help.

**Comment by Gily-H** [comment]
Thanks @scordio. I've written the hasSize in the Path assertions and declared some unit tests for it, but I want to make sure it fits the desired functionality. Would it be appropriate to open a PR with what I have so far?

**Comment by scordio** [comment]
Sure, go for it.
