### ISSUE TITLE
pitest PR actions take a long time

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2238]
#### Summary

Pitest is executed to verify PR, the CI / pitest (pull_request)  `pitest` task seems to take forever, it's not clear if it's in the Receive or PR Update workflow.

#### Example

https://github.com/assertj/assertj-core/pull/2083/checks?check_run_id=2700985331 has started 14h 52m 7s ago and has not finished (at the time of this writing).

A pitest artefact  containing the pitest execution report is produced and is available at https://github.com/assertj/assertj-core/suites/2863716540/artifacts/63970905 and has been attached to this issue in [pitest.zip](https://github.com/assertj/assertj-core/files/6565765/pitest.zip)

![pitest](https://user-images.githubusercontent.com/382613/120092566-f91aaf80-c167-11eb-9dc7-dbd399dac1d6.png)

**Comment by joel-costigliola** [comment]
@hcoles can you help on this one?

I made 2 changes on https://github.com/assertj/assertj-core/blob/main/.github/workflows/pitest-updated-pr.yml from https://github.com/GroupCDG-Labs/pitest-github-demo/blob/main/.github/workflows/update-pr.yml:

- use of pitest profile (`-Ppitest`) 
- bumped version of `com.groupcdg:pitest-github-maven-plugin` to 0.0.8 to be in sync with the pitest version used in the pom (https://github.com/assertj/assertj-core/blob/main/pom.xml#L37)

**Comment by joel-costigliola** [comment]
It's a bit confusing to investigate as I can't pinpoint which exact github action jobs/step is performed.

The Receive workflow job is completed as far as I can tell from https://github.com/assertj/assertj-core/pull/2083/checks?check_run_id=2700972002 but I fail to identify which step is taking so much time, I assume it's in `pitest-update-pr` even though there is no log showing `pitest-update-pr` has started.

**Comment by joel-costigliola** [comment]
A bit more insight, when comparing with https://github.com/GroupCDG-Labs/pitest-github-demo/ PRs, I see that the `pitest` phase that takes forever in assertj-core takes almost no time, ex: https://github.com/GroupCDG-Labs/pitest-github-demo/pull/7/checks?check_run_id=2546195806.

It shows the Pitest mutation testing feedback results whereas the one in assertj-core are stuck there.

https://github.com/GroupCDG-Labs/pitest-github-demo/pull/7/checks?check_run_id=2546195806

**Comment by hcoles** [comment]
Hi Joel,

What I think is happening is that mutation testing is running successfully, but the job defined in https://github.com/assertj/assertj-core/blob/main/.github/workflows/pitest-updated-pr.yml is failing to complete. 

This job is starting, creating a new checkrun called 'pitest', but is then unable to update its status so it appears to have been running for hours.

This is a known bug caused by a change to the github apis last week and these two issues

https://github.com/hub4j/github-api/issues/1156
https://github.com/hub4j/github-api/issues/1157

I'm hoping there will be a release of hub4j soon to fix this.

What I don't understand is why no error log is visible. I assume this is a peculiarity of the actions workflow_run trigger.

**Comment by joel-costigliola** [comment]
Thanks @hcoles for the explanation.

**Comment by hcoles** [comment]
@joel-costigliola There is now a 0.0.9 release that should fix the issue if you update the pom and the version in the github workflow, sorry for the delay.

**Comment by joel-costigliola** [comment]
thanks @hcoles, I'll try it on the week end.

**Comment by joel-costigliola** [comment]
version bumped, let's see how it goes.

**Comment by joel-costigliola** [comment]
Looks good now: https://github.com/assertj/assertj-core/pull/2246#issuecomment-855236608
thanks again @hcoles
