### ISSUE TITLE
Allow configuring the order of assumption exception classes

### ISSUE THREAD

**Issue by ikhoon** [assertj/assertj-core#2267]
#### Problem

Our project has dependencies on both JUnit5 and TestNG. Most test cases are written by JUnit5.
`Assumptions.assumeThat()` is also used with JUnit5. TestNG is only used for running Reactive Streams TCK.
https://github.com/reactive-streams/reactive-streams-jvm/blob/899f17ffc2927bf89fad73dfde182f5018359bdf/tck/build.gradle#L19
When I tried to upgrade AssertJ from 3.17.1, our JUnit test suits failed with:
```
FlagsTest > epollAvailableOnLinux() FAILED
    org.testng.SkipException: assumption was not met due to: 
    Expecting:
      ...
```
The error seems to be caused by the change of the order of assumption exceptions in https://github.com/assertj/assertj-core/commit/cf65f6a069814abbf478b9fda47db0978e6dfa75.

#### Suggestion

It would be nice to give an option that changes the order of assumption exceptions using a property file or a JVM system property.
```
-Dorg.assertj.assumeption.exceptions=org.opentest4j.TestAbortedException,org.testng.SkipException,org.junit.AssumptionViolatedException
```

**Comment by joel-costigliola** [comment]
I'm not sure to completely understand the issue, if the assumption was not met, it does not really matter whether the assumption error is a TestNG, JUnit or opentest4j one.

Can you clarify why this test did not behave as expected?

**Comment by scordio** [comment]
If I got it correctly, AssertJ throws `org.testng.SkipException` having TestNG in the classpath, but the test engine is JUnit 5 so the exception is not recognized, causing a test failure instead of skipping it.

Is that correct @ikhoon?

**Comment by ikhoon** [comment]
> If I got it correctly, AssertJ throws `org.testng.SkipException` having TestNG in the classpath, but the test engine is JUnit 5 so the exception is not recognized, causing a test failure instead of skipping it.

Yes, exactly. Since TestNG is in the classpath, we could not use `assumeThat()` with JUnit 5 that worked with ~4.17.1.

**Comment by joel-costigliola** [comment]
dumb suggestion: is it possible to migrate everything to JUnit5?

I feel the mix of TestNG and JUnit5 is a bit of an unusual situation.

If we decide to provide selecting the assumptions exception order, it would be in https://javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/configuration/Configuration.html.

**Comment by ikhoon** [comment]
> is it possible to migrate everything to JUnit5?

Yes. It is possible, but our team ❤️ AssertJ's fluent assertions.

> I feel the mix of TestNG and JUnit5 is a bit of an unusual situation.

As I said, we have to check Reactive Streams implementations with technology compatibility kit that is out of control. 😅

> If we decide to provide selecting the assumptions exception order, it would be in javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/configuration/Configuration.html.

That sounds good to me. 👍

**Comment by joel-costigliola** [comment]
Alright, when I said migrating to JUnit5 I was really saying get rid of TestNG 😄 .

I understand now it's not possible so let's go with selecting the assumption exception to throw form the config.
