### ISSUE TITLE
2D arrays: assert size of first dimension only

### ISSUE THREAD

**Issue by bdumon** [assertj/assertj-core#2296]
#### Summary

In assertj 3.17.0, for 2D arrays like `byte[][]` the `hasSize(int)` method has been replaced by `hasDimensions(int, int)`.

It would be useful to keep the `hasSize(int)` as well. The length of the second dimension might be different for each entry, or it might simply be irrelevant to the test.

#### Example

```java
byte[][] bytes = {{1}, {1, 2}, {1, 2, 3}};
assertThat(bytes).hasDimensions(3, /* problem: second dimension is variable length */);
```

**Comment by joel-costigliola** [comment]
Yes that's true, keen to contribute it @bdumon?

**Comment by scordio** [comment]
I have the feeling `hasSize(int)` might be ambiguous with 2D arrays.

What about something more specific? Maybe `hasRowSize(int)`? (not fully happy with the "row" terminology, but it's my best proposal so far)

**Comment by bdumon** [comment]
How about allowing a wildcard value for the parameters to `hasDimensions(int, int)`, such as `-1`: `hasDimensions(3, -1)`?

Though `hasSize(int)` seems fine to me as well, and is consistent with the API for collections. It's an array after all, where each entry happens to be a reference to another array.

**Comment by joel-costigliola** [comment]
No magic/wildcard value.

I have a slight preference for `hasRowSize` over `hasSize` as it is more explicit.

**Comment by SekarMylsamy** [comment]
@joel-costigliola Created PR for this issue. Could you please review?
https://github.aexp.com/smylsamy/assrt-core/pull/1

**Comment by joel-costigliola** [comment]
@SekarMylsamy thanks, your link is brokne and I don't see your new PR in https://github.com/assertj/assertj-core/pulls

**Comment by SekarMylsamy** [comment]
My apologies, I posted broken link. Will fix and post it again.

**Comment by SekarMylsamy** [comment]
@joel-costigliola Here is the updated link : https://github.com/assertj/assertj-core/pull/2316

**Comment by scordio** [comment]
As we have now an open PR about the issue, I'd like to have one more round on the naming of this new assertion method.

As mentioned in https://github.com/assertj/assertj-core/pull/2316#discussion_r690956051, `hasRowSize` might still be ambiguous: is it the number of rows or the number of elements a single row has? The latter would be the number of columns only with a symmetric matrix.

At this point, I'd go with something more verbose like `hasNumberOfRowsEqualTo`.

**Comment by joel-costigliola** [comment]
I vote for `hasNumberOfRows` first and then `hasRowCount`

**Comment by scordio** [comment]
@bdumon @SekarMylsamy is `hasNumberOfRows` good enough for you?

**Comment by SekarMylsamy** [comment]
@scordio I am ok with `hasNumberOfRows`. If every one is aligned on the naming convention, will work on the PR to update the name along with the change suggested by you.

**Comment by scordio** [comment]
@SekarMylsamy please go ahead with `hasNumberOfRows`. Thanks a lot!

**Comment by SekarMylsamy** [comment]
Thanks @scordio for the confirmation, will work on the PR.
