### ISSUE TITLE
Question/Suggestion: Allowing to override what failure case throws in AssertJ api.

### ISSUE THREAD

**Issue by yakovbelov** [assertj/assertj-core#2305]
Dear AssertJ team,

So, in the end AssertJ throws AssertionError. And that is, I guess, to imitate Java assert feature. Junit does it too. Testing frameworks expect nothing less.

I really want to use AssertJ api in the prod code, as I think it is awesome and can help with readability and reusability of validation layer. One would think, just catch AssertionError and bob's your uncle. But that is a code smell, as you are not supposed to catch this Throwable in prod code.

It would be nice if we could leverage the plethora of validating code before AssertionError is thrown and then throw something else. I did a bit of a search for this and I don't think this is either possible at the moment in the code or anyone has asked for this before. I could be wrong on both accounts. In any case, what do you think?

I realise this probably belongs in Discussions, but before I move this item, I wanted to get an idea if I'm on to something here or barking up the wrong tree :)

**Comment by joel-costigliola** [comment]
AssertJ only throws `AssertionError` and there is no plan to throw anything else.

I think that `AssertionError` can be used production code (although it is not a prevalent usage), java actually comes with the [assert](https://docs.oracle.com/javase/7/docs/technotes/guides/language/assert.html) construct to to verify pre and post design-by-contract conditions and invariants. If an `assert` expression is not met, an `AssertionError` is thrown.

**Comment by yakovbelov** [comment]
Hi @joel-costigliola,

Thanks for the response. Makes sense. One thing I would like to make - assert failures, usually, are not caught. That means if assert fails, it is the end of the thread's execution. That is how I read it.

Anyway, your response also probably means, that AssertJ is designed to be used in test code, mainly. I would probably use AssertJ in prod code for my personal projects, but in enterprise environment an architect would object :)

Thanks for your time anyway and thanks for amazingly useable framework, that AssertJ is. Cheers!
