### ISSUE TITLE
Idea: Kotlin-specific collection-assertion helper

### ISSUE THREAD

**Issue by mbjelac** [assertj/assertj-core#2307]
Main point: I want to have a single assert per test & I don't want to bother with [soft assertions](https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/SoftAssertions.html) because reasons.

I've been using a pattern where I collect the actual values in a collection and then assert that to be equal to a collection of expected values:

```java
@Test
public void someTest() {

  Result result = doStuff();

  assertThat(List.of(result.foo, result.bar))
    .isEqualTo(List.of("Foo", "Bar"));
}
```

It's simple & short, using the standard assertion stuff & not needing to "collect" all assertions.

However, for more than 2 elements it's not very readable. I'd prefer to have expected & actual results as close as possible.

In *Kotlin* I can use the `Pair` class infix operator `to` to achieve something like this:

```kotlin
@Test
fun someTest() {

  val result = doStuff()
  
  assertEqualityOf(
    result.foo to "Foo",
    result.bar to "Bar" 
  )
}
```

This seems very nifty to me!

The magic `assertEqualityOf` helper is actually simple:

```kotlin
import org.assertj.core.api.Assertions.assertThat

fun assertEqualityOf(vararg equalities: Pair<Any, Any>) {
  assertThat(
    equalities.map { it.first }
  )
    .isEqualTo(
      equalities.map { it.second }
    )
}
```

My question is: Is it possible for me or someone else to get that Kotlin-specific helper into the AssertJ core or a module?

**Comment by joel-costigliola** [comment]
We can consider it as long as it does not involve adding dependencies, to keep assertj core easy to use we don't want it to have any depedencies.

Maybe open a draft PR for us to get an idea of the changes?

**Comment by scordio** [comment]
If I got it correctly, the helper requires the knowledge of [`Pair`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-pair/), which is a Kotlin class and would go against what Joel mentioned.

You might consider https://github.com/willowtreeapps/assertk for Kotlin specific features. Be aware that AssertK is inspired by AssertJ but it has nothing to do with it.

**Comment by mbjelac** [comment]
Thanks! Will try it out.

**Comment by joel-costigliola** [comment]
Closing this issue for now since it looks like it would need additional dependencies but @mbjelac feel free to comment on it if you need more information from us.
