### ISSUE TITLE
Add `hasNoExtension` to `Path` assertions

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2318]
#### Example

```java
assertThat(Paths.get("file")).hasNoExtension();
```

Related to #2233.

**Comment by Syemon** [comment]
Hi, can I take this one?

**Comment by vinayakkumargupta** [comment]
hey, @scordio can I fix it? I am new to open source.

**Comment by scordio** [comment]
Thanks to both of you for offering help.

As @Syemon was commenting first, I'd let him work on this one.

@vinayakkumargupta feel free to check other open issues and let us know if there is anything you would like to work on.
