### ISSUE TITLE
add singleElement() to AbstractObjectArrayAssert

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2320]
#### Summary

`singleElement()` has been added to Iterable assertions but not in `AbstractObjectArrayAssert`

**Comment by Syemon** [comment]
Hi, can I take this one?

**Comment by scordio** [comment]
Sure and thanks, @Syemon.

**Comment by joel-costigliola** [comment]
@Syemon if you don't have time to work on this one, it's not a big deal I'll take over.

**Comment by Syemon** [comment]
@joel-costigliola Thanks, I completely miscalculated how long it would take me. I got totally stuck in this task. I was not able to make it work with strongly typed assertion variant.

**Comment by joel-costigliola** [comment]
Don't worry @Syemon, thanks for the effort, we will take it from there.
