### ISSUE TITLE
Using comparator/equals for list items ignoring order

### ISSUE THREAD

**Issue by arturmkr** [assertj/assertj-core#2336]
Having following code:

```
public class Person {
   String name;
   List<MyAction> actions = new ArrayList<>();
 }
 
public class MyAction {
   String title;
   String type;
   String data;
}
 
 
 Person sherlock1 = new Person("Sherlock Holmes");
 sherlock1.actions.add(new MyAction("login", "low", "{\"age\": 30, \"car\": null, \"name\": \"John\"}"));
 sherlock1.actions.add(new MyAction("open", "high", "http://example.com"));
 
 Person sherlock2 = new Person("Sherlock Holmes");
 sherlock2.actions.add(new MyAction("open", "high", "http://example.com"));
 sherlock2.actions.add(new MyAction("login", "low", "{\"name\": \"John\", \"age\": 30, \"car\": null}"));
```

It's needed to compare `sherlock1` and `sherlock2` objects.
But the problem is with `data` field.
It could contain json and this json could be in different order.

If using `withEqualsForType` or `withComparatorForType` assert would fail:
```
    BiPredicate<MyAction, MyAction> myActionValidation = ....

    assertThat(sherlock1)
        .usingRecursiveComparison()
        .ignoringCollectionOrder()
        .ignoringExpectedNullFields()
//            .withEqualsForType(myActionValidation, MyAction.class)
//            .withComparatorForType(new MyActionComparator(), MyAction.class)
            .isEqualTo(sherlock2);
```

Because it's trying to validate `actions` elements list one by one, but not ignoring order.

So, it would compare: 
`new MyAction("login", "low", "{\"age\": 30, \"car\": null, \"name\": \"John\"}")`
with
`new MyAction("open", "high", "http://example.com")`

and:
`new MyAction("open", "high", "http://example.com")`
with
`new MyAction("login", "low", "{\"name\": \"John\", \"age\": 30, \"car\": null}")`

It would be great to have a functionality to solve this issue - having comparator/equals for list items ignoring order.

**Comment by joel-costigliola** [comment]
Thanks for reporting this, we will be looking at it shortly.

**Comment by joel-costigliola** [comment]
@arturmkr can you share `MyActionComparator` and `myActionValidation` code so that I can try to reproduce the behavior you mention?

**Comment by arturmkr** [comment]
@joel-costigliola , sorry I forgot to mention.
In `MyAction.class `variable `type` tells in which format `data` variable is initialised.

So `type` variable could either 'JSON', either 'STRING'.

For comparator, I have following code:
```
public class MyActionComparator  implements Comparator<MyAction> {
    @SneakyThrows
    @Override
    public int compare(MyAction o1, MyAction o2) {

        boolean valueCheck;
        if (o1.type().equals("JSON")) {
            JsonNode tree1 = mapper.readTree(o1.data());
            JsonNode tree2 = mapper.readTree(o2.data());
            valueCheck = tree1.equals(tree2);
        } else {
            valueCheck = Objects.equals(o1.data(), o2.data());
        }

        if (Objects.equals(o1.title(), o2.title())
                && Objects.equals(o1.type(), o2.type())
                && valueCheck) {
            return 0;
        } else return 1;
    }
}
```

For equals:
```
    BiPredicate<MyAction, MyAction> myActionValidation = (o1, o2) -> {
      boolean valueCheck;
      if (o1.type().equals("JSON")) {
        JsonNode tree1 = null;
        try {
          tree1 = mapper.readTree(o1.data());
        } catch (JsonProcessingException e) {
          e.printStackTrace();
        }
        JsonNode tree2 = null;
        try {
          tree2 = mapper.readTree(o2.data());
        } catch (JsonProcessingException e) {
          e.printStackTrace();
        }
        valueCheck = tree1.equals(tree2);
      } else {
        valueCheck = Objects.equals(o1.data(), o2.data());
      }

      return Objects.equals(o1.title(), o2.title())
              && Objects.equals(o1.type(), o2.type())
              && valueCheck;
    };
```

If it's needed, here is the full code:
https://github.com/arturmkr/assertJComparatorExample

Thanks in advance!

**Comment by joel-costigliola** [comment]
So the issue is within your comparator which only compares `MyAction.data` as JSON if `MyAction.type="JSON"`.
This is not the case in your example, as `MyAction.type="low"` `"{\"age\": 30, \"car\": null, \"name\": \"John\"}"` is compared to `"{\"name\": \"John\", \"age\": 30, \"car\": null}"` as strings which obviously are not equal. 

If you change `low` to `JSON` then the test fails with a jackson exception since it tries to parse `"http://example.com"` as json.

After modifying a bit your data I have got this test running:
```java
  @Test
  void should_pass() {
    // GIVEN
    Person sherlock1 = new Person("Sherlock Holmes");
    sherlock1.actions.add(new MyAction("login", "JSON", "{\"age\": 30, \"car\": null, \"name\": \"John\"}"));
    sherlock1.actions.add(new MyAction("open", "high", "{\"site\":\"http://example.com\"}"));

    Person sherlock2 = new Person("Sherlock Holmes");
    sherlock2.actions.add(new MyAction("open", "high", "{\"site\":\"http://example.com\"}"));
    sherlock2.actions.add(new MyAction("login", "JSON", "{\"name\": \"John\", \"age\": 30, \"car\": null}"));

    // WHEN/THEN
    assertThat(sherlock1).usingRecursiveComparison()
                         .ignoringCollectionOrder()
                         .ignoringExpectedNullFields()
                         .withComparatorForType(new MyActionComparator(), MyAction.class)
                         .isEqualTo(sherlock2);
  }
``` 

Note that I'm using type="JSON" and `data` is always a valid json

**Comment by arturmkr** [comment]
@joel-costigliola , you are right!
There is a bug in my Comparator.
Sorry for bothering.
Closing issue.

Thanks for the help.
