### ISSUE TITLE
Avoid mocks for testing `File` assertions

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2337]
Similar to #2292, all the test cases in subclasses of `FilesBaseTest` should use real filesystem elements and not mocks.

We might still favor the NIO2 File API to initialize the test prerequisites, so `actual` would be obtained via `Path::toFile`.

**Comment by ahmadsadeed** [comment]
I have been working on this issue and have a question. For a case like below or similar situations, when we expect an IOException to be thrown, should I replace such mocks with actual examples of forcing an exception? 

```
@Test
  void should_throw_exception_when_canonical_form_representation_fail_for_expected_parent() throws Exception {
    File expectedParent = mock(File.class);
    when(expectedParent.getCanonicalFile()).thenThrow(new IOException());

    assertThatExceptionOfType(UncheckedIOException.class).isThrownBy(() -> files.assertHasParent(someInfo(), actual,
                                                                                                 expectedParent));
  }
```

To:

```
@Test
  void should_throw_exception_when_canonical_form_representation_fail_for_expected_parent() throws Exception {
    File expectedParent = new File("\u0000");
    assertThatExceptionOfType(UncheckedIOException.class).isThrownBy(() -> files.assertHasParent(someInfo(), actual,
                                                                                                 expectedParent));
  }
```

I have such cases in multiple subclasses of FilesBaseTest and any suggestion will help. Thanks.

**Comment by scordio** [comment]
Thanks for working on it, @ahmadsadeed.

I think that these are test cases where using mocks would still make sense. This is also what we have for `Path` test cases:

https://github.com/assertj/assertj-core/blob/d267961e6950215cdaa855038fe4a8bd3806eb75/src/test/java/org/assertj/core/internal/paths/Paths_assertHasParent_Test.java#L67-L93

In case you'd like to bring this topic forward, I suggest raising a small PR first where only one test class is rewritten so that you can get faster feedback on the direction to follow.
