### ISSUE TITLE
Suggestion: Follow semantic versioning rules

### ISSUE THREAD

**Issue by jpfroud** [assertj/assertj-core#2339]
Upgrading from assertj-core 3.17.2 to 3.18.0 shouldn't introduce breaking changes

https://assertj.github.io/doc/#assertj-core-3-18-0-release-notes

3.18.0 should be 4.0.0?

**Comment by scordio** [comment]
AssertJ Core does not use semantic versioning (see #2148).

Fun fact: Dependabot thinks AssertJ Core has [97% of SemVer stability](https://dependabot.com/compatibility-score/?dependency-name=org.assertj:assertj-core&package-manager=maven).
