### ISSUE TITLE
Extracting BigDecimal in assumption throws IllegalArgumentException

### ISSUE THREAD

**Issue by DanPetras** [assertj/assertj-core#2349]
#### Summary
Extracting BigDecimal from assumption throws `IllegalArgumentException: Unsupported assumption creation for class org.assertj.core.api.BigDecimalAssert`.

It seems that [Assumptions.asAssumption](https://github.com/assertj/assertj-core/blob/d9299db7a0dccfc1b70b6cb0996b6a231d99dd0f/src/main/java/org/assertj/core/api/Assumptions.java#L1349) is missing something like
```java
if (assertion instanceof BigDecimalAssert) return asAssumption(BigDecimalAssert.class, BigDecimal.class, actual);
```

#### Example

```java
class Item {
  public BigDecimal getQuantity() { return BigDecimal.ONE; }
}
Item item = new Item();
// ok
assumeThat(item.getQuantity()).isEqualByComparingTo("1");

// fails with "Unsupported assumption creation for class org.assertj.core.api.BigDecimalAssert"
assumeThat(item).extracting(Item::getQuantity, InstanceOfAssertFactories.BIG_DECIMAL).isEqualByComparingTo("1")

// ok, because it is assertion not assumption
assertThat(item).extracting(Item::getQuantity, InstanceOfAssertFactories.BIG_DECIMAL).isEqualByComparingTo("1")
```
#### Version

AssertJ: 3.21.0

**Comment by scordio** [comment]
Thanks for reporting the issue, we will look into it.
