### ISSUE TITLE
Consider adding an idiom for double-equal-only comparison for Iterables.

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2365]
#### Abstract

Apologies, if this issue is not applicable or there is already an idiom.

#### Summary

Consider adding an idiom for asserting an `Iterable` has exactly the same element against other `Iterable` using only double-equal(`==`) comparison strategy.

```java
List<Integer> unsorted = IntStream.of(2, 0, 0, 3, 1) // <E extends Comparable<? super E>>
        .mapToObj(Integer::new) // just for testing the stability
        .collect(Collectors.toList());
List<Integer> sorted1 = Collections.sort(new ArrayList<>(unsorted)); // might be stable
List<Integer> sorted2 = MySort.sort(new ArrayList<>(unsorted)); // should also be stable
assertThat(sorted2)
        .isSorted()
        .isSortedAccordingTo(Comparator.naturalOrder())
        .containsExactlyElementsOf(sorted1) // nothing else in the same order
        .hasSameElementsAs(sorted1) // in any order, ignoring duplicates
        ;
```

When, say, the `MySort` produced an unstable result,

```
// assume the method produced an unstable result
Collections.swap(sorted2, 0, 1); // swap first two zeros from 0, 0, 1, 2, 3
```

I couldn't find any idiom for asserting the `actual` has exactly the same(`==`) elements against the expected.

I know I can do this.

```java
for (int i = 0; i < sorted1.size(); i++) {
    assertThat(sorted2.get(i))
            .isSameAs(sorted1.get(i));
}
``` 

#### Example

```java
// nothing else in the same order, using == comparison only
assertThat(sorted2)
        .containsExactlyTheSameElementsOf(sorted1);
```

**Comment by joel-costigliola** [comment]
Have you tried [`usingElementComparator`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#usingElementComparator(java.util.Comparator)) and passing a comparator that just checks objects are `==`?
