### ISSUE TITLE
Add `satisfiesAllOf` to `AbstractAssert`

### ISSUE THREAD

**Issue by martin-tarjanyi** [assertj/assertj-core#2374]
#### Summary
AssertJ already has support for soft assertions. However, that feature might be difficult to discover as it's not part of the main API and also a bit error-prone considering that you have to remember to call `assertAll` in the end.

`AbstractAssert` already contains a `satisfiesAnyOf` method, so this proposed method would be a nice complement to that. It would be easy to discover and would be less error-prone.

#### Example

```java
TolkienCharacter frodo = new TolkienCharacter("Frodo", HOBBIT);
    
Consumer<TolkienCharacter> isHobbit = tolkienCharacter -> assertThat(tolkienCharacter.getRace()).isEqualTo(HOBBIT);
Consumer<TolkienCharacter> isElf = tolkienCharacter -> assertThat(tolkienCharacter.getRace()).isEqualTo(ELF);
Consumer<TolkienCharacter> isFrodo = tolkienCharacter -> assertThat(tolkienCharacter.getName()).isEqualTo("Frodo");
Consumer<TolkienCharacter> isBoromir = tolkienCharacter -> assertThat(tolkienCharacter.getRace()).isEqualTo("Boromir");
    
// assertion succeeds:
assertThat(frodo).satisfiesAllOf(isHobbit, isFrodo);
    
// assertion fails reporting all failures:
assertThat(boromir).satisfiesAllOf(isElf, isBoromir);
```

If the proposal is accepted I would be happy to contribute.

**Comment by joel-costigliola** [comment]
I think what you are looking for is [allSatisfy](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#allSatisfy(java.util.function.Consumer)), it was named like this to follow the Java APi allMatch, anyMatch, ...

**Comment by martin-tarjanyi** [comment]
`allSatisfy` serves a different use case. It is part of `AbstractIterableAssert` and executes the **same assertions on all elements of an Iterable**.

`satisfiesAllOf` would be part of `AbstractAssert` and would execute **multiple assertions on the same object** in a soft manner.

**Comment by joel-costigliola** [comment]
You are right, I read your summary too quickly, my bad.

We can certainly add this, just wondering if we should just make `satisfies` to accept a vararg or go with `satisfiesAllOf`.

And thanks for wanting to contribute, I'm assigning this to you.

**Comment by joel-costigliola** [comment]
I would prefer not as the API is already quite big
