### ISSUE TITLE
MapAssert throws NPE on null key and value

### ISSUE THREAD

**Issue by parenko** [assertj/assertj-core#2379]
#### Summary
`MapAssert` throws NPE on `null` key and value, if `Map` implementation does not accept `null` values like `java.util.Map#of(*)`.
For `List` there ist a special method  `ListAssert#doesNotContainNull()`.
Maybe `MapAssert` should also have special treatment for `null` keys and values.
At least the negative verification methods shouldn't throw an exception.

#### Example

```java
assertThat(List.of("a", "b")).doesNotContainNull(); // OK

assertThat(Map.of("a", "b")).containsValue(null); // NPE
assertThat(Map.of("a", "b")).containsKey(null); // NPE

assertThat(Map.of("a", "b")).doesNotContainKey(null); // NPE
assertThat(Map.of("a", "b")).doesNotContainValue(null); // NPE
```

run with org.assertj:assertj-core:3.21.0

**Comment by BenTels** [comment]
Hello,

If it's okay with you, I would like to take a stab at this one. Can you assign it to me please?

Thanks,

Ben.

**Comment by joel-costigliola** [comment]
@BenTels happy to do that after we review the issue and how to address it.

**Comment by BenTels** [comment]
Anybody know what is up with pitest?
