### ISSUE TITLE
`catchThrowableOfType` enriched alternatives

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2397]
#### Summary
Similarly to the enriched alternatives of [`assertThatExceptionOfType`](https://assertj.github.io/doc/#assertj-core-exception-assertions-assertThatExceptionOfType), we could introduce enriched versions of `catchThrowableOfType`.

#### Example

```java
NullPointerException npe = catchNullPointerException( () -> ... );
IllegalArgumentException iae = catchIllegalArgumentException( () -> ... );
IllegalStateException ise = catchIllegalStateException( () -> ... );
IOException ioe = catchIOException( () -> ... );
```

**Comment by Spacca** [comment]
I would like to work on this one as my first contribution

**Comment by scordio** [comment]
Sure, thanks @Spacca!
