### ISSUE TITLE
flatExtracting/flatMap for iterable/array should throw a proper assertion error if any element is null

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2412]
#### Summary

Similar to  https://github.com/assertj/assertj-core/issues/2401 but for `flatExtracting`/`flatMap`.

There are quite a few variations to cover and tests;
- [ ] `flatExtracting(Function)`, `flatMap(Function) `, `flatExtracting(ThrowingExtractor)` and `flatMap(ThrowingExtractor)`, will be fixed by changing `doFlatExtracting`, tests needed for the 4 methods exposed in the API.
- [ ] `flatExtracting(Function...)`, flatExtracting(ThrowingExtractor...), `flatMap(Function...)` and `flatMap(ThrowingExtractor...)`, will be fixed by changing `flatExtractingForProxy`, tests needed for  4 methods exposed in the API.

**Comment by zihanxu3** [comment]
Hi can I take this issue? Thanks!

**Comment by joel-costigliola** [comment]
Sure, go ahead @zihanxu3! thanks!
