### ISSUE TITLE
Boxed vs unboxed arrays comparison should work

### ISSUE THREAD

**Issue by juherr** [assertj/assertj-core#2415]
#### Summary
According to #1948 boxed vs unboxed arrays comparison should work.

`assertj-3.21.0`

#### Example

```java
assertThat(new int[]{42}).isEqualTo(new Integer[]{Integer.valueOf(42)}); // should not fail
```
Result:

> expected: "[42] (Integer[]@7157f156)"
 but was: "[42] (int[]@4ee5fa6f)"

**Comment by scordio** [comment]
In #1948 I mentioned that we do not expect your example to work:

> My initial feeling is that the old behavior was violating the language design, which [supports boxing/unboxing for primitive types](https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.1.7) but not for the corresponding arrays.
> 
> Also, IntelliJ fires an [`assertEquals`() between objects of inconvertible types](https://www.jetbrains.com/help/idea/list-of-java-inspections.html#junit) warning with the example above. Indeed, `org.junit.jupiter.api.Assertions.assertEquals` fails similarly.
> 
> However, I understand the convenience of the previous behavior.
> 
> Instead of having it behind an `equals` check, my proposal would be to make it explicit adding the overloaded assertions in the `contains` family which would support boxed arrays. E.g., in `AbstractLongArrayAssert` we would add:
> 
> ```java
>   public SELF containsExactly(Long[] values) {
>     arrays.assertContainsExactly(info, actual, values);
>     return myself;
>   }
> ```
> 
> which would allow:
> 
> ```java
>   @Test
>   void testCompareArrays() {
>     long[] array1 = new long[] { 2L, 2L };
>     Long[] array2 = new Long[] { 2L, 2L };
> 
>     assertThat(array1).containsExactly(array2);
>   }
> ```

so `contains` alternatives supporting boxed arrays should be used.

**Comment by juherr** [comment]
@scordio Sorry for the misread and thank you a lot for the appropriate solution.

For the record:
```java
assertThat(new Integer[]{Integer.valueOf(42)}).containsExactly(new int[]{42});
```
won't compile as explained in https://github.com/assertj/assertj-core/issues/1948#issuecomment-707644838

An alternative is:

```java
Integer[] expected = Arrays.stream(new int[]{42}).boxed().toArray(Integer[]::new);
assertThat(new Integer[]{Integer.valueOf(42)}).containsExactly(expected);
```
