### ISSUE TITLE
Problem with Eclipse AspectJ Project

### ISSUE THREAD

**Issue by avenue68** [assertj/assertj-core#2432]
#### Summary
When I try to run a Junit5 test class in Eclipse AspectJ Project, I got the following error message on the following pop-up.
```
Launching of JUnit tests unexpectedly failed. Check log for details.
Reason: <anonymous #1> {key=Lorg/assertj/core/api/ThrowableAssert$ThrowingCallable;}[in testMethod() [in AppTest [in [Working copy] AppTest.java [in MY PROJECT...]]]] does not exist.
```
![error](https://user-images.githubusercontent.com/83228978/145398871-0bb2e03b-61fa-4005-b239-e1ff2fdf7b47.png)

Here are some information I confirmed.
- The error happens when calling assertion methods which needs ThrowableAssert$ThrowingCallable dependency like isThrownBy() method.
- Even if I don't define any Aspect class nor use AspectJ dependencies in pom.xml, the error happens in Eclipse AspectJ project.
- After re-converting to a normal maven project, the error don't happen.
- All dependencies are the latest stable version.

#### Example
The test method which will result in the error.
```java
package com.example;

import static org.assertj.core.api.Assertions.*;
import org.junit.jupiter.api.Test;

public class AppTest 
{
    @Test
    public void testMethod()
    {
    	assertThatNoException().isThrownBy(() -> System.out.println("aaaaa"));
    }
}
```

Eclipse's log
```
!ENTRY org.eclipse.jdt.junit 4 4 2021-12-09 21:29:25.147
!MESSAGE ERROR
!STACK 1
Java Model Exception: Error in Java Model (code 969): <anonymous #1> {key=Lorg/assertj/core/api/ThrowableAssert$ThrowingCallable;} [in shouldAnswerWithTrue() [in AppTest [in [Working copy] AppTest.java [in MY PROJECT...]]]] does not exist.
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:574)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:617)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:328)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:314)
	at org.eclipse.jdt.internal.core.Member.getFlags(Member.java:172)
	at org.eclipse.jdt.internal.junit.util.CoreTestSearchEngine.isAccessibleClass(CoreTestSearchEngine.java:64)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.internalIsTest(JUnit5TestFinder.java:259)
	at org.eclipse.jdt.internal.junit.launcher.JUnit5TestFinder.findTestsInContainer(JUnit5TestFinder.java:226)
	at org.eclipse.jdt.internal.junit.util.TestSearchEngine.lambda$0(TestSearchEngine.java:42)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2021-12-09 21:29:25.148
!MESSAGE <anonymous #1> {key=Lorg/assertj/core/api/ThrowableAssert$ThrowingCallable;} [in shouldAnswerWithTrue() [in AppTest [in [Working copy] AppTest.java [in MY PROJECT...]]]] does not exist.
```

**Comment by avenue68** [comment]
I noticed that I can't run test codes with [click on test source in package explorer →  Alt + Shift + X → T] 
but I can run test codes with [click following icons → run execution in history].
![icon](https://user-images.githubusercontent.com/83228978/145411593-c54f48d5-cd9a-4988-a58e-5a64d29aa67c.PNG)

So I guess this problem is cause by Eclipse or AJDT.
Should I close this issue?

**Comment by joel-costigliola** [comment]
It's likely an a project setup issue with eclipse, you can close the issue.
Our project is named AssertJ and not AspectJ btw 😆

**Comment by avenue68** [comment]
@joel-costigliola 
I couldn't identify which AssertJ or AspectJ (including AJDT) is the cause of this problem and AssertJ community seems more active than the other so I report it here.
I'm sorry and thank you for your response!😊
