### ISSUE TITLE
ClassCastException instead of ComparisonFailure when comparing Double to Integer using `usingRecursiveComparison()`

### ISSUE THREAD

**Issue by Sandared** [assertj/assertj-core#2434]
#### Summary
In my case I have two complex objects which have a "value" member variable of type "Object". When I compare two of those objects via "usingRecursiveComparison()" and one of the objects has a double value and the other an integer value, I get a ClassCastException instead of a  ComparisonFailure as expected.

#### Example
This behavior can also be reproduced via a simplified comparison: 
```java
assertThat(Double.MAX_VALUE).usingRecursiveComparison().isEqualTo(Integer.MAX_VALUE) // ClassCastException instead of expected  ComparisonFailure
```

Is this an expected/intended beahvior? Is there a workaround for more complex objects where the same field of type "Object" could have such incompatible types?

Kind regards,
Thomas

**Comment by joel-costigliola** [comment]
Hi @Sandared,

I have tried your example and it gave an introspection error:
```
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'value'.
Error when introspecting properties was :
- No getter for property 'value' in java.lang.Double 
Error when introspecting fields was :
- Unable to obtain the value of the field <'value'> from <1.7976931348623157E308>
	at org.assertj.core.util.introspection.PropertyOrFieldSupport.getSimpleValue(PropertyOrFieldSupport.java:91)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration.dualValueForField(RecursiveComparisonConfiguration.java:631)
```

Could you give us a reproducible test case?

**Comment by joel-costigliola** [comment]
If I wrap the values in a class like:
```java
  @Test
  void test() {
    MyObject actual = new MyObject(Double.MAX_VALUE);
    MyObject expected = new MyObject(Integer.MAX_VALUE);
    assertThat(actual).usingRecursiveComparison().isEqualTo(expected);
  }

  static class MyObject {
    Object value;
    MyObject(Object value) {
      this.value = value;
    }
  }
```
I get a `ClassCastException`:
```
java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Double (java.lang.Integer and java.lang.Double are in module java.base of loader 'bootstrap')
	at org.assertj.core.util.DoubleComparator.compareNonNull(DoubleComparator.java:17)
	at org.assertj.core.util.NullSafeComparator.compare(NullSafeComparator.java:25)
	at org.assertj.core.util.DoubleComparator.compare(DoubleComparator.java:17)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.propertyOrFieldValuesAreEqual(RecursiveComparisonDifferenceCalculator.java:688)
```
Since you are trying to compare doubles with integer, I think that behavior makes sense as a default behavior.

Now what you could is register your own way of comparing numbers for specific fields, this test works:
```
MyObject actual = new MyObject(Double.valueOf(Integer.MAX_VALUE));
MyObject expected = new MyObject(Integer.MAX_VALUE);
BiPredicate<Number, Number> closeEnough = (n1, n2) -> Math.abs(n1.doubleValue() - n2.doubleValue()) <= 0.5;

assertThat(actual).usingRecursiveComparison()
                  .withEqualsForFields(closeEnough, "value")
                  .isEqualTo(expected);
```

Note that at the moment, using  `withEqualsForType(closeEnough, Number.class)` instead of `withEqualsForFields(closeEnough, "value")` does not work as AssertJ selects its default `Double` comparator over `closeEnough`, whether it is the desired behavior is debatable, on one hand the `Double` comparator is an exact match for the Double value to compare but OTOH user own comparator / BiPredicate should have precedence. We still need to think what the best approach is here.

**Comment by Sandared** [comment]
Hi @joel-costigliola 

thanks for digging into this issue :)

I just verified that I got the ClassCastException also with the minimal example and I can reproduce it on GitPod where I use the following JDK:
```
openjdk 11.0.13 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```
I created a repository for that here: https://github.com/Sandared/assertj-bug-1
If you want to try it for yourself you can use this link https://gitpod.io/#https://github.com/Sandared/assertj-bug-1

I also added a testcase that more or less resembles the usecase I have in production. It is very similar to what you did with the `MyObject`. We have a "PropertyDTO" datatype that can hold virtually any value in form of an object.

Wouldn't a better number comparison be something like this?

```java
BiPredicate<Number, Number> exactly = (n1, n2) -> new BigDecimal(n1.toString()).compareTo(new BigDecimal(n2.toString())) == 0;
```

If I understand your workaround (and the current limitations regarding `withEqualsForType(closeEnough, Number.class)`) corrctly that would mean for my case that I have to do the comparison logic for that field completely customized, as the `value` field in my case could not only hold Numbers. Do I understand that correctly?

Kind regards,
Thomas

**Comment by Sandared** [comment]
I just thought about your workaround: the example in the documentation of `withEqualsForFields()` implies that I have to know the fields exactly up front, i.e., I cannot use regexes like `.*?properties` for a `properties` field that might exist on different levels of a recusive object hierarchy.
E.g., if I have a class like this:
```java
public class HierarchicalNode {
  List<HierarchicalNode> children;
  List<Property> properties;
}
```

I would have to explicitly define every nested `properties` field up front, e.g., `node.properties, node.children.properties, node.children.children.properties etc.` or am I getting this wrong?

**Comment by Sandared** [comment]
Sorry for spamming :/ 

Regarding this test case of yours: 
```java
  @Test
  void test() {
    MyObject actual = new MyObject(Double.MAX_VALUE);
    MyObject expected = new MyObject(Integer.MAX_VALUE);
    assertThat(actual).usingRecursiveComparison().isEqualTo(expected);
  }

  static class MyObject {
    Object value;
    MyObject(Object value) {
      this.value = value;
    }
  }
```

I really think, that a ClassCastException is not an expected behavior here. Actually I would just expect the assertion to fail, as those two objects are not equal. So I would expect a failing test and not a test in error. 

Given the case you have a more complex object, e.g., 
```java
@Test
  void test() {
    MyObject a = new MyObject(Double.MAX_VALUE); 
    MyObject b = new MyObject(Integer.MAX_VALUE);
    MyComplexObject actual = new MyComplexObject(a, b);
    MyComplexObject expected= new MyComplexObject(b, a);
    assertThat(actual).usingRecursiveComparison().ignoringCollectionOrderInFields("values").isEqualTo(expected);
  }

  public static class MyComplexObject {
    private List<MyObject> values;
    public MyComplexObject(MyObject a, MyObject b) {
      this.values = List.of(a,b);
    }
  }

```

Wouldn't that then sometimes lead to failing the test, although the lists are actually equal?
At least this is what I observe in my case.

Kind regards, 
Thomas

**Comment by joel-costigliola** [comment]
Thanks for the detailed case, you have a point on the `MyComplexObject` example which should have worked, `ClassCastException` should probably be reported as comparison failures instead of blowing the comparison (still need to think about it more but that looks reasonable).

**Comment by Sandared** [comment]
Hi Joel,

thanks, glad I could clarify that case :)
