### ISSUE TITLE
DefaultAssertionErrorCollector dismisses expected/actual fields during injection of line numbers

### ISSUE THREAD

**Issue by akozlova** [assertj/assertj-core#2437]
#### Summary
Given junit 5 on the classpath, `org.opentest4j.AssertionFailedError`s  in `assertAll` method are cloned to be decorated with line numbers. During `org.assertj.core.api.DefaultAssertionErrorCollector#createNewInstanceWithLineNumberInErrorMessage` expected/actual values of  assertion failures are not restored though. Thus IntelliJ is unable to display `Click to see difference` link with diff.

#### Example

```kotlin
import org.assertj.core.api.JUnitSoftAssertions
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.JUnit4
@RunWith(JUnit4::class)
class MyTest {
    @get:Rule
    val softly: JUnitSoftAssertions = JUnitSoftAssertions()
    @Test
    fun t() {
        softly.assertThat("foo").describedAs("foo == bar").isEqualTo("bar")
        softly.assertThat(42).describedAs("42 == 43").isEqualTo(43)
    }
}
```

**Comment by unix-junkie** [comment]
The corresponding issue in IntelliJ bug tracker is [IDEA-261779](https://youtrack.jetbrains.com/issue/IDEA-261779).

**Comment by joel-costigliola** [comment]
Thanks for reporting this, good catch !
