### ISSUE TITLE
isExactlyInstanceOf gives confusing error message when instance is an anonymous inner class

### ISSUE THREAD

**Issue by hjohn** [assertj/assertj-core#2444]
#### Summary

When using isExactlyInstanceOf and the actual value is an anonymous inner class, the message is confusing as it claims that the actual value is an "instance of null".

#### Example

```java
    assertThat(x.red).isNotNull().isExactlyInstanceOf(A.class);
```
Will not fail `isNotNull` but fails on `isExactlyInstanceOf` with:
```
java.lang.AssertionError: 
Expecting:
 <hs.ddif.core.inject.store.BindingProvider$ProviderBinding$1@4f1bfe23>
to be exactly an instance of:
 <hs.ddif.core.InjectorProviderTest.A>
but was an instance of:
 <null>
```
This led me to believe the value in `x.red` is `null`, but it clearly isn't.

If it is not possible to detect the anonymous inner class type here  (it in this case is an anonymous implementation of the interface `Provider`) perhaps change the message to `but was an instance of an anonymous class`.

**Comment by scordio** [comment]
Thanks for reporting it, @hjohn. We'll look into it.

A small reproducible example would be:

```java
Object actual = new Object() {};
assertThat(actual).isNotNull().isExactlyInstanceOf(Object.class);
```

which yields:

```
java.lang.AssertionError: 
Expecting actual:
  org.example.MyTest$1@37eeec90
to be exactly an instance of:
  java.lang.Object
but was an instance of:
  null
```

**Comment by scordio** [comment]
@hjohn the error messages are now the following:

**Anonymous class**

```java
Object actual = new Object() {};
assertThat(actual).isExactlyInstanceOf(Object.class);
```

```
java.lang.AssertionError: 
Expecting actual:
  org.example.MyTest$1@32fe9d0a
to be exactly an instance of:
  java.lang.Object
but was an instance of:
  anonymous class
```
**Local class**

```java
class MyClass {}
MyClass actual = new MyClass();
assertThat(actual).isExactlyInstanceOf(Object.class);
```

```
java.lang.AssertionError: 
Expecting actual:
  org.example.MyTest$1@32fe9d0a
to be exactly an instance of:
  java.lang.Object
but was an instance of:
  local class MyClass
```

**Comment by hjohn** [comment]
Thank you very much! :)
