### ISSUE TITLE
Add `startsWithIgnoringCase` and `endsWithIgnoringCase` to AbstractCharSequenceAssert

### ISSUE THREAD

**Issue by bbogason** [assertj/assertj-core#2449]
#### Summary
While migrating assertions from Hamcrest to AssertJ I noticed there was no AssertJ equivalent to Hamcrest's `org.hamcrest.Matchers#startsWithIgnoringCase` and `org.hamcrest.Matchers#endsWithIgnoringCase`. However, AssertJ does provide `org.assertj.core.api.AbstractCharSequenceAssert#containsIgnoringCase` which is equivalent to Hamcrest's `org.hamcrest.Matchers#containsStringIgnoringCase`, so there is precedence in providing "ignoringCase" alternatives.

#### Example

```java
// assertion will pass
assertThat("Gandalf the grey").startsWithIgnoringCase("Gandalf");
assertThat("Gandalf the grey").startsWithIgnoringCase("gandalf");

//assertions will fail
assertThat("Gandalf the grey").startsWithIgnoringCase("grey");
```

and

```java
// assertion will pass
assertThat("Gandalf the grey").endsWithIgnoringCase("grey");
assertThat("Gandalf the grey").endsWithIgnoringCase("Grey");

//assertions will fail
assertThat("Gandalf the grey").endsWithIgnoringCase("Gandalf");
```

If you agree that this would be a reasonable addition to the API, I would be happy to take first stab at implementing this.

**Comment by scordio** [comment]
The proposal looks good to me. Thanks for offering help, @bbogason!

**Comment by bbogason** [comment]
Also added `doesNotStartWithIgnoringCase` and `doesNotEndWithIgnoringCase` assertions.

**Comment by joel-costigliola** [comment]
closed by https://github.com/assertj/assertj-core/commit/0ffde17f9e0e513b0240cef6be3b4c03856799e7
