### ISSUE TITLE
Illegal reflective access operation with recursive comparison and `ReentrantReadWriteLock`

### ISSUE THREAD

**Issue by Meijuh** [assertj/assertj-core#2450]
#### Summary
With assertj version 3.21.0 and Java 11, an illegal reflective access operation warning is raised, the full warning is as follows.

#### Example

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.assertj.core.util.introspection.FieldUtils (file:/home/meijer/.gradle/caches/modules-2/files-2.1/org.assertj/assertj-core/3.21.0/27a14d6d22c4e3d58f799fb2a5ca8eaf53e6942a/assertj-core-3.21.0.jar) to field java.util.concurrent.locks.ReentrantReadWriteLock.writerLock
WARNING: Please consider reporting this to the maintainers of org.assertj.core.util.introspection.FieldUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by scordio** [comment]
Could you please share an example that triggers the warning?

**Comment by Meijuh** [comment]
The code base is quite large; is there any strategy to pinpoint what could trigger the warning? Could it be related to such a reentrant lock?

**Comment by scordio** [comment]
> The code base is quite large; is there any strategy to pinpoint what could trigger the warning?

Common triggers of reflection operations are for example `extracting` methods and recursive comparison.


> Could it be related to such a reentrant lock?

Yes, I'd assume that AssertJ tries to use reflection to access `writerLock`. Based on the actual usage, we can evaluate if and how this can be avoided.

**Comment by Meijuh** [comment]
The following code snippet triggers the warning.
```
import static org.assertj.core.api.Assertions.assertThat;

import java.util.concurrent.locks.ReadWriteLock;
import java.util.concurrent.locks.ReentrantReadWriteLock;
import org.junit.jupiter.api.Test;

class LockTest {

    ReadWriteLock lock1 = new ReentrantReadWriteLock();

    ReadWriteLock lock2 = new ReentrantReadWriteLock();

    @Test
    void test() {
        assertThat(lock1).usingRecursiveComparison().isEqualTo(lock2);
    }
}
```
I was unable (yet) to pinpoint the case in my code base using `-Dorg.gradle.jvmargs="--illegal-access=deny"`, as this does not give me a stacktrace. Would it be useful to have such a stracktrace? Any ideas how to trigger the stacktrace?

**Comment by Meijuh** [comment]
In the meantime I found the practical cause. The following test triggers the warning also:
```
package com.example.demo;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.springframework.http.client.HttpComponentsClientHttpRequestFactory;

class LockTest2 {

    final HttpComponentsClientHttpRequestFactory clientHttpRequestFactory1 =
            new HttpComponentsClientHttpRequestFactory();

    final HttpComponentsClientHttpRequestFactory clientHttpRequestFactory2 =
            new HttpComponentsClientHttpRequestFactory();


    @Test
    void test() {
        assertThat(clientHttpRequestFactory1)
                .usingRecursiveComparison()
                .isEqualTo(clientHttpRequestFactory2);
    }
}
```
You will need to have the following `build.gradle`:
```
plugins {
	id 'org.springframework.boot' version '2.6.2'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'

	testImplementation 'org.apache.httpcomponents:httpclient:4.5.13'
}

test {
	useJUnitPlatform()
}
```

**Comment by scordio** [comment]
The fix would be adding a custom comparison similar to
https://github.com/assertj/assertj-core/blob/7a68105826e00188f6821f7daca28dd86538a8aa/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java#L530-L548

However, we should decide how to compare `ReadWriteLock` instances and if we want to focus only on `ReentrantReadWriteLock` to address the current use case. Even if we decide to go with `ReentrantReadWriteLock` only, we should define how the comparison should work as no `equals` implementation is available.

**Comment by scordio** [comment]
@Meijuh what is your expectation when comparing two instances of `ReentrantReadWriteLock`?

We are evaluating the usage of `equals` by default for all the JDK types. Assuming we do it, the recursive comparison from your example would fail as `ReentrantReadWriteLock` doesn't override `equals`.

Is that the outcome you would expect, i.e., failing assertion without warnings?

**Comment by scordio** [comment]
The warning issue has been addressed in 7406133f21ed66e3908a50c581ad0f0aaf059aa6.

**Comment by Meijuh** [comment]
@scordio I see you chose to fix it by using `equals`. Is this a backwards compatible change though? If I understand the fix in https://github.com/assertj/assertj-core/commit/7406133f21ed66e3908a50c581ad0f0aaf059aa6 correctly, then wouldn't the test in https://github.com/assertj/assertj-core/issues/2450#issuecomment-1000498743 fail? That might not be a big problem, but if this is the case I do not think you can release it in version 3.23.0? You would require a major version bump.

As an alternative you could also choose to skip comparison of objects in certain modules?

**Comment by scordio** [comment]
@Meijuh it's indeed a breaking change.

We've taken the decision in the team not to introduce smart comparisons if the JDK is not doing them (i.e., `equals` is not overridden). We could enhance it in the future when a concrete use case arises.

About versioning, minor version upgrades can deliver breaking changes, more at #2148.
