### ISSUE TITLE
Additional `assertThat...Exception` and `then...Exception` alternatives

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2454]
#### Summary

#2410 added some `catchThrowable` alternatives:
* `catchException`
* `catchIndexOutOfBoundsException`
* `catchReflectiveOperationException`
* `catchRuntimeException`

These do not have the corresponding `Assertions.assertThat...Exception`, `WithAssertions.assertThat...Exception` and `BDDAssertions.then...Exception` static methods.

We should add them and create a sync test between the three classes.

**Comment by nannany** [comment]
Could you assign this issue to me as my first contribution?

**Comment by scordio** [comment]
Sure and thanks, @nannany!
