### ISSUE TITLE
usingRecursiveComparison with usingOverriddenEquals ignores equals method of the compared object

### ISSUE THREAD

**Issue by xbif** [assertj/assertj-core#2479]
#### Summary
Version 3.22.0
I expect if I use usingRecursiveComparison with usingOverriddenEquals, field "age" should be ignored.
But as result I get

> java.lang.AssertionError: 
> Expecting actual:
>   com.ComparatorDevices$Person@63be0d6
> to be equal to:
>   com.ComparatorDevices$Person@63be0b6
> when recursively comparing field by field, but found the following difference:
> 
> field/property 'age' differ:
> - actual value  : "22"
> - expected value: "11"
> 
> The recursive comparison was performed with this configuration:
> - overridden equals methods were used in the comparison
> - these types were compared with the following comparators:
>   - java.lang.Double -> DoubleComparator[precision=1.0E-15]
>   - java.lang.Float -> FloatComparator[precision=1.0E-6]
>   - java.nio.file.Path -> lexicographic comparator (Path natural order)
> - actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).

#### Example

```java
class Person {
        String name;
        String age;

        public Person(String name, String age) {
            this.name = name;
            this.age = age;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Person person = (Person) o;
            return Objects.equals(name, person.name);
        }

        @Override
        public int hashCode() {
            return Objects.hash(name, age);
        }
    }

@Test()
    public void personTest() {
        Person expectedPerson = new Person("name", "11");
        Person actualPerson = new Person("name", "22");
        Assertions.assertThat(actualPerson)
                .usingRecursiveComparison()
                .usingOverriddenEquals()
                .isEqualTo(expectedPerson);
    }

    
```

**Comment by scordio** [comment]
Thanks for reporting it, @xbif. We'll look into it.

**Comment by JanUrb** [comment]
Hey, is this something I could work one as a newcomer?

**Comment by joel-costigliola** [comment]
@JanUrb thanks for the offer, the recursive comparison is a bit tricky so I would not recommend it as a first issue to work on.
We usually label issues that newcomers can pick with "Good first issue", have a look if there is one you'd like to contribute

**Comment by JanUrb** [comment]
Hey @joel-costigliola, 
Thanks for the advice. I will take a look at those issues. Maybe my initial analysis is of some use for you. It seems like `usingOverriddenEquals` ignores an overridden `equals` method of the root but respects  `equals` when comparing leaf objects. 
I wrote this test to make the behaviour repeatable:
```java
class RecursiveComparisonAssert_isEqualTo_usingOverriddenEquals_Test {

  public static class PersonWithOverriddenEquals {
    String name;
    String color;
    Pet pet;

    public PersonWithOverriddenEquals(String name, String color, Pet pet) {
      this.name = name; // only name is used in equals
      this.color = color;
      this.pet = pet;
    }

    @Override
    public boolean equals(Object o) {
      PersonWithOverriddenEquals person = (PersonWithOverriddenEquals) o;
      return Objects.equals(name, person.name);
    }

    @Override
    public int hashCode() {
      return Objects.hash(name, color);
    }

    @Override
    public String toString() {
      return String.format("Person [name=%s, color=%s]", name, color);
    }
  }

  public static class Pet {
    String name;
    String type; // only type is used in equals

    public Pet(String name, String type) {
      this.name = name;
      this.type = type;
    }

    @Override
    public boolean equals(Object o) {
      Pet pet = (Pet) o;
      return type.equals(pet.type);
    }

    @Override
    public int hashCode() {
      return Objects.hash(type);
    }
  }

  
  @ParameterizedTest(name = "{2}: actual={0} / expected={1}")
  @MethodSource("comparison_uses_overriden_equals")
  void should_pass_when_comparison_using_overriden_equals(Object actual, Object expected) {
    assertThat(actual).usingRecursiveComparison()
                      .usingOverriddenEquals()
                      .isEqualTo(expected);
  }

  private static Stream<Arguments> comparison_uses_overriden_equals() {
    // expected behaviour: PersonWithOverriddenEquals has an overridden equals method that only compares the field name. Therefore the following objects
    // should be the same.
    // actual behaviour: All fields of PersonWithOverriddenEquals are compared. However, the overridden equals method of Pet is respected.
    PersonWithOverriddenEquals person1 = new PersonWithOverriddenEquals("John", "green", new Pet("Ducky", "Duck"));
    PersonWithOverriddenEquals person2 = new PersonWithOverriddenEquals("John", "blue", new Pet("Mia", "Duck"));
    return Stream.of(arguments(person1, person2));
  }
}

```

**Comment by uc4w6c** [comment]
I'm sorry.
I was also starting to work.
I made it in the draft version, but I had some concerns, so let me ask you a question.

@joel-costigliola 
I have confirmed that the commit "1f8a43e6fa" has been changed so that the equals method is not used in the case of root object.
Is there anything wrong with my fix?

@JanUrb 
Once the above problem is resolved, you can use my pull request to change it.
In that case I will close my pull request.

thank you.

**Comment by joel-costigliola** [comment]
thanks for the analysis and the test case @JanUrb! :)

**Comment by joel-costigliola** [comment]
So it looks like the issue only occurs when comparing root object and `usingOverriddenEquals`, although this is a bug there is no point of using the recursive comparison combined with `usingOverriddenEquals` on the root object, better in this case to simply use `isEqualTo` which will perform the same assertion but will give a better error message (one that IDE can show visual diff):
```java
assertThat(actual).isEqualTo(expected);
```

**Comment by uc4w6c** [comment]
Thank you for letting me know.
You're right.
I will close the pull request.

**Comment by joel-costigliola** [comment]
Leave it open @uc4w6c, I'm looking at it and it might be that we don't need `isRootObject` anymore (which you have removed in your PR). I'll see if I can confirm that and if I do I'll integrate your PR and you'll get the credit for fixing this one :) (usually I get the PR code, play with it, refactor it if needed, squash all commits but keep the original PR author)

**Comment by uc4w6c** [comment]
@joel-costigliola 
Thank you :)
