### ISSUE TITLE
Provide `Comparable` assertions for `URI`

### ISSUE THREAD

**Issue by t1** [assertj/assertj-core#2487]
#### Summary

`java.net.URI` is a `Comparable`, so `AbstractUriAssert` should extend `AbstractComparableAssert`.

I assume this to be a minor, non-breaking change. I'd do a PR, but the overhead seems to be too big in my eyes.

Note: `java.net.URL` is _not_ comparable.

**Comment by scordio** [comment]
Sounds very reasonable to me.

What kind of overhead do you see?

I'd expect test classes to be added for all the methods exposed by `AbstractComparableAssert`, but they should be trivial like:

https://github.com/assertj/assertj-core/blob/517c9c6fca738cb4d088f125ae5186a3a1e4efac/src/test/java/org/assertj/core/api/long_/LongAssert_isLessThan_long_Test.java#L26-L37

**Comment by t1** [comment]
I'd have to clone the project, create a branch, install the Eclipse-Formatting-Plugin, etc. etc. pp. ... that kind of overhead ;-)

**Comment by scordio** [comment]
Got it and I am happy to help get you onboarded. What you mentioned is sort of prerequisite for any contributions 🙂

**Comment by t1** [comment]
Thanks for the offer. I know how to do all of that. I'll be happy to do this when I have something more substantial to add.

**Comment by pbacz** [comment]
I can work on this.

**Comment by pbacz** [comment]
> I'd expect test classes to be added for all the methods exposed by `AbstractComparableAssert`, but they should be trivial like

Hi, as for test cases, methods of `AbstractComparableAssert` are already tested in `org.assertj.core.api.comparable.AbstractComparableAssert_*_Test`, so I don't think there is a need to repeat those.

Your example of `LongAssert_isLessThan_long_Test` is quite different as it tests `isLessThan(long)` which is not defined in `AbstractComparableAssert` (it comes from `AbstractLongAssert`).

**Comment by scordio** [comment]
@pbacz you're right, I overlooked both points. Thanks for the PR!
