### ISSUE TITLE
assertIsNotEmpty manipulates stream position

### ISSUE THREAD

**Issue by pohly05** [assertj/assertj-core#2490]
#### Summary
If you use asserThat(inputStream).isNotEmpty() the internal pos attribute is increased by one.
This is a bit confusing cause you don't expect that. In our case a file is created after the assert and we spent a lot of time to find the reason. 

#### Example

```java
               File anyFile= new File("src/main/resources/sample.html");
               InputStream html= new FileInputStream(anyfile);
               // After next line html.pos is increased by 1
		assertThat(html).isNotEmpty();
		ClassPathResource printRes = new ClassPathResource("anypath");
		String path= printRes.getFile().getAbsolutePath() + "/" + name;
		File targetFile = new File(path);
		byte[] buffer = new byte[stream.available()];
		stream.read(buffer);
		OutputStream outStream = new FileOutputStream(targetFile);
		outStream.write(buffer);
		outStream.close();
```

**Comment by scordio** [comment]
We could prevent this with `mark` / `reset` if the `InputStream` implementation supports them, but this wouldn't work for `FileInputStream`.

Is there a reason why `File` assertions are not used? E.g.:

```java
File anyFile= new File("src/main/resources/sample.html");
assertThat(anyFile).isNotEmpty();
```

**Comment by nith2001** [comment]
Is this still an issue? Couldn't tell from @scordio 's response whether or not this needed fixing.

**Comment by scordio** [comment]
I don't see any way to fix the issue for `FileInputStream` as it doesn't support `mark` / `reset`. However, I raised #2596 to improve other use cases.

The suggested way to fix the original example is to use `File` assertions.
