### ISSUE TITLE
assertThat((Comparable) obj) not working

### ISSUE THREAD

**Issue by rala72** [assertj/assertj-core#2504]
I have a class _(`PowerClass` in examples below)_ which is `Iterable` and `Comparable`.
I was trying to test it with something similar like the example below.

```java
// assertThat(new PowerClass()).isEqualTo(new PowerClass()); // Ambiguous method call.
assertThat((Object) new PowerClass()).isEqualTo(new PowerClass()); // does not look nice
assertThatObject((Object) new PowerClass()).isEqualTo(new PowerClass()); // better way of line above
assertThat((Iterable<PowerClass>) new PowerClass()).contains(new PowerClass()); // looks not nice but works
// assertThat((Comparable<PowerClass>) new PowerClass()).isGreaterThan(new PowerClass()); // counts as Object not Comparable
```

It works only like expected if the class is only `Iterable` and no cast is present.

```java
assertThat(new PowerClass()).isGreaterThan(new PowerClass());
```

It would be nice if the cast would work, and to prevent ambiguous method calls to have own `assertThat` calls for `Iterable` and `Comparable` like `assertThatObject`. (ref. #1388)
The other solution would be to call the `GenericComparableAssert` constructor on our own (or create a method for that).

_This may also affect other interfaces (like `Throwable`?)._

**Comment by joel-costigliola** [comment]
Since your class is both `Iterable` and `Comparable`, there is no way for java or AssertJ to know whether to use `assertThat(Comparable)` or `assertThat(Iterable)`.
What we could do is introduce `assertThatComparable` to force returning `Comparable` assertions.

In the meantime you can add factory utility methods like `assertThatComparable` or `assertThatIterable` in your codebase.

**Comment by rala72** [comment]
Sorry, maybe it was not clear enough.
Yes, please add these methods and make it possible to cast it to `Comparable` as argument if possible like `Iterable`.

**Comment by kriegfrj** [comment]
> *This may also affect other interfaces (like Throwable?).*

Well, `Throwable` is not an interface - but yes, as I discovered yesterday, this is a generic problem that affects classes that implement more than one interface. I had an object that implemented both `Predicate` and `Comparable` and had the same problem (couldn't get `assertThat()` to resolve the method without a cast to `(Predicate<String>)`). 

I think it would be nice if we had a more generic approach to this problem. One possibility is to do what osgi-test has done and add the static `assertThat()` entry point to each individual assertion type. So in this case you could type ComparableAssert.assertThat(object) to get your `ComparableAssert` instance. Of course, you could just call `new ComparableAssert()` directly, but it's not the most fluent API.

On this point, I also noticed that `AssertionsForInterfaceTypes` inherits from `AssertionsForClassTypes`. Is this necessary? There doesn't seem to be a need for `AssertionsForInterfaceTypes` to inherit from `AssertionsForClassTypes` - if people want a single entry point containing both, they can simply use `Assertions`. On the other hand, I fear that this inheritance exacerbates the ambiguity problem by creating additional possibilities for ambiguity when invoking `AssertionsForInterfaceTypes.assertThat()`.

(As an aside, I also think the compiler could also be more helpful here by telling you which are the candidate methods that can't be disambiguated.)

**Comment by joel-costigliola** [comment]
Let's see if we can address that issue with `AssertionsForInterfaceTypes` not inheriting `AssertionsForClassTypes` and use it for disambiguate imports.
We can certainly add `ComparableAssert.assertThat` as another way of addressing the issue too.

**Comment by kriegfrj** [comment]
> Let's see if we can address that issue with `AssertionsForInterfaceTypes` not inheriting `AssertionsForClassTypes` and use it for disambiguate imports.

This will help in some cases, however I don't believe it would help in my case or in the case of the OP.

My class implemented two interfaces (`Comparable` as well as `Predicate`), so it still would have two ambiguously matching methods in `AssertionsForInterfaceTypes`.

I believe the case in the OP will suffer from the same problem as it also implements two interfaces (`Comparable` and `Iterable`).

>We can certainly add `ComparableAssert.assertThat` as another way of addressing the issue too.

If this is the best that we can come up with, I'm all for it. Would probably only need to be done for interface assertions.

**Comment by joel-costigliola** [comment]
I think adding `assertThat` for each interface type and use `AssertionsForClassTypes` should address the issue, note that one will not be able to static import every potentially ambiguous `assertThat` as shown in the test below:
```java
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;
import static org.assertj.core.api.PredicateAssert.assertThat;

import java.util.function.Predicate;

import org.junit.jupiter.api.Test;

class Assertions_solving_assertThat_ambiguous_Test {

  @Test
  void should_resolve_ambiguous_assertThat_for_interfaces_and_use_assertThat_for_classes() {
    // GIVEN
    ComparablePredicate<String> comparablePredicate = new ComparablePredicate<>();
    // WHEN/THEN
    // can't static import both PredicateAssert.assertThat and GenericComparableAssert.assertThat 
    assertThat(comparablePredicate).isNotNull();
    GenericComparableAssert.assertThat(comparablePredicate).isNotNull();
    // can use assertThat for classes without issue
    assertThat("").isEmpty();
    assertThat(2L).isPositive();
  }

  static class ComparablePredicate<T> implements Comparable<T>, Predicate<T> {

    @Override
    public boolean test(T t) {
      return false;
    }

    @Override
    public int compareTo(T o) {
      return 0;
    }

  }
}
```

**Comment by rala72** [comment]
> note that one will not be able to static import every potentially ambiguous `assertThat`

what about the first suggestion of adding `assert[InterfaceName]`?
these methods don't have to be added in `AssertionsForClassTypes` / `AssertionsForInterfaceTypes` if you want to prevent it from having too many methods;
it is also fine in each Interface implementation like `GenericComparableAssert`
like that, we can still import the methods statically
_(you can do these also additionally to the other plan you presented above)_

**Comment by joel-costigliola** [comment]
good idea having `assertThat[InterfaceName]` in `[InterfaceName]Assert`, no ambiguity possible.

**Comment by kriegfrj** [comment]
I think I'm warming to the idea of assertThat<interfacename>. This could be in addition to assertThat(InterfaceName), so you still have the convenience of assertThat but the fallback of assertThatInterfaceName if you hit an ambiguity. 

Under this scheme, all entry points could go in AssertionsForInterfaceTypes. They could optionally go in the assertion types too but it would not be necessary.

**Comment by joel-costigliola** [comment]
pros and cons of having `assertThat[InterfaceName]` in `AssertionsForInterfaceTypes`:
* pros: easy to discover
* cons: quite a lot of new methods in `AssertionsForInterfaceTypes` and co (`BDDAssertions`, `WithAssertions`, ...)

pros and cons of having `assertThat[InterfaceName]` in `[InterfaceName]Assert` is basically the opposite.

maybe we can find a middle ground where we would add `assertThat[InterfaceName]` in `AssertionsForInterfaceTypes` for commonly implemented interfaces like `Comparable`. 

We'll discuss it with the team before moving forward.

**Comment by kriegfrj** [comment]
The main con could be overcome if the assertion entry point methods could be generated automatically...

**Comment by joel-costigliola** [comment]
I was more talking about that code completion discovery ;-)
