### ISSUE TITLE
Add AbstractStringAssert#asInstanceOf(Class<? extends Number>, ...)

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2509]
#### Summary

Please forgive me If this issue is already fulfilled or not appropriate.

I just faced a situation that I need to assert an actual of `String` against an expected of `int`.

```java
String actual = calculate();
int expected = 1;
assertThat(actual).isNotNull().satisfies(v -> {
    assertThat(Integer.parseInt(v)).isEqualsTo(expected);
});
assertThat(actual).isNotNull()
        .asInstanceOf(new InstanceOfAssertFactory<>(String.class, v -> assertThat(Integer.parseInt(v))))
        .isEqualTo(expected);
```

#### Example

Do I have an already existing handy idiom or do I have any chance to get following one?

```java
String actual = calculate();
int expected = 1;
assertThat(actual).parsesAsInt().isEqualsTo(expected);
 // <N extends Number, A extends NumberAssert<?, N>> A asInstanceOf(Class<N>, Class<A>)
assertThat(actual)
        .asInstanceOf(Integer.class, AbstractIntegerAssert.class)
        .isEqualTo(expected);
 // AbstractIntegerAssert<?> asInstanceOfIntegerAssert()
assertThat(actual)
        .asInstanceOfIntegerAssert()
        .isEqualTo(expected);
```

Thanks.

**Comment by scordio** [comment]
I don't think `asInstanceOf` is a good fit for your target.

Probably a combination of [`assertThatObject`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Assertions.html#assertThatObject(T)) and [`extracting(Function)`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function)) is more readable:

```java
assertThatObject(actual)
  .isNotNull() // will be done implicitly in `extracting` with 3.23.0
  .extracting(Integer::parseInt)
  .isEqualTo(expected);
```

We could think about adding transformation methods to `AbstractStringAssert` as shortcuts for `extracting` use cases, like:
* `asInteger()` as shortcut for `.extracting(Integer::parseInt, InstanceOfAssertFactories.INTEGER)`
* `asLong()` as shortcut for `.extracting(Long::parseLong, InstanceOfAssertFactories.LONG)`
and so on.
