### ISSUE TITLE
FileAssert_content_Test#should_return_StringAssert_on_path_content() fails

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2522]
#### Summary

At the end the method calls StandardComparisonStrategy#areEqual with `actual\n` and `actual\r\n`.

Windows/Temurin-11

#### Example

```text
this = {StandardComparisonStrategy@3863} 
actual = "actual\n"
 value = {byte[7]@3866} [97, 99, 116, 117, 97, 108, 10]
 coder = 0
 hash = 0
other = "actual\r\n"
 value = {byte[8]@3865} [97, 99, 116, 117, 97, 108, 13, 10]
 coder = 0
 hash = 0
actualClass = {Class@596} "class java.lang.String"
```

**Comment by onacit** [comment]
Do we have any chance the problem is from git line ending?

**Comment by onacit** [comment]
Seems not reproducible with macOS.

**Comment by onacit** [comment]
I'm mentioning @joel-costigliola based on the committer, regards.

**Comment by joel-costigliola** [comment]
I don't have windows, working with linux.

**Comment by epeee** [comment]
I will try to reproduce it on Windows.

**Comment by epeee** [comment]
The test mentioned is passing on my windows machine (Windows 10).

**Comment by onacit** [comment]
Maybe something's wrong with my environment.
