### ISSUE TITLE
Add assumptions methods to be in sync with assertions methods

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2531]
#### Summary

Sync `assertThatXxx` methods with assumptions `assumeThatXxx`.

#### Missing ones

* `assumeThatCollection`
* `assumeThatIterable`
* `assumeThatIterator`
* `assumeThatList`
* `assumeThatPath`
* `assumeThatPredicate`
* `assumeThatStream`
* `assumeThatExceptionOfType`
* `assumeThatException`
* `assumeThatRuntimeException`
* `assumeThatNullPointerException`
* `assumeThatIllegalArgumentException`
* `assumeThatIOException`
* `assumeThatIndexOutOfBoundsException`
* `assumeThatReflectiveOperationException"`

Refactor `Assertions_sync_with_BDDAssumptions_Test` to be parameterized as `Assertions_sync_with_BDDAssertions_WithAssertions_and_soft_assertions_variants_Test`.

Don't add `assertThatComparable` it is going to be done as part of another ongoing issue.

**Comment by HDreamer2** [comment]
@joel-costigliola Hi, I am interested in this. Would you like to assign this to me?

**Comment by joel-costigliola** [comment]
Sure, go ahead @HDreamer2

**Comment by joel-costigliola** [comment]
@HDreamer2 are you working on this?

**Comment by HDreamer2** [comment]
@joel-costigliola Yes, I’ve done some work but I'm a little busy last two weeks and I'm really sorry for that. I was working on this just now and I'll finish this soon.

**Comment by HDreamer2** [comment]
@joel-costigliola Yes, I’ve done some work but I'm a little busy last two weeks and I'm really sorry for that. I was working on this just now and I'll finish this soon.

**Comment by HDreamer2** [comment]
@joel-costigliola Yes, I’ve done some work but I'm a little busy last two weeks and I'm really sorry for that. I was working on this just now and I'll finish this soon.

**Comment by HDreamer2** [comment]
@joel-costigliola Hi, I'm confused about the second requirement(refactoring). Does it mean I need to create a new test class named `Assertions_sync_with_BDDAssumptions_WithAssertions_and_soft_assertions_variants_Test` as it describes?

**Comment by joel-costigliola** [comment]
thanks @HDreamer2.
you need to change `Assertions_sync_with_BDDAssumptions_Test` so that it has a parameterized tests as we did in `Assertions_sync_with_BDDAssumptions_WithAssertions_and_soft_assertions_variants_Test`, hope it's clearer.

**Comment by HDreamer2** [comment]
@joel-costigliola Thanks, it's quite clearer and I've done most of the work including refactoring. But I still have some questions like the implementation of `assumeThatException`. Since there is no method like `assertThatExceptionOfType` whose argument is exceptionType, I tried to call `assumeThat(new Exception())` whose declaration is `public static <T extends Throwable> AbstractThrowableAssert<?, T> assumeThat(T actual)`. Is that a kind of reasonable implementation?

**Comment by joel-costigliola** [comment]
@HDreamer2 I think it would be nice to add `assumeThatExceptionOfType` and use it in the implementation of `assumeThatException`, `assumeThatRuntimeException` etc ...

**Comment by joel-costigliola** [comment]
I updated the issue description to make it clearer that we want to add `assumeThatXxx` methods in sync with `assertThatXxx`

**Comment by HDreamer2** [comment]
@joel-costigliola Thanks, the description confused me in the very beginning and the advice sounds great.

**Comment by HDreamer2** [comment]
@joel-costigliola Hi, I've done the whole work. Should I write extra tests or make a PR now? This is my first contribution so I have no idea whether it is enough.

**Comment by scordio** [comment]
@HDreamer2 feel free to raise a PR! In case tests are missing, we'll give you feedback during the review.
