### ISSUE TITLE
Float/Double precision bugs about assertion within the certain range

### ISSUE THREAD

**Issue by YeeTone** [assertj/assertj-core#2537]
#### Summary
Considering the following 2 cases, they both try to assert double values is equal to expected in the certain range. But these two assertions have different behaviours. It should be a serious bug, and hope the team can look at it. 

#### Example

```java
assertThat(0.125f).isEqualTo(0.5f, within(0.375f)); // pass!
assertThat(1.1f).isEqualTo(1.0f, within(0.1f)); // fail!
```

For the second assertion, the running result is:
```
java.lang.AssertionError: 
Expecting actual:
  1.1f
to be close to:
  1.0f
by less than 0.1f but difference was 0.100000024f.
(a difference of exactly 0.1f being considered valid)
```

**Comment by joel-costigliola** [comment]
Although it's not intuitive the issue is related to floating value arithmetic that is not purely mathematical in computer science.
It turns out that `1.1f - 1.0f` equals `0.100000024` and not `0.1` which makes the assertion to fail.

see https://stackoverflow.com/questions/322749/retain-precision-with-double-in-java for an explanation.

**Comment by YeeTone** [comment]
Ya. I know this is the problem of arithmetic float/double calculation in computers. Actually, if we can fix this problem and provide more precise comparison in this project, our assertion framework will be more user-friendly, since they will suffer less from the precision problem.

**Comment by YeeTone** [comment]
And the solution for fixing this precision problem is using the combination of BigDecimal, which is the high-precision of java library. Please look at this [pull request](https://github.com/assertj/assertj-core/pull/2535).

**Comment by joel-costigliola** [comment]
We will thanks!

**Comment by YeeTone** [comment]
If you have any suggestions, or anything help wanted, please inform me and I am very pleased to contribute to this project!

**Comment by YeeTone** [comment]
Could you assign issue this to me? Thx! @joel-costigliola
