### ISSUE TITLE
`assertThat(comparable)` returns `ObjectAssert` instead of `AbstractComparableAssert`

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2557]
### Summary
Given a `Comparable<T>` variable, it's currently not possible to use assertions from [`ComparableAssert`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/ComparableAssert.html) unless `T` is `Object`.

Also, if the type implementing `Comparable` targets a parent type that is not `Object`, `assertThat` always returns `ObjectAssert` for both strongly-typed and `Comparable<T>` variables.

### Example: JDK type not comparing with `Object`

```java
Comparable<String> comparable = "value";

assertThat(comparable)            // ObjectAssert<Comparable<String>>
  .isEqualByComparingTo("value"); // does not compile
```

### Example: Custom type comparing with self

```java
class ComparingWithSelf implements Comparable<ComparingWithSelf> {
  @Override
  public int compareTo(ComparingWithSelf other) {
    return 0;
  }
}

Comparable<ComparingWithSelf> comparable = new ComparingWithSelf();

assertThat(comparable)                            // ObjectAssert<Comparable<ComparingWithSelf>>
  .isEqualByComparingTo(new ComparingWithSelf()); // does not compile

ComparingWithSelf comparingWithSelf = new ComparingWithSelf();

assertThat(comparingWithSelf)                     // AbstractComparableAssert<?, ComparingWithSelf>
  .isEqualByComparingTo(new ComparingWithSelf()); // compiles
```

### Example: Custom type comparing with parent

```java
class Parent {}

class ComparingWithParent extends Parent implements Comparable<Parent> {
  @Override
  public int compareTo(Parent other) {
    return 0;
  }
}

Comparable<Parent> comparable = new ComparingWithParent();

assertThat(comparable)                              // ObjectAssert<Comparable<Parent>>
  .isEqualByComparingTo(new ComparingWithParent()); // does not compile

ComparingWithParent comparingWithParent = new ComparingWithParent();

assertThat(comparingWithParent)                     // ObjectAssert<ComparingWithParent>
  .isEqualByComparingTo(new ComparingWithParent()); // does not compile
```

### Example: Custom type comparing with `Object`

```java
class ComparingWithObject implements Comparable<Object> {
  @Override
  public int compareTo(Object other) {
    return 0;
  }
}

Comparable<Object> comparable = new ComparingWithObject();

assertThat(comparable)                              // AbstractComparableAssert<?, Comparable<Object>
  .isEqualByComparingTo(new ComparingWithObject()); // compiles

ComparingWithObject comparingWithObject = new ComparingWithObject();

assertThat(comparingWithObject)                     // AbstractComparableAssert<?, ComparingWithObject>
  .isEqualByComparingTo(new ComparingWithObject()); // compiles
```

### Workaround: Raw type

```java
Comparable comparable = "value";  // "rawtypes" warning

assertThat(comparable)            // AbstractComparableAssert<?, Comparable> with "unchecked" warning
  .isEqualByComparingTo("value"); // compiles with "unchecked" warning
```

### Workaround: `asInstanceOf`

This works only with non-null instances due to the null-check performed in `asInstanceOf`.

```java
Comparable<String> comparable = "value";

assertThat(comparable)                    // ObjectAssert<Comparable<String>>
  .asInstanceOf(comparable(String.class)) // AbstractComparableAssert<?, String>
  .isEqualByComparingTo("value");         // compiles
```
### Current status

| `assertThat` use case                 | `Comparable<T>` variable   | Strongly-typed variable    |
|--------------------------------------|----------------------------|----------------------------|
| JDK type not comparing with `Object` | `ObjectAssert`             | N/A (dedicated assertions) |
| Custom type comparing with self      | `ObjectAssert`             | `AbstractComparableAssert` |
| Custom type comparing with parent    | `ObjectAssert`             | `ObjectAssert`             |
| Custom type comparing with `Object`  | `AbstractComparableAssert` | `AbstractComparableAssert` |

**Comment by scordio** [comment]
I tried restricting `ACTUAL` of `ComparableAssert`, from:

```java
ACTUAL extends Comparable<? super ACTUAL>
```

to:

```java
ACTUAL extends Comparable<ACTUAL>
```

Here is the result:

| Use case                              | `Comparable<T>` variable | Strongly-typed variable    |
|---------------------------------------|--------------------------|----------------------------|
| JDK type not comparing with  `Object` | compiles                 | N/A (dedicated assertions) |
| Custom type comparing with self       | compiles                 | compiles                   |
| Custom type comparing with parent     | does not compile         | does not compile           |
| Custom type comparing with  `Object`  | does not compile         | does not compile           |

While it fixes one case of `Comparable<T>` variable, it breaks another case of strongly-typed variable.

**Comment by YeeTone** [comment]
Can I try to contribute to fix this bugs? @scordio

**Comment by YeeTone** [comment]
Hi, could you assign this to me? I would like to fix this issue.

**Comment by joel-costigliola** [comment]
@YeeTone we are already on it with @scordio, thanks anyway.

**Comment by YeeTone** [comment]
Thx! Hope this bug could be fixed!
