### ISSUE TITLE
Java 11 to 17 -> BigDecimal intValue field no longer accessible (JPMS)

### ISSUE THREAD

**Issue by piewie** [assertj/assertj-core#2559]
#### Summary
Hi,

We are migrating our java code from 11 to 17 and use JPMS
With java 11 there was already a warning during running a testscenario where we do:
```java
 assertThat(value)
      .usingRecursiveComparison()
      .ignoringCollectionOrder()
      .isEqualTo(expected);
```

value is containing a BigDecimal and that gives the following warning:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.assertj.core.util.introspection.FieldUtils (file:/home/niels/.m2/repository/org/assertj/assertj-core/3.21.0/assertj-core-3.21.0.jar) to field java.math.BigDecimal.intVal
WARNING: Please consider reporting this to the maintainers of org.assertj.core.util.introspection.FieldUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

With java 17 the test no longer passes:
org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'intVal'.
Error when introspecting properties was :
- No getter for property 'intVal' in java.math.BigDecimal 
Error when introspecting fields was :
- Unable to obtain the value of the field <'intVal'> from <10.52>

The underlaying error:
Unable to make field private final java.math.BigInteger java.math.BigDecimal.intVal accessible: module java.base does not "opens java.math" to unnamed module @14ec4505

Thrown in PropertyOrFieldSupport -> getSimpleValue-method (fieldsupport.fieldValue(...))

#### Example

Easy way to reproduce the error
```java
assertThat(new BigDecimal("10.52"))
                .usingRecursiveComparison()
                        .isEqualTo(BigDecimal.valueOf(10.52));
```

**Comment by scordio** [comment]
Related to #2466 and #2450, fixed with 7406133f21ed66e3908a50c581ad0f0aaf059aa6.

Will be part of 3.23.0.
