### ISSUE TITLE
isSameAs failure text has 'actual' twice

### ISSUE THREAD

**Issue by frankbenoit** [assertj/assertj-core#2565]
https://github.com/assertj/assertj-core/blob/1d02a978b463bbd44865ed806f048838654260fb/src/main/java/org/assertj/core/error/ShouldBeSame.java#L33

````
java.lang.AssertionError: 
Expecting actual:
  ...
and actual:
  ...
to refer to the same object
````

I guess it should be only `Expecting:`

**Comment by scordio** [comment]
That was indeed weird. Thanks for reporting it, @frankbenoit!
