### ISSUE TITLE
Introspection.findGetter() should check "has" prefix for finding boolean properties

### ISSUE THREAD

**Issue by zartc** [assertj/assertj-core#2572]
#### Summary

Introspection.findGetter method only attempt to use "is" prefix to find boolean properties in a class. It should also try "has" as it is a frequently used prefix for boolean properties.

**Comment by scordio** [comment]
`findGetter` is in line with the Oracle's [JavaBeans specification](https://download.oracle.com/otn-pub/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/beans.101.pdf), chapter 8.3.2:

> In addition, for boolean properties, we allow a getter method to match the pattern:
> ```
> public boolean is<PropertyName>();
> ```
> This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method, or it may be provided in addition to a “get<PropertyName>” method.
> In either case, if the “is<PropertyName>” method is present for a boolean property then we will use the “is<PropertyName>” method to read the property value.
> An example boolean property might be:
> ```
> public boolean isMarsupial();
> public void setMarsupial(boolean m);
> ```

Honestly, I couldn't come up with any boolean property name that would have a meaningful "has" method. "has" feels more natural with collections, for example.

Could you provide a concrete example?

**Comment by zartc** [comment]
“`has`” prefix is often prefered to express the notion of an object _HAVING_ a value or a characteristic instead of the notion of an object _BEING_ of a certain kind or in a certain state.

#### Example:
```
interface Car {
    boolean isCabriolet();   // "is" prefix ok
    boolean isParked();

    boolean hasABS();        // "has" prefix is a better choice here than any isXXX
    boolean hasESBAudio()
}
```

**Comment by zartc** [comment]
But thinking a bit further, I find cases where the behavior could be ambiguous, such as when a class has a getXXX AND a hasXXX (like the classes generated by Google protobuf Generator). It would be difficult to tell AssertJ to call the getXXX method instead of the hasXXX method (or vice versa).

Thus I'm going to close this thread, because it could do more harm than good.
