### ISSUE TITLE
IterableAssert#containsOnlyNulls should pass for an empty list

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2595]
#### Summary

I just found that [IterableAssert#containsOnlyNulls](https://javadoc.io/static/org.assertj/assertj-core/3.22.0/org/assertj/core/api/AbstractIterableAssert.html#containsOnlyNulls()) fails when the `actual` is *empty*, **as documented**, yet I think the behaviour is not intuitive and somewhat misleading.

The `containsOnlyNulls` works as `containsOnlyNulls_AndShouldContainAtLeastOneNull`.

Sometimes a user may want to assert for a `List` which **may be empty** yet **should contain specific value only**.

I wonder is there any idiom for `mayBeEmptyYetContainsOnlyNulls`.

#### Example

```java
        final var page = repositoryInstance().findAllByParent(parent, Pageable.ofSize(128));
        assertThat(page)
                .doesNotContainNull()
                .extracting(Some_.PARENT)
                .allMatch(p -> (long) p == parent);
        assertThat(page.stream().filter(e -> e.getParent() == 0L))
                .extracting(Some::getParent_)
                .containsOnlyNulls(); // fails when empty
        assertThat(page.stream().filter(e -> e.getParent_() == null))
                .extracting(Some::getParent)
                .containsOnly(0L); // fails when empty
```

Should I do this or am I missing an existing idiom?

```java
        final var page = repositoryInstance().findAllByParent(parent, Pageable.ofSize(128));
        if (/** check the emptyness with same filtering?? */) {
            assertThat(page.stream().filter(e -> e.getParent() == 0L))
                    .extracting(Some::getParent_)
                    .containsOnlyNulls();
        }
```

Thank you.

**Comment by onacit** [comment]
And I just found that the `doesNotContainNull` pases with an empty list.

**Comment by onacit** [comment]
Getting confused more and more...
The `containsOnly` passes with an empty list with an zero-length values.

```java
        assertThat(Arrays.asList()).containsOnly(); // is this practically practical?
        assertThatThrownBy(() -> assertThat(Arrays.asList()).containsOnly(""))
                .isInstanceOf(AssertionError.class);
        assertThat(Arrays.asList("")).containsOnly("");
```

**Comment by joel-costigliola** [comment]
> I just found that `containsOnlyNulls` fails when the actual is empty, as documented, yet I think the behaviour is not intuitive and somewhat misleading.

the behavior of these kind of assertions is IMO always subject to different point of view, we have taken one and we won't change it unless given a real good reason.

> Sometimes a user may want to assert for a List which may be empty yet should contain specific value only. 

I would use [satisfiesAnyOf](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractAssert.html#satisfiesAnyOf(java.util.function.Consumer...)) to assert any of `isEmpty` or `containsOnly(value)`

> assertThat(Arrays.asList()).containsOnly(); // is this practically practical?

it can be practical when you pass an array for the vararg and the array turns out to be empty but that's part of the subject to interpretation assertion where there is no obvious way to go.
