### ISSUE TITLE
isUnmodifiable() fails with Collections.singleton and Collections.singletonList although they are unmodifiable

### ISSUE THREAD

**Issue by glhez** [assertj/assertj-core#2599]
AssertJ version: 3.22.0

The various implementation of `Collections.singleton`, `Collections.singletonList`, `Collections.singletonMap` all extends respectively `java.util.AbstractSet`, `java.util.AbstractList` and `java.util.AbstractMap` and are all being immutable.

The `org.assertj.core.api.AbstractCollectionAssert.assertIsUnmodifiable()` fails with the following assertions:

        assertThat(singleton("A")).isUnmodifiable();
        assertThat(singletonList("A")).isUnmodifiable();

The failure is fairly simple:

```
java.lang.AssertionError:
Expecting actual to be unmodifiable, but invoking
  "Collection.addAll(emptyCollection())"
succeeded instead of throwing java.lang.UnsupportedOperationException
	at
```

The reason behind the failure is due to default implementation of `addAll` in case of `AbstractList` (in fact `AbstractCollection`) which simply do a "add" and which does nothing with an empty collection.

I think it would be best to pass a collection of some element (a collection containing only null ?) rather than trying to pry on the collection concrete type, especially when some implementations may also exhibit the same problem, for example Guava `ImmutableList` do extends `AbstractCollection` : https://guava.dev/releases/23.0/api/docs/com/google/common/collect/ImmutableList.html

I can do a PR with that in mind, except if there is a better way.

There is no "isUnmodifiable" for map but I've seen #2381, so this would also apply to.

**Comment by scordio** [comment]
Thank you, @glhez.

Initially, I wanted to improve the current implementation and cover these types properly, but then I realized that some of the methods are just empty and there isn't much we can do in these cases.

For this reason, I've decided to skip the assertion based on the class' fully qualified name.

**Comment by glhez** [comment]
I was doing my PR at the same time and it was more or less the same algorithm that I used, although I used getCanonicalName().
