### ISSUE TITLE
Gitpod Integration Enhancement - Open With Gitpod Button

### ISSUE THREAD

**Issue by anugrahsinghal** [assertj/assertj-core#2604]
#### Summary

The `Open with Gitpod` Button, currently opens the upstream repo [assertj-core](https://github.com/assertj/assertj-core)/main.

For an easier contributor experience, when the user is on their fork the `Open with Gitpod` Button could directly open that fork on gitpod.

The gitpod button can be changed to point to the `user-specific fork/branch`.

Please let me know if this sounds like a good idea, I'd be willing to work on it.

**Comment by scordio** [comment]
Yes, it would be much better for user experience.

Do you already have an idea about how to deal with this? I saw [this thread](https://community.gitpod.io/t/how-to-specify-users-fork-instead-of-main-repository/639/3) but haven't had the chance to try the suggestions.

**Comment by anugrahsinghal** [comment]
Yeah, I do have an idea of how to deal with this.

I cannot find the original link that pointed me towards the solution.

the above [thread](https://community.gitpod.io/t/how-to-specify-users-fork-instead-of-main-repository/639/3) takes me directly to their discord.

**Comment by anugrahsinghal** [comment]
I recently made similar changes to the spring-cloud-aws project [here](https://github.com/awspring/spring-cloud-aws/pull/383)

**Comment by scordio** [comment]
I was eager to try it so I applied the changes but giving you the credit 😉

Thanks, @anugrahsinghal!
