### ISSUE TITLE
Gitpod Integraion - Bug

### ISSUE THREAD

**Issue by anugrahsinghal** [assertj/assertj-core#2605]
#### Summary
When Opening the repo on gitpod the build command specified on init fails
`mvnd verify license:format -DskipTests=true`

the full [log](https://github.com/assertj/assertj-core/files/8668670/build.log)

**Comment by scordio** [comment]
We couldn't reproduce the issue. Could it be you have some settings that are influencing the workspace?

**Comment by anugrahsinghal** [comment]
I was able to correctly build the application doing just `mvn`

Closing this.
