### ISSUE TITLE
Introduce extracting api to OptionalAssert

### ISSUE THREAD

**Issue by govi20** [assertj/assertj-core#2608]
#### Summary

I have an API which returns `Optional<CustomClass>`, Now I want to assert if an `Optional` is present and then I want to write an assertion on one of the fields of the CustomeClass object. Please refer sample code below

#### Example

```java

        Optional<ErrorMessage> errorMessageOptional = ... ;
        assertThat(errorMessageOptional).isPresent();
        assertThat(errorMessageOptional.get().getErrorMessage()).isEqualTo("Request Body is Mandatory");
```

This can be improved to:

```java

        Optional<ErrorMessage> errorMessageOptional = ... ;
        assertThat(errorMessageOptional).isPresent()
              .extracting(errorMessage -> errorMessage.getErrorMessage())
              .isEqualTo("Request Body is Mandatory");
```

**Comment by scordio** [comment]
This can be achieved with [`map`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractOptionalAssert.html#map(java.util.function.Function)) and [`get`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractOptionalAssert.html#get()):

```java
assertThat(errorMessageOptional)
  .map(ErrorMessage::getErrorMessage)
  .get()
  .isEqualTo("Request Body is Mandatory");
```

or with [`get`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractOptionalAssert.html#get()) and [`extracting`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function)):

```java
assertThat(errorMessageOptional)
  .get()
  .extracting(ErrorMessage::getErrorMessage)
  .isEqualTo("Request Body is Mandatory");
```

**Comment by scordio** [comment]
I am going to close this issue but please let us know if further clarifications are needed.

**Comment by onacit** [comment]
Please regard this comment as a pure comment.

I also reached here looking for `extracting` directly attached to the `OptionalAssert`.

Ways explained by @scordio are works. Thanks.

I'm guessing `map` or `get` have been introduced aligning those method names defined with the `Optional` class itself.

Yet I'm still favor to `extracting` or `mapping`.

```java
    @MethodSource({"getRecommendKeyList"})
    @ParameterizedTest
    void __(final String recommendKey) {
        final var found = repositoryInstance().findByRecommendKey(recommendKey);
        assertThat(found)
                .get()
                .extracting(MappedTbFriendRecommend::getRecommendKey)
                .isEqualTo(recommendKey);
        assertThat(found)
                .map(MappedTbFriendRecommend::getRecommendKey) // why not 'mapping'?
                .get()
                .isEqualTo(recommendKey);
        assertThat(found)
                .hasValueSatisfying(tfr -> {
                    assertThat(tfr.getRecommendKey()).isEqualTo(recommendKey);
                });
//        assertThat(found)
//                .extracting(MappedTbFriendRecommend::getRecommendKey) // not implemented yet
//                .mapping(MappedTbFriendRecommend::getRecommendKey) // not implemented yet; more intuitive, IMHO
//                .hasValue(recommendKey);
    }
```
