### ISSUE TITLE
`linesOf` variants for `Path` content

### ISSUE THREAD

**Issue by scordio** [assertj/assertj-core#2617]
`Path` related variants of [`linesOf`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Assertions.html#linesOf(java.io.File)) are currently not available.

**Comment by StefanBratanov** [comment]
If not assigned yet, is it possible that I give it a try? Keen to make a contribution. :) Thank you.

**Comment by joel-costigliola** [comment]
Sure, thanks @StefanBratanov.
