### ISSUE TITLE
NoSuchMethodError for asserting two objects since 3.20.0 version

### ISSUE THREAD

**Issue by topsycreed** [assertj/assertj-core#2646]
**Describe the bug**
Since 3.20.0 version there are an error when you are trying to assert two objects.

* assertj core version: since org.assertj:assertj-core:3.20.0 and newer
* java version: openjdk-17.0.2
* os (if relevant): MacOS 12.2.1 (but probably not relevant)

**Test case reproducing the bug**

Try to assert 

```java
Obj1 = actualAddress;
Obj2 = expectedAddress;

SoftAssertions assertion = new SoftAssertions();
table.asMaps().forEach(map -> {
    if (isNotBlank(actualAddress.toString())) {
        String expectedAddress = map.get("address");
        assertion.assertThat(actualAddress)
                .as(String.format("invalid address for %s", actualAddress))
                .isEqualTo(convertedAddress)
```
Error:
java.lang.NoSuchMethodError: ‘org.assertj.core.api.ObjectAssert
org.assertj.core.api.SoftAssertions.assertThat(java.lang.Object)'

**Comment by scordio** [comment]
Hi @topsycreed, what version were you using before?

Could you enhance your example to make it reproducible?

**Comment by topsycreed** [comment]
Hey @scordio It's working for org.assertj:assertj-core:3.19.0, give me some time to get an example

**Comment by topsycreed** [comment]
@scordio we were able to fix that issue with migrating to a new version of the library 'org.assertj:assertj-core:3.23.1', thanks!

**Comment by scordio** [comment]
Cool, thanks for the feedback, @topsycreed!
