### ISSUE TITLE
Published Javadoc has broken search

### ISSUE THREAD

**Issue by pkubowicz** [assertj/assertj-core#2684]
**Describe the bug**
Javadoc linked on the main page does not allow to search.

**Test case reproducing the bug**

1. Go to https://assertj.github.io/doc/#assertj-core-javadoc and click the link (http://www.javadoc.io/doc/org.assertj/assertj-core/)
2. Start typing "ObjectAssert"; window focus should be on the "search" input in the top-right corner, if it's not, click the input
3. Try to use keyboard (Enter key) or mouse to select any of search results

Expected:
- you can open a search result like on https://docs.oracle.com/en/java/javase/17/docs/api/

Actual:
- no way to open search results; they appear but are not clickable and Enter key pressed in the search input has no effect

**Comment by scordio** [comment]
It seems it's a local issue with cookies, clearing them should fix it.

Related: maxcellent/javadoc.io#97

**Comment by pkubowicz** [comment]
I tried opening JavaDoc in a private window of Chrome (102.0.5005.115) and Firefox (101.0.1) and still nothing works. I think this simulates a case of a new visitor with no cookies opening JavaDoc. Have you even tried if this works for you?

**Comment by scordio** [comment]
Yes, I did exactly these tries yesterday: https://github.com/maxcellent/javadoc.io/issues/97#issuecomment-1164192984

**Comment by scordio** [comment]
@pkubowicz @lkucik and even after clearing cookies for javadoc.io, it still doesn't work, right?

**Comment by joel-costigliola** [comment]
it works for me with ffox 101.0.1 (64-bit) on linux

**Comment by pkubowicz** [comment]
> and even after clearing cookies for javadoc.io, it still doesn't work, right?

I don't need to clear cookies. I checked Firefox web inspector and it shows no cookies for domain when opening the page in a private window. I suspect private mode in Firefox rejects all cookies.

**Comment by pkubowicz** [comment]
I just reproduced this on a different computer. I cleared cookies in the normal mode (although I had no cookies as I have probably never visisted javadoc.io on this machine). When clicking a search result I see an error in JS console:
```
Uncaught TypeError: parent.classFrame is undefined
    select https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/search.js:346
    jQuery 37
    _create https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/search.js:124
    jQuery 7
    <anonymous> https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/search.js:294
    jQuery 13
```
I suspect the problem may be in your browser: you can have outdated JS files that work, I load fresh JS files and they are broken.

**Comment by scordio** [comment]
As mentioned in https://github.com/maxcellent/javadoc.io/issues/97#issuecomment-1165695636, there is an ongoing migration activity on javadoc.io, and not all the versions are working properly. The migration may take another two weeks to complete.

**Comment by scordio** [comment]
From https://github.com/maxcellent/javadoc.io/issues/97#issuecomment-1165729049:

> so this is likely a caching issue from CDN. I have purged everything. Now if you do Ctrl + refresh it should work now.
>
> I have test both Chrome and Firefox against latest version.

@pkubowicz @lkucik could you please check again? I've tried it and it looks good on my side.

**Comment by scordio** [comment]
Closing as the issue seems to be fixed now. @pkubowicz @lkucik please let us know if this is not the case for you.

**Comment by pkubowicz** [comment]
Works fine now, thank you.
