### ISSUE TITLE
Potential Refactoring Estimate

### ISSUE THREAD

**Issue by alvintanjianjia** [assertj/assertj-core#2695]
**Summary**
I have identified a few classes with refactoring potential, specifically PredicateAssert_accepts_Test.java. The class was refactored once on Aug 16, 2020  along with other classes in commit 95e3cf978bfa3cb444ae12dd2f4fc374d7606a86. Given the duration of the last refactoring, could it be possible to improve this class further? I am probably not qualified and experienced enough to point out the exact code needs to be refactored, given my limited knowledge of the project and codebase.

**Urgency**
Low priority. For maintenance of code in the long run.

Hi,
I am currently doing some research on Estimating Time Taken for Software Refactoring. Assertj is one of my case studies being a highly popular project. Would appreciate your kind feedback on the appropriateness of the estimated time to refactor. The estimated time is based on historical commits containing refactoring and the complexity of the involved classes.
I am specifically looking at potential for refactoring, such as breaking functions that are too long into shorter functions, or to remove code duplication. Would you agree that there could be some modification to the code to make it better in the listed classes? And if so, is the estimated time appropriate to carry out the improvement? I will be grateful for any help you can provide.

1. PredicateAssert_accepts_Test.java - 6.5 hours
2. PredicateAssert_acceptsAll_Test.java - 6 hours
3. PredicateAssert.java - 1 hour

Thank you.

Regards,
Alvin

**Comment by scordio** [comment]
I'm not sure I understand your target here.

You talk about potential refactoring with estimates but at the same time say you're not familiar with the codebase and the scope is quite vague.

Looking at your GitHub profile, you opened dozens of similar issues with other projects. It sounds like a script-based activity.

Our capacity is limited and we cannot help with this exercise. I'm going to close this issue but I'm happy to reopen it if there is a concrete value for the project.
