### ISSUE TITLE
Maintain binary compatibility in minor releases

### ISSUE THREAD

**Issue by mkm-dt** [assertj/assertj-core#2700]
#### Feature summary
AssertJ is a great library, and we use it a lot internally, but unfortunately, it's also a recurring source of problems because of binary incompatibilities of minor releases. Please consider using semver or something similar to clearly show incompatibilities and make it possible to resolve conflicts automatically (or fail early if that's not possible). In our company, with multiple testing-related libraries using assertJ, we can only chose between two bad options:

1. We can hope that everything works, which it does most of the time. But when things do break because of a version update somewhere in the dependency chain, they usually do so at test runtime in a project other than the one that did the actual update. This is a very bad failure mode, as it requires quite a bit of work to analyze and fix the problem across multiple projects, updating to the same assertj version everywhere.
2. We could try to ensure (via gradle's `strictly` versioning) that all dependencies use the same assertj version. This moves the failures to build time and prevents (potentially) incompatible versions from being introduced, but does nothing to make upgrades easier. On the contrary, it requires updating all our libraries in lockstep not only for _actually_ incompatible versions, but for any version upgrades.

Seeing the issues returned by [searching for "binary"](https://github.com/assertj/assertj-core/issues?q=is%3Aissue+binary), I'm quite sure we are not the only ones being plagued by this problem.

Please consider making assertJ even greater by eliminating this -- in my personal view -- unnecessary hassle.

**Comment by scordio** [comment]
Hi @mkm-dt, thanks for your feedback.

Some thoughts about the versioning used in AssertJ are in #2148, especially:

> Minor versions usually provide new features but potentially also breaking changes

However, starting from 3.21.0, we introduced [automated checks](https://github.com/assertj/assertj-core/actions/workflows/binary-compatibility.yml) and [contribution guidelines](https://github.com/assertj/assertj-core/blob/main/CONTRIBUTING.md#binary-compatibility) for binary compatibility to better assess the impact of our changes.

In general, we try not to break it unless the change really outweighs the broken compatibility, something we evaluate very carefully.

I am going to close this issue but happy to continue the conversation in #2148 in case you have any additional thoughts.

**Comment by mkm-dt** [comment]
Thanks for your quick reply! I did read your description of the current state, which is why I filed this feature request in the first place. I think regularly breaking binary compatibility in minor versions, in random places where it may or may not bite consumers when upgrading, is a bad thing[TM], whether it's documented nicely or not. I do hope this will get better in the next releases, but if not, I'd really appreciate you encoding that information in the version number.

**Comment by scordio** [comment]
> I'd really appreciate you encoding that information in the version number

There is a proposal at https://github.com/assertj/assertj-core/discussions/2148#discussioncomment-2298524 for a four-part version number.

We haven't yet made a decision on this and may consider it for AssertJ 4.
