### ISSUE TITLE
Making it easier to use existing assertions in a "soft assert" context

### ISSUE THREAD

**Issue by fge** [assertj/assertj-core#283]
When writing a custom assertion, if you want it to be "compatible" with soft assertions you have to use inherited methods when you want to fail, as [this example](http://joel-costigliola.github.io/assertj/assertj-core-custom-assertions.html) demonstrates (`failWithMessage()`, `isNotNull()`).

Unfortunately this becomes quite cumbersome when you have a lot of custom methods for this assertion; ideally, I'd like to be able to reuse existing assertions in this context... For instance, to test equality of two objects, I'd love to be able to write something like `assertThat(actual.myField).isNotNull()` and that it be compatible when used with `SoftAssertions`.

I have tried to use the builtin classes (`Objects.instance()`, etc) to no avail; when I assert using those, an error is still a "hard" assertion.

Is it possible with the current versions to reuse existing assertions to this effect (I use 1.7.0)?

**Comment by joel-costigliola** [comment]
@fge is still an issue for you, if so could you provide a small code example that we could use ?

**Comment by joel-costigliola** [comment]
closing due to lack of feedback
