### ISSUE TITLE
Shorter way to initialize what is now an AutoCloseableSoftAssertions?

### ISSUE THREAD

**Issue by fge** [assertj/assertj-core#628]
Right now, the code to use is:

``` java
try (
    final AutoCloseableSoftAssertions soft = new AutoCloseableSoftAssertions();
) {
    // assertions here
}
```

But that is very long to write.

What about this?

``` java
try (
    final DelayedAssertions delayed = DelayedAssertions.create();
) {
    // assertions here
}
```

And the `close()` method would call something like `delayed.assertNow()`? (or `assertAll()`; I believe however that in this scenario `assertNow()` is more talkative)

**Comment by joel-costigliola** [comment]
Although I like the name `DelayedAssertions`, I think we already have enough different Soft assertions classes not to add another one even if it's only an alias.

I would agree though to have a soft assertions factory class, if you think that can help, it would provide the different methods to build different soft assertions.

**Comment by joel-costigliola** [comment]
Closing it since we have enough ways of soft asserting.
