### ISSUE TITLE
Add satisfies with checked exceptions consumer.

### ISSUE THREAD

**Issue by mgorniew** [assertj/assertj-core#731]
Hello,

Currently it is not possible to write code like that:

``` java

assertThat(item).satisfies(i -> {
   assertThat(i.getContent()).isEqualTo("data"); // i.getContent() throws IOException
});
```

Would it be possible to add satisfies method which can handle consumer throwing checked exception? If exception would be thrown then it would be assumed that condition failed.

Thanks,
Michał

**Comment by joel-costigliola** [comment]
I believe it is not possible at the AssertJ level, you would need to use something like `LambdaExceptionUtil` as described in http://stackoverflow.com/questions/27644361/how-can-i-throw-checked-exceptions-from-inside-java-8-streams.

**Comment by mgorniew** [comment]
First answer in link that you posted suggested that this is in fact ```java.util.function``` API design error. But AssertJ defines its own API, which doesn't extend Java SDK API. So you could define interface like this:

```
import java.util.function.Consumer;

@FunctionalInterface
public interface CheckedConsumer<T> {
    void accept(T value) throws Exception;
    
    static <T> Consumer<T> toConsumer(CheckedConsumer<T> checkedConsumer) {
        return value -> {
            try {
                checkedConsumer.accept(value);
            } catch (Exception ex) {
                throw new RuntimeException(ex);
            }
        };
    }
}
```

This interfaces would be used as satisfies method parameter.

**Comment by PascalSchumacher** [comment]
@joel-costigliola  I a solution would be similar to the one for `extracting` contributed in https://github.com/joel-costigliola/assertj-core/pull/963

**Comment by joel-costigliola** [comment]
Good point @PascalSchumacher, that should be possible indeed.
