### ISSUE TITLE
Use mutation testing (Pitest) for the AssertJ tests

### ISSUE THREAD

**Issue by filiphr** [assertj/assertj-core#778]
I created this issue, so we can have a discussion.

I have played around with pitest and the tests in AssertJ. Setting up pitest for AssertJ is pretty simple. There is an example of a setup in my [branch](https://github.com/filiphr/assertj-core/tree/pitest-setup), [this](https://github.com/filiphr/assertj-core/commit/cbd3e9295a43c04d13bc14ba948bf8416f939ace) commit specifically.

A full pitest analysis on the entire AssertJ codebase takes 25 minutes. It also supports [incremental analysis](http://pitest.org/quickstart/incremental_analysis/), but I haven't tried it yet.

Once the analysis is done an HTML report is created in `target/pit-reports/`.

**Comment by fduminy** [comment]
@filiphr I have updated your patch on [my branch](https://github.com/fduminy/assertj-core/commits/pitest-setup)

**Comment by scordio** [comment]
pitest has been added with 81ed66f4710138d30e4a4b5ab83ef2989e7f39dd.
